/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   `mailwoman gazetteer overture-ingest` — Overture Maps addresses-theme ingest + per-country
 *   fill-rate probe (#471, epic #470).
 *
 *   Pulls address rows for a pinned Overture release into per-country local Parquet via DuckDB with
 *   predicate pushdown (megabytes per country — never the planet), and emits the fill-rate report
 *   that gates every downstream Overture issue (#472-#477): per-country row counts, field fill
 *   percentages, observed source datasets, and OpenAddresses-lineage share.
 *
 *   Standing rules encoded here (see epic #470 "pre-registered decision rules"):
 *
 *   - The release is pinned in every artifact path. The addresses theme is ALPHA; rows churn between
 *       monthly releases. Two releases never mix in one artifact.
 *   - The per-row `sources` array is preserved verbatim — it is what makes leakage-free eval filtering
 *       possible (#472) and satisfies the provenance-per-row rule.
 *   - Overture's `id` (GERS) rides along as a nullable passthrough column. Nothing joins on it.
 *
 *   The probe (fill-rates.json + fill-rates.md) runs against the LOCAL Parquet after ingest, so it is
 *   exact for what we materialized and costs no second remote scan.
 *
 *   Progress streams to stderr; the final summary is on stdout. The per-country Parquet + the
 *   fill-rates report are written DIRECTLY under `<out>/<release>/` (Parquet/JSON artifacts, not a
 *   SQLite DB — no atomic temp-swap applies); this preserves the original
 *   `scripts/ingest-overture-addresses.ts` behavior verbatim.
 */

import { dataRootPath } from "@mailwoman/core/utils"
import { Box, Text } from "ink"
import { mkdirSync, writeFileSync } from "node:fs"
import * as path from "node:path"
import { useEffect, useState } from "react"
import zod from "zod"

import type { CommandComponent } from "../../sdk/cli.js"

const DEFAULT_RELEASE = "2026-05-20.0"
const S3_GLOB = (release: string) =>
	`s3://overturemaps-us-west-2/release/${release}/theme=addresses/type=address/*.parquet`

/** Fields whose fill rate the report tracks — the gate inputs for #472-#477. */
const FILL_FIELDS = ["postcode", "street", "number", "unit", "postal_city"] as const

interface CountryProbe {
	country: string
	rows: number
	fill_pct: Record<string, number>
	address_levels_pct: number
	datasets: Record<string, number>
	oa_lineage_pct: number
}

const OptionsSchema = zod.object({
	release: zod.string().optional().describe(`Pinned Overture release. Default ${DEFAULT_RELEASE}`),
	countries: zod.string().optional().describe("ISO 3166-1 alpha-2, comma-separated, e.g. US,DE,FR (required)"),
	limit: zod.string().optional().describe("Cap rows per country (debug)"),
	out: zod.string().optional().describe("Output root. Default <data-root>/overture"),
	probeOnly: zod.boolean().default(false).describe("Skip ingest; probe the already-materialized local Parquet"),
	corpusJsonl: zod.boolean().default(false).describe("Also emit the flattened corpus-input JSONL per country"),
})

export { OptionsSchema as options }

function renderMarkdown(release: string, probes: CountryProbe[]): string {
	const lines = [
		`# Overture addresses fill-rate report — release ${release}`,
		"",
		`Generated by \`mailwoman gazetteer overture-ingest\` (#471). Gate rule (epic #470): no`,
		`downstream issue proceeds on a country whose relevant field fills <80% without a note.`,
		"",
		"| country | rows | postcode | street | number | unit | postal_city | address_levels | OA-lineage |",
		"| --- | --: | --: | --: | --: | --: | --: | --: | --: |",
	]
	for (const p of probes) {
		lines.push(
			`| ${p.country} | ${p.rows.toLocaleString("en-US")} | ${p.fill_pct.postcode}% | ${p.fill_pct.street}% | ` +
				`${p.fill_pct.number}% | ${p.fill_pct.unit}% | ${p.fill_pct.postal_city}% | ` +
				`${p.address_levels_pct}% | ${p.oa_lineage_pct}% |`
		)
	}
	lines.push("", "## Observed source datasets (per country)", "")
	for (const p of probes) {
		lines.push(`### ${p.country}`, "")
		for (const [ds, n] of Object.entries(p.datasets)) {
			lines.push(`- \`${ds}\` — ${n.toLocaleString("en-US")} rows`)
		}
		lines.push("")
	}
	return lines.join("\n")
}

const GazetteerOvertureIngest: CommandComponent<typeof OptionsSchema> = ({ options }) => {
	const [error, setError] = useState<string>()
	const [summary, setSummary] = useState<string[]>()

	useEffect(() => {
		void (async () => {
			try {
				if (!options.countries) {
					setError("--countries is required (ISO 3166-1 alpha-2, comma-separated, e.g. US,DE,FR)")
					return
				}

				const release = options.release ?? DEFAULT_RELEASE
				const countries = options.countries.split(",").map((c) => c.trim().toUpperCase())
				const limit = options.limit ? Number.parseInt(options.limit, 10) : undefined
				const outRoot = options.out ?? dataRootPath("overture")
				const outDir = path.join(outRoot, release)
				mkdirSync(outDir, { recursive: true })

				// @duckdb/node-api is an optional peer dep (this is a maintainer-only data command) — load
				// it dynamically so merely importing this command (e.g. `mailwoman --help`) doesn't fault
				// when the native binding isn't installed.
				const { DuckDBInstance } = await import("@duckdb/node-api")
				const instance = await DuckDBInstance.create()
				const db = await instance.connect()

				// Anonymous access to the public Overture bucket — region only, no credentials.
				await db.run("INSTALL httpfs; LOAD httpfs;")
				await db.run("INSTALL spatial; LOAD spatial;")
				await db.run("SET s3_region='us-west-2';")

				const countryParquet = (cc: string) => path.join(outDir, `addresses-${cc.toLowerCase()}.parquet`)

				/**
				 * Materialize one country into local Parquet. Column set preserves the Overture schema
				 * verbatim (nested `sources` + `address_levels` included) plus lon/lat decoded from the WKB
				 * point via the spatial extension.
				 */
				const ingestCountry = async (cc: string): Promise<void> => {
					const limitClause = limit ? `LIMIT ${limit}` : ""
					const dest = countryParquet(cc)
					const started = Date.now()
					await db.run(`
						COPY (
							SELECT
								id,
								country,
								postcode,
								street,
								number,
								unit,
								address_levels,
								postal_city,
								sources,
								version,
								ST_X(geometry) AS lon,
								ST_Y(geometry) AS lat
							FROM read_parquet('${S3_GLOB(release)}', hive_partitioning = 1)
							WHERE country = '${cc}'
							${limitClause}
						) TO '${dest}' (FORMAT PARQUET, COMPRESSION SNAPPY)
					`)
					const secs = ((Date.now() - started) / 1000).toFixed(0)
					console.error(`[ingest] ${cc} -> ${dest} (${secs}s)`)
				}

				/**
				 * Emit the flattened corpus-input JSONL the `overture` corpus adapter consumes (`{ street,
				 * number, unit, postcode, locality }`), so `@mailwoman/corpus` stays free of the heavy
				 * native DuckDB binding. `street` is kept WHOLE (keyword included); the downstream
				 * affix-relabel splits `street_prefix`. `locality` flattens the `address_levels`
				 * municipality (the deepest level) with a `postal_city` fallback.
				 */
				const emitCorpusJsonl = async (cc: string): Promise<void> => {
					const src = countryParquet(cc)
					const dest = path.join(outDir, `overture-${cc.toLowerCase()}.corpus.jsonl`)
					await db.run(`
						COPY (
							SELECT
								street,
								number,
								unit,
								postcode,
								COALESCE(NULLIF(trim(postal_city), ''), address_levels[len(address_levels)].value) AS locality
							FROM read_parquet('${src}')
							WHERE street IS NOT NULL AND trim(street) <> ''
								AND (
									(postcode IS NOT NULL AND trim(postcode) <> '')
									OR len(address_levels) > 0
									OR (postal_city IS NOT NULL AND trim(postal_city) <> '')
								)
						) TO '${dest}' (FORMAT JSON)
					`)
					console.error(`[corpus-jsonl] ${cc} -> ${dest}`)
				}

				/** Probe one country's LOCAL Parquet for the fill-rate report. */
				const probeCountry = async (cc: string): Promise<CountryProbe | null> => {
					const src = countryParquet(cc)
					const fillExprs = FILL_FIELDS.map(
						(f) => `round(100.0 * count(nullif(trim(${f}), '')) / count(*), 1) AS ${f}_pct`
					).join(",\n\t\t\t")

					const totals = await db.runAndReadAll(`
						SELECT
							count(*)::BIGINT AS rows,
							${fillExprs},
							round(100.0 * count(*) FILTER (len(address_levels) > 0) / count(*), 1) AS address_levels_pct,
							round(100.0 * count(*) FILTER (
								len(list_filter(sources, s -> s.dataset ILIKE '%openaddress%')) > 0
							) / count(*), 1) AS oa_lineage_pct
						FROM read_parquet('${src}')
					`)
					const row = totals.getRowObjects()[0] as Record<string, unknown>
					if (!row || Number(row.rows) === 0) return null

					const datasetRows = await db.runAndReadAll(`
						SELECT u.dataset AS dataset, count(*)::BIGINT AS n
						FROM (SELECT unnest(sources) AS u FROM read_parquet('${src}'))
						GROUP BY 1 ORDER BY n DESC
					`)
					const datasets: Record<string, number> = {}
					for (const d of datasetRows.getRowObjects() as { dataset: string; n: bigint }[]) {
						datasets[d.dataset ?? "(null)"] = Number(d.n)
					}

					const fill_pct: Record<string, number> = {}
					for (const f of FILL_FIELDS) fill_pct[f] = Number(row[`${f}_pct`])

					return {
						country: cc,
						rows: Number(row.rows),
						fill_pct,
						address_levels_pct: Number(row.address_levels_pct),
						datasets,
						oa_lineage_pct: Number(row.oa_lineage_pct),
					}
				}

				const probes: CountryProbe[] = []
				for (const cc of countries) {
					if (!options.probeOnly) await ingestCountry(cc)
					if (options.corpusJsonl) await emitCorpusJsonl(cc)
					const probe = await probeCountry(cc)
					if (probe) {
						probes.push(probe)
						console.error(
							`[probe] ${cc}: ${probe.rows} rows · postcode ${probe.fill_pct.postcode}% · ` +
								`postal_city ${probe.fill_pct.postal_city}% · OA-lineage ${probe.oa_lineage_pct}%`
						)
					} else {
						console.error(`[probe] ${cc}: no rows found — check the country code or release`)
					}
				}

				writeFileSync(path.join(outDir, "fill-rates.json"), JSON.stringify({ release, probes }, null, "\t"))
				writeFileSync(path.join(outDir, "fill-rates.md"), renderMarkdown(release, probes))
				console.error(`[done] report -> ${path.join(outDir, "fill-rates.{json,md}")}`)

				db.closeSync()

				const lines = [
					`overture ingest: ${outDir}`,
					`release ${release} · ${countries.join(",")} · ${probes.length} probed`,
					`report: fill-rates.json + fill-rates.md`,
					...probes.map(
						(p) =>
							`${p.country}: ${p.rows.toLocaleString("en-US")} rows · postcode ${p.fill_pct.postcode}% · OA ${p.oa_lineage_pct}%`
					),
				]
				setSummary(lines)
			} catch (e) {
				setError(e instanceof Error ? e.message : String(e))
			}
		})()
	}, [options])

	useEffect(() => {
		if (summary || error) setImmediate(() => process.exit(error ? 1 : 0))
	}, [summary, error])

	if (error) return <Text color="red">✗ {error}</Text>
	if (summary) {
		return (
			<Box flexDirection="column">
				{summary.map((line, i) => (
					<Text key={i} color={i === 0 ? "green" : undefined}>
						{i === 0 ? "✓ " : "  "}
						{line}
					</Text>
				))}
			</Box>
		)
	}
	return null // progress streams to stderr until the summary lands
}

export default GazetteerOvertureIngest
