/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 */

import { writeLocalFile } from "@mailwoman/core/fs/writers"
import { makeLcg } from "@mailwoman/core/random"

import { resolveEntities, type SourceRecord } from "#index"

/**
 * Options for {@linkcode matcherScale}.
 */
export interface MatcherScaleOptions {
	/**
	 * Lists the record counts to measure, defaulting to 10,000, 50,000, 100,000, 250,000 and 500,000.
	 */
	sizes?: number[]

	/**
	 * Sets the average number of records per distinct synthetic place, defaulting to 3.
	 */
	dup?: number

	/**
	 * Fits the Fellegi-Sunter m and u probabilities with EM at each size,
	 * which is slower, and defaults to `false`.
	 */
	em?: boolean

	/**
	 * Gives a path where the Markdown report is also written.
	 */
	outMd?: string
}

function generate(n: number, dup: number, seed = 1): SourceRecord[] {
	const rnd = makeLcg(seed || 1)
	const places = Math.max(1, Math.round(n / dup))
	const records: SourceRecord[] = new Array(n)

	for (let i = 0; i < n; i++) {
		const place = i % places
		const latitude = 25 + rnd() * 24
		const longitude = -124 + rnd() * 57
		const variant = i < places ? "" : rnd() < 0.5 ? " llc" : " inc"

		records[i] = {
			id: String(i),
			organization: { canonical: `org ${place}${variant}`, raw: `Org ${place}` },
			address: {
				components: {},
				canonicalKey: `key-${place}`,
				raw: `${place} main st`,
				geocode: {
					coordinate: { latitude: latitude + (place % 7) * 1e-4, longitude: longitude + (place % 5) * 1e-4 },
					tier: "address_point",
					uncertaintyMeters: 5,
				},
			},
		} as SourceRecord
	}

	return records
}

const mb = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(0)} MB`
const sec = (ms: number) => `${(ms / 1000).toFixed(2)} s`

/**
 * Measures entity-resolution time, candidate pairs and memory on synthetic records
 * of increasing size, all in one Node process.
 *
 * The Markdown report is printed to stdout, returned, and also written to `outMd` when that option is set.
 */
export async function matcherScale(
	options: MatcherScaleOptions = {},
	report?: (line: string) => void
): Promise<{ markdown: string }> {
	const SIZES = options.sizes?.length ? options.sizes : [10_000, 50_000, 100_000, 250_000, 500_000]
	const DUP = options.dup ?? 3
	const EM = options.em ?? false
	const OUT_MD = options.outMd || ""

	interface Measurement {
		n: number
		records: number
		entities: number
		candidatePairs: number
		wallMs: number
		rssBytes: number
	}

	const rows: Measurement[] = []

	for (const n of SIZES) {
		const records = generate(n, DUP)
		const t0 = performance.now()

		const { entities, candidatePairs } = resolveEntities(records, {
			collapseSpatial: true,
			trainEM: EM,
			learnedScorer: false,
		})

		const wallMs = performance.now() - t0
		const rssBytes = process.memoryUsage().rss
		rows.push({ n, records: records.length, entities: entities.length, candidatePairs, wallMs, rssBytes })
		report?.(`    N=${n}: ${sec(wallMs)}, ${candidatePairs} pairs → ${entities.length} entities, RSS ${mb(rssBytes)}`)

		if (globalThis.gc) {
			globalThis.gc()
		}
	}

	const lines: string[] = [
		`# Matcher scale — pure-Node block → score → cluster (#K)`,
		"",
		`_Generated by \`registry/tools/matcher-scale.ts\`. Synthetic geo-clustered records (~${DUP} per ` +
			`distinct place), resolved with the geo-first baseline (collapsed spatial${EM ? " + EM" : ""}) in one Node ` +
			`process without Elasticsearch or a server. Geocoding is out of scope (measured separately); this isolates the ` +
			`matcher's block/score/cluster cost vs N._`,
		"",
		`| records | candidate pairs | entities | wall-clock | resolve rate | RSS (high-water) |`,
		`|---:|---:|---:|---:|---:|---:|`,
	]

	for (const r of rows) {
		const rate = Math.round(r.records / (r.wallMs / 1000))

		lines.push(
			`| ${r.records.toLocaleString()} | ${r.candidatePairs.toLocaleString()} | ${r.entities.toLocaleString()} | ` +
				`${sec(r.wallMs)} | ${rate.toLocaleString()}/s | ${mb(r.rssBytes)} |`
		)
	}

	lines.push("")
	lines.push(`## Reading`)
	lines.push("")
	const last = rows.at(-1)!

	lines.push(
		`The matcher resolves **${last.records.toLocaleString()} records in ${sec(last.wallMs)}** in a single Node ` +
			`process (block → Fellegi-Sunter → union-find clustering) without an external service. Geo-cell + canonical-key ` +
			`blocking keeps candidate generation near-linear (it never enumerates the O(n²) pair space), so the wall-clock ` +
			`scales with the number of *blocked* pairs, not the square of N. That is the architectural claim made ` +
			`concrete: a calibrated street-level geocoder feeding the blocking lets entity resolution run in-process at ` +
			`hundreds of thousands of records, where a string-similarity matcher would need a search cluster to make the ` +
			`candidate generation tractable.`
	)

	lines.push("")

	lines.push(
		`RSS is the shared-process high-water mark across the sweep (each size reuses the heap), so it is an upper ` +
			`bound, not a per-N working set. The largest size that fits is bounded by the record objects + the link array; ` +
			`beyond that, extract by geography (each cell is independent) — the same partition the blocking already implies.`
	)

	lines.push("")

	lines.push(
		`One honest caveat on the shape: these are uniform-random US coordinates, so as N rises the geo-cell collision ` +
			`rate climbs and the candidate-pair count grows faster than N (visible in the table). Real address data clusters ` +
			`into a roughly fixed set of places, so its pair/record ratio is flatter — the wall-clock here, which tracks the ` +
			`number of PAIRS, is a conservative upper bound on a realistic workload of the same N.`
	)

	lines.push("")

	const md = lines.join("\n")

	console.log(md)

	if (OUT_MD) {
		await writeLocalFile(md, OUT_MD)
		report?.(`[written] ${OUT_MD}`)
	}

	return { markdown: md }
}
