/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   Single-token venue-class hints over `data/venue-word-hints.json` — the MINED sibling of the
 *   curated synonym table. Where a synonym entry says "this phrase NAMES a category" ('drinking
 *   fountain' → `drinking_water`), a venue-word hint says "this token is overwhelmingly attested in
 *   venue names of one class" ('teppanyaki' → food, 'juzgado' → civic, 'cemetery' → civic). The
 *   table is a survey artifact, regenerated by `scripts/build-venue-word-hints.ts`, never
 *   hand-edited; its provenance block records the source md5 and the composed bars.
 *
 *   REGISTRY DOCTRINE APPLIES: a hint is POSITIVE evidence only — a soft prior a consumer may add
 *   to a venue/POI hypothesis. The absence of a token here means "the survey has nothing to say",
 *   never "not a venue word", and no consumer may filter or veto on a miss. The composed measure
 *   behind the table exists because raw venue-frequency is toponym-saturated (famous place names
 *   dominate venue names); see the generator header for the bars and their measured families.
 */

import { readPackagedTable } from "#packaged-data"

/**
 * One mined hint row. Rates are per-million tokens of the respective name corpus; shares are of the token's poi
 * occurrences.
 */
export interface VenueWordHint {
	/**
	 * The dominant category CLASS (food, retail, civic, health, lodging, transit, burial, …) — the grain a single token
	 * reliably predicts.
	 */
	topClass: string
	topClassShare: number
	/**
	 * The dominant LEAF category, carried for consumers that can use the sharper grain. Its share is typically far below
	 * the class share — act on it only when it clears the consumer's own bar.
	 */
	topCategory: string | null
	topCategoryShare: number
	venueRatio: number
	poiFreq: number
	placeRatePPM: number
}

export interface VenueWordHintTable {
	version: number
	provenance: {
		source: string
		sourceMD5: string
		bars: {
			venueRatioMin: number
			poiFreqMin: number
			topClassShareMin: number
			placeRatePPMMax: number
		}
	}
	hints: Record<string, VenueWordHint>
}

const TABLE = await readPackagedTable<VenueWordHintTable>("venue-word-hints.json")
const HINTS = new Map<string, VenueWordHint>(Object.entries(TABLE.hints))

/**
 * The mined class hint for a single lowercased token, or `null` when the survey has nothing to say. Callers pass one
 * token — the table is token-grained by construction; n-gram extraction from longer queries belongs to the kind
 * classifier, mirroring the phrase-lookup contract.
 */
export function venueWordHint(token: string): VenueWordHint | null {
	return HINTS.get(token.toLowerCase()) ?? null
}

/**
 * The table's provenance block, for consumers that surface receipts.
 */
export function venueWordHintProvenance(): VenueWordHintTable["provenance"] {
	return TABLE.provenance
}

/**
 * Number of tokens carrying a hint.
 */
export function venueWordHintCount(): number {
	return HINTS.size
}
