/**
 * @copyright Sister Software.
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 */

import type { CountryName } from "./names.ts"

/**
 * @category Country
 * @title Country ISO 3166-1 Alpha-2 code
 * @public
 */
export const CountryISO2 = {
	Afghanistan: "AF",
	Albania: "AL",
	Algeria: "DZ",
	"American Samoa": "AS",
	Andorra: "AD",
	Angola: "AO",
	Anguilla: "AI",
	Antarctica: "AQ",
	"Antigua and Barbuda": "AG",
	Argentina: "AR",
	Armenia: "AM",
	Aruba: "AW",
	Australia: "AU",
	Austria: "AT",
	Azerbaijan: "AZ",
	Bahamas: "BS",
	Bahrain: "BH",
	Bangladesh: "BD",
	Barbados: "BB",
	Belarus: "BY",
	Belgium: "BE",
	Belize: "BZ",
	Benin: "BJ",
	Bermuda: "BM",
	Bhutan: "BT",
	Bolivia: "BO",
	"Bonaire, Sint Eustatius and Saba": "BQ",
	"Bosnia and Herzegovina": "BA",
	Botswana: "BW",
	"Bouvet Island": "BV",
	Brazil: "BR",
	"British Indian Ocean Territory": "IO",
	"Brunei Darussalam": "BN",
	Bulgaria: "BG",
	"Burkina Faso": "BF",
	Burundi: "BI",
	Cambodia: "KH",
	Cameroon: "CM",
	Canada: "CA",
	"Cape Verde": "CV",
	"Cayman Islands": "KY",
	"Central African Republic": "CF",
	Chad: "TD",
	Chile: "CL",
	China: "CN",
	"Christmas Island": "CX",
	"Cocos (Keeling) Islands": "CC",
	Colombia: "CO",
	Comoros: "KM",
	Congo: "CG",
	"Congo, the Democratic Republic of the": "CD",
	"Cook Islands": "CK",
	"Costa Rica": "CR",
	"Cote DIvoire": "CI",
	Croatia: "HR",
	Cuba: "CU",
	Curaçao: "CW",
	Cyprus: "CY",
	"Czech Republic": "CZ",
	Denmark: "DK",
	Djibouti: "DJ",
	Dominica: "DM",
	"Dominican Republic": "DO",
	Ecuador: "EC",
	Egypt: "EG",
	"El Salvador": "SV",
	"Equatorial Guinea": "GQ",
	Eritrea: "ER",
	Estonia: "EE",
	Ethiopia: "ET",
	"Falkland Islands (Malvinas)": "FK",
	"Faroe Islands": "FO",
	Fiji: "FJ",
	Finland: "FI",
	France: "FR",
	"French Guiana": "GF",
	"French Polynesia": "PF",
	"French Southern Territories": "TF",
	Gabon: "GA",
	Gambia: "GM",
	Georgia: "GE",
	Germany: "DE",
	Ghana: "GH",
	Gibraltar: "GI",
	Greece: "GR",
	Greenland: "GL",
	Grenada: "GD",
	Guadeloupe: "GP",
	Guam: "GU",
	Guatemala: "GT",
	Guernsey: "GG",
	Guinea: "GN",
	"Guinea-Bissau": "GW",
	Guyana: "GY",
	Haiti: "HT",
	"Heard Island and Mcdonald Islands": "HM",
	"Holy See (Vatican City State)": "VA",
	Honduras: "HN",
	"Hong Kong": "HK",
	Hungary: "HU",
	Iceland: "IS",
	India: "IN",
	Indonesia: "ID",
	"Iran, Islamic Republic of": "IR",
	Iraq: "IQ",
	Ireland: "IE",
	"Isle of Man": "IM",
	Israel: "IL",
	Italy: "IT",
	Jamaica: "JM",
	Japan: "JP",
	Jersey: "JE",
	Jordan: "JO",
	Kazakhstan: "KZ",
	Kenya: "KE",
	Kiribati: "KI",
	"Korea, Democratic People's Republic of": "KP",
	"Korea, Republic of": "KR",
	Kuwait: "KW",
	Kyrgyzstan: "KG",
	"Lao People's Democratic Republic": "LA",
	Latvia: "LV",
	Lebanon: "LB",
	Lesotho: "LS",
	Liberia: "LR",
	Libya: "LY",
	Liechtenstein: "LI",
	Lithuania: "LT",
	Luxembourg: "LU",
	Macao: "MO",
	"Macedonia, the Former Yugoslav Republic of": "MK",
	Madagascar: "MG",
	Malawi: "MW",
	Malaysia: "MY",
	Maldives: "MV",
	Mali: "ML",
	Malta: "MT",
	"Marshall Islands": "MH",
	Martinique: "MQ",
	Mauritania: "MR",
	Mauritius: "MU",
	Mayotte: "YT",
	Mexico: "MX",
	"Micronesia, Federated States of": "FM",
	"Moldova, Republic of": "MD",
	Monaco: "MC",
	Mongolia: "MN",
	Montenegro: "ME",
	Montserrat: "MS",
	Morocco: "MA",
	Mozambique: "MZ",
	Myanmar: "MM",
	Namibia: "NA",
	Nauru: "NR",
	Nepal: "NP",
	Netherlands: "NL",
	"New Caledonia": "NC",
	"New Zealand": "NZ",
	Nicaragua: "NI",
	Niger: "NE",
	Nigeria: "NG",
	Niue: "NU",
	"Norfolk Island": "NF",
	"Northern Mariana Islands": "MP",
	Norway: "NO",
	Oman: "OM",
	Pakistan: "PK",
	Palau: "PW",
	"Palestine, State of": "PS",
	Panama: "PA",
	"Papua New Guinea": "PG",
	Paraguay: "PY",
	Peru: "PE",
	Philippines: "PH",
	Pitcairn: "PN",
	Poland: "PL",
	Portugal: "PT",
	"Puerto Rico": "PR",
	Qatar: "QA",
	Reunion: "RE",
	Romania: "RO",
	"Russian Federation": "RU",
	Rwanda: "RW",
	"Saint Barthélemy": "BL",
	"Saint Helena, Ascension and Tristan da Cunha": "SH",
	"Saint Kitts and Nevis": "KN",
	"Saint Lucia": "LC",
	"Saint Martin (French part)": "MF",
	"Saint Pierre and Miquelon": "PM",
	"Saint Vincent and the Grenadines": "VC",
	Samoa: "WS",
	"San Marino": "SM",
	"Sao Tome and Principe": "ST",
	"Saudi Arabia": "SA",
	Senegal: "SN",
	Serbia: "RS",
	Seychelles: "SC",
	"Sierra Leone": "SL",
	Singapore: "SG",
	"Sint Maarten (Dutch part)": "SX",
	Slovakia: "SK",
	Slovenia: "SI",
	"Solomon Islands": "SB",
	Somalia: "SO",
	"South Africa": "ZA",
	"South Georgia and the South Sandwich Islands": "GS",
	"South Sudan": "SS",
	Spain: "ES",
	"Sri Lanka": "LK",
	Sudan: "SD",
	Suriname: "SR",
	"Svalbard and Jan Mayen": "SJ",
	Swaziland: "SZ",
	Sweden: "SE",
	Switzerland: "CH",
	"Syrian Arab Republic": "SY",
	"Taiwan (Province of China)": "TW",
	Tajikistan: "TJ",
	"Tanzania, United Republic of": "TZ",
	Thailand: "TH",
	"Timor-Leste": "TL",
	Togo: "TG",
	Tokelau: "TK",
	Tonga: "TO",
	"Trinidad and Tobago": "TT",
	Tunisia: "TN",
	Turkey: "TR",
	Turkmenistan: "TM",
	"Turks and Caicos Islands": "TC",
	Tuvalu: "TV",
	Uganda: "UG",
	Ukraine: "UA",
	"United Arab Emirates": "AE",
	"United Kingdom": "GB",
	"United States": "US",
	"United States Minor Outlying Islands": "UM",
	Uruguay: "UY",
	Uzbekistan: "UZ",
	Vanuatu: "VU",
	Venezuela: "VE",
	"Viet Nam": "VN",
	"Virgin Islands (British)": "VG",
	"Virgin Islands (U.S.)": "VI",
	"Wallis and Futuna": "WF",
	"Western Sahara": "EH",
	Yemen: "YE",
	Zambia: "ZM",
	Zimbabwe: "ZW",
	"Åland Islands": "AX",
} as const

export type CountryISO2 = (typeof CountryISO2)[keyof typeof CountryISO2]

/**
 * ISO 3166-1 alpha-3 country codes to country names.
 *
 * @internal
 * @title Country ISO 3166-1 Alpha-3 Code
 */
export const Alpha3ToCountryRecord = {
	AFG: "Afghanistan",
	ALB: "Albania",
	DZA: "Algeria",
	ASM: "American Samoa",
	AND: "Andorra",
	AGO: "Angola",
	AIA: "Anguilla",
	ATA: "Antarctica",
	ATG: "Antigua and Barbuda",
	ARG: "Argentina",
	ARM: "Armenia",
	ABW: "Aruba",
	AUS: "Australia",
	AUT: "Austria",
	AZE: "Azerbaijan",
	BHS: "Bahamas",
	BHR: "Bahrain",
	BGD: "Bangladesh",
	BRB: "Barbados",
	BLR: "Belarus",
	BEL: "Belgium",
	BLZ: "Belize",
	BEN: "Benin",
	BMU: "Bermuda",
	BTN: "Bhutan",
	BOL: "Bolivia",
	BES: "Bonaire, Sint Eustatius and Saba",
	BIH: "Bosnia and Herzegovina",
	BWA: "Botswana",
	BVT: "Bouvet Island",
	BRA: "Brazil",
	IOT: "British Indian Ocean Territory",
	BRN: "Brunei Darussalam",
	BGR: "Bulgaria",
	BFA: "Burkina Faso",
	BDI: "Burundi",
	KHM: "Cambodia",
	CMR: "Cameroon",
	CAN: "Canada",
	CPV: "Cape Verde",
	CYM: "Cayman Islands",
	CAF: "Central African Republic",
	TCD: "Chad",
	CHL: "Chile",
	CHN: "China",
	CXR: "Christmas Island",
	CCK: "Cocos (Keeling) Islands",
	COL: "Colombia",
	COM: "Comoros",
	COG: "Congo",
	COD: "Congo, the Democratic Republic of the",
	COK: "Cook Islands",
	CRI: "Costa Rica",
	CIV: "Cote DIvoire",
	HRV: "Croatia",
	CUB: "Cuba",
	CUW: "Curaçao",
	CYP: "Cyprus",
	CZE: "Czech Republic",
	DNK: "Denmark",
	DJI: "Djibouti",
	DMA: "Dominica",
	DOM: "Dominican Republic",
	ECU: "Ecuador",
	EGY: "Egypt",
	SLV: "El Salvador",
	GNQ: "Equatorial Guinea",
	ERI: "Eritrea",
	EST: "Estonia",
	ETH: "Ethiopia",
	FLK: "Falkland Islands (Malvinas)",
	FRO: "Faroe Islands",
	FJI: "Fiji",
	FIN: "Finland",
	FRA: "France",
	GUF: "French Guiana",
	PYF: "French Polynesia",
	ATF: "French Southern Territories",
	GAB: "Gabon",
	GMB: "Gambia",
	GEO: "Georgia",
	DEU: "Germany",
	GHA: "Ghana",
	GIB: "Gibraltar",
	GRC: "Greece",
	GRL: "Greenland",
	GRD: "Grenada",
	GLP: "Guadeloupe",
	GUM: "Guam",
	GTM: "Guatemala",
	GGY: "Guernsey",
	GIN: "Guinea",
	GNB: "Guinea-Bissau",
	GUY: "Guyana",
	HTI: "Haiti",
	HMD: "Heard Island and Mcdonald Islands",
	VAT: "Holy See (Vatican City State)",
	HND: "Honduras",
	HKG: "Hong Kong",
	HUN: "Hungary",
	ISL: "Iceland",
	IND: "India",
	IDN: "Indonesia",
	IRN: "Iran, Islamic Republic of",
	IRQ: "Iraq",
	IRL: "Ireland",
	IMN: "Isle of Man",
	ISR: "Israel",
	ITA: "Italy",
	JAM: "Jamaica",
	JPN: "Japan",
	JEY: "Jersey",
	JOR: "Jordan",
	KAZ: "Kazakhstan",
	KEN: "Kenya",
	KIR: "Kiribati",
	PRK: "Korea, Democratic People's Republic of",
	KOR: "Korea, Republic of",
	KWT: "Kuwait",
	KGZ: "Kyrgyzstan",
	LAO: "Lao People's Democratic Republic",
	LVA: "Latvia",
	LBN: "Lebanon",
	LSO: "Lesotho",
	LBR: "Liberia",
	LBY: "Libya",
	LIE: "Liechtenstein",
	LTU: "Lithuania",
	LUX: "Luxembourg",
	MAC: "Macao",
	MKD: "Macedonia, the Former Yugoslav Republic of",
	MDG: "Madagascar",
	MWI: "Malawi",
	MYS: "Malaysia",
	MDV: "Maldives",
	MLI: "Mali",
	MLT: "Malta",
	MHL: "Marshall Islands",
	MTQ: "Martinique",
	MRT: "Mauritania",
	MUS: "Mauritius",
	MYT: "Mayotte",
	MEX: "Mexico",
	FSM: "Micronesia, Federated States of",
	MDA: "Moldova, Republic of",
	MCO: "Monaco",
	MNG: "Mongolia",
	MNE: "Montenegro",
	MSR: "Montserrat",
	MAR: "Morocco",
	MOZ: "Mozambique",
	MMR: "Myanmar",
	NAM: "Namibia",
	NRU: "Nauru",
	NPL: "Nepal",
	NLD: "Netherlands",
	NCL: "New Caledonia",
	NZL: "New Zealand",
	NIC: "Nicaragua",
	NER: "Niger",
	NGA: "Nigeria",
	NIU: "Niue",
	NFK: "Norfolk Island",
	MNP: "Northern Mariana Islands",
	NOR: "Norway",
	OMN: "Oman",
	PAK: "Pakistan",
	PLW: "Palau",
	PSE: "Palestine, State of",
	PAN: "Panama",
	PNG: "Papua New Guinea",
	PRY: "Paraguay",
	PER: "Peru",
	PHL: "Philippines",
	PCN: "Pitcairn",
	POL: "Poland",
	PRT: "Portugal",
	PRI: "Puerto Rico",
	QAT: "Qatar",
	REU: "Reunion",
	ROM: "Romania",
	RUS: "Russian Federation",
	RWA: "Rwanda",
	BLM: "Saint Barthélemy",
	SHN: "Saint Helena, Ascension and Tristan da Cunha",
	KNA: "Saint Kitts and Nevis",
	LCA: "Saint Lucia",
	MAF: "Saint Martin (French part)",
	SPM: "Saint Pierre and Miquelon",
	VCT: "Saint Vincent and the Grenadines",
	WSM: "Samoa",
	SMR: "San Marino",
	STP: "Sao Tome and Principe",
	SAU: "Saudi Arabia",
	SEN: "Senegal",
	SRB: "Serbia",
	SYC: "Seychelles",
	SLE: "Sierra Leone",
	SGP: "Singapore",
	SXM: "Sint Maarten (Dutch part)",
	SVK: "Slovakia",
	SVN: "Slovenia",
	SLB: "Solomon Islands",
	SOM: "Somalia",
	ZAF: "South Africa",
	SGS: "South Georgia and the South Sandwich Islands",
	SSD: "South Sudan",
	ESP: "Spain",
	LKA: "Sri Lanka",
	SDN: "Sudan",
	SUR: "Suriname",
	SJM: "Svalbard and Jan Mayen",
	SWZ: "Swaziland",
	SWE: "Sweden",
	CHE: "Switzerland",
	SYR: "Syrian Arab Republic",
	TWN: "Taiwan (Province of China)",
	TJK: "Tajikistan",
	TZA: "Tanzania, United Republic of",
	THA: "Thailand",
	TLS: "Timor-Leste",
	TGO: "Togo",
	TKL: "Tokelau",
	TON: "Tonga",
	TTO: "Trinidad and Tobago",
	TUN: "Tunisia",
	TUR: "Turkey",
	TKM: "Turkmenistan",
	TCA: "Turks and Caicos Islands",
	TUV: "Tuvalu",
	UGA: "Uganda",
	UKR: "Ukraine",
	ARE: "United Arab Emirates",
	GBR: "United Kingdom",
	USA: "United States",
	UMI: "United States Minor Outlying Islands",
	URY: "Uruguay",
	UZB: "Uzbekistan",
	VUT: "Vanuatu",
	VEN: "Venezuela",
	VNM: "Viet Nam",
	VGB: "Virgin Islands (British)",
	VIR: "Virgin Islands (U.S.)",
	WLF: "Wallis and Futuna",
	ESH: "Western Sahara",
	YEM: "Yemen",
	ZMB: "Zambia",
	ZWE: "Zimbabwe",
	ALA: "Åland Islands",
} as const satisfies Record<string, CountryName>

/**
 * ISO 3166-1 alpha-3 country code.
 *
 * @category Geographic
 * @category Country
 * @title Country ISO 3166-1 Alpha-3 Code
 * @public
 */
export type CountryISO3 = keyof typeof Alpha3ToCountryRecord
