/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   Render a weights package's two rights files from its {@link WeightsRightsRecord}: `LICENSE.md`, the terms this
 *   repository grants, and `PROVENANCE.json`, where the artifacts came from and what the repository does not know
 *   about them.
 *
 *   They are two files because they answer to different parties. `LICENSE.md` is our own grant, and its text is the
 *   same for every package because the expression is. `PROVENANCE.json` is a record about other people's data, it
 *   differs per package, and a consumer's build should be able to read it without parsing prose. Folding the second
 *   into the first produced the state the inventory found: one `data_attribution` list, in one package, covering
 *   artifacts that ship in others.
 *
 *   Neither file asserts clearance. `PROVENANCE.json` records what the model card records and marks the rest
 *   unresolved, and `LICENSE.md` says in as many words that the commercial grant does not reach third-party inputs.
 */

import { stringifyJSON } from "@mailwoman/core/json"

import type { WeightsRightsRecord } from "#weights/rights/record"

/**
 * The name of the generated obligations file inside a weights workspace.
 */
export const LICENSE_FILE = "LICENSE.md"

/**
 * The name of the generated machine-readable provenance file inside a weights workspace.
 */
export const PROVENANCE_FILE = "PROVENANCE.json"

/**
 * The provenance record as it is written to disk. Field names are snake_case to match `model-card.json`, which is the
 * file a reader of this one will open next.
 */
export interface ProvenanceDocument {
	$comment: string
	package: string
	package_version: string
	license: string
	model_card_version: string | null
	version_series: string
	version_series_meaning: string
	base_weights: string | null
	/**
	 * What this package inherits by decoding through another package's graph. `null` for a graph package.
	 */
	inherited_lineage: {
		package: string
		package_version: string
		model_card_version: string | null
		chain: string[]
		note: string
		attribution: Array<{ text: string; license_named: string | null }>
		unresolved: string | null
	} | null
	artifacts: Array<{ path: string; md5: string | null; digest: string }>
	training_attribution: {
		status: "recorded" | "none-recorded-in-this-package"
		entries: Array<{ text: string; license_named: string | null }>
	}
	attribution_recorded_in_another_package: Array<{ artifact: string; recorded_in: string; text: string }>
	corpus_version: string | null
	tokenizer_version: string | null
	unresolved: string[]
}

const GENERATED_BY =
	"Generated by `mwops release write-rights-files` from package.json and model-card.json. Edit the generator or those files, never this one."

const SERIES_MEANING: Readonly<Record<string, string>> = {
	model:
		"This package ships a model graph, and model_card_version names the trained model. It is a different series from package_version, which moves in lockstep across every mailwoman workspace on every release. `mwops release verify-metadata` keys the score ledger and release documentation off this number.",
	overlay:
		"This package is a data-only overlay, and model_card_version names this overlay's own artifacts. The model graph its rows decode through is the one base_weights names, at that package's own model_card_version. Neither number is package_version, which moves in lockstep across every mailwoman workspace on every release.",
}

/**
 * The questions this record leaves open, each phrased as the question rather than as a finding. A reader has to be able
 * to tell a package with no recorded training inputs from a package trained on nothing, and an artifact with no
 * recorded digest from an artifact whose digest was checked.
 */
function unresolvedQuestions(record: WeightsRightsRecord): string[] {
	const questions: string[] = []
	const undigested = record.artifacts.filter((artifact) => artifact.digest === "unrecorded")

	if (undigested.length) {
		questions.push(
			`No digest is recorded for ${undigested.length} of ${record.artifacts.length} declared artifacts: ${undigested
				.map((artifact) => artifact.path)
				.join(", ")}. An unrecorded digest is not a verified one.`
		)
	}

	if (!record.attribution.length) {
		questions.push(
			record.inherited?.attribution.length
				? `This package's model card records no training attribution of its own. It ships ${record.artifacts.length} artifacts and no model graph, so its own inputs are unattributed here while the ${record.inherited.attribution.length} entries under inherited_lineage describe ${record.inherited.package}'s graph.`
				: "This package's model card records no training attribution. That states what the card holds, not that the artifacts have no attributable inputs."
		)
	}

	if (record.inherited?.unresolved) {
		questions.push(`The inherited lineage could not be resolved: ${record.inherited.unresolved}`)
	}

	for (const entry of record.attribution) {
		if (entry.licenseNamed) continue

		questions.push(`One attribution entry names no license: ${entry.text}`)
	}

	for (const foreign of record.foreignAttribution) {
		questions.push(
			`${foreign.artifact} ships here, and the entry attributing it sits in ${foreign.recordedIn}'s model card. A consumer installing this package alone receives the artifact without the attribution.`
		)
	}

	questions.push(
		"Which records trained the model this package ships or inherits is unresolved. No frozen per-release training manifest exists, and the corpus named above is the recipe's corpus rather than a record of what reached the model."
	)

	return questions
}

/**
 * The provenance document for one package.
 */
export function renderProvenance(record: WeightsRightsRecord): ProvenanceDocument {
	return {
		$comment: GENERATED_BY,
		package: record.packageName,
		package_version: record.packageVersion,
		license: record.license,
		model_card_version: record.modelCardVersion,
		version_series: record.versionSeries,
		version_series_meaning: SERIES_MEANING[record.versionSeries]!,
		base_weights: record.baseWeights,
		inherited_lineage: record.inherited
			? {
					package: record.inherited.package,
					package_version: record.inherited.packageVersion,
					model_card_version: record.inherited.modelCardVersion,
					chain: record.inherited.chain,
					note: `These entries are ${record.inherited.package}'s record of what its model graph was trained on. This package ships no graph and contributed none of these rows. Read them as the base's lineage rather than as a claim about this package's own artifacts, which are listed under artifacts and attributed under training_attribution.`,
					attribution: record.inherited.attribution.map((entry) => ({
						text: entry.text,
						license_named: entry.licenseNamed,
					})),
					unresolved: record.inherited.unresolved,
				}
			: null,
		artifacts: record.artifacts.map((artifact) => ({
			path: artifact.path,
			md5: artifact.md5,
			digest: artifact.digest,
		})),
		training_attribution: {
			status: record.attribution.length ? "recorded" : "none-recorded-in-this-package",
			entries: record.attribution.map((entry) => ({ text: entry.text, license_named: entry.licenseNamed })),
		},
		attribution_recorded_in_another_package: record.foreignAttribution.map((foreign) => ({
			artifact: foreign.artifact,
			recorded_in: foreign.recordedIn,
			text: foreign.text,
		})),
		corpus_version: record.corpusVersion,
		tokenizer_version: record.tokenizerVersion,
		unresolved: unresolvedQuestions(record),
	}
}

/**
 * Whether a committed provenance document equals the one this record renders.
 *
 * Parsed JSON is compared rather than text, so the repository formatter may lay the file out as it likes — the same
 * reason `license-register` compares the well-known key file that way.
 */
export function provenanceMatches(committed: unknown, record: WeightsRightsRecord): boolean {
	return stringifyJSON(committed) === stringifyJSON(renderProvenance(record))
}

/**
 * The obligations file for one package.
 *
 * Every published mailwoman package carries the same expression, so this text does not vary with the package beyond its
 * name and the pointer to its own provenance record. It exists per package because npm ships per package: a consumer
 * who installs one weights overlay and reads its tarball finds the terms there rather than in a repository they were
 * never sent to.
 */
export function renderLicenseFile(record: WeightsRightsRecord): string {
	return `# License — ${record.packageName}

${GENERATED_BY}

## The terms Sister Software grants

This package is distributed under \`${record.license}\`.

Under the AGPL-3.0-only branch, three obligations attach: keep the copyright notices, license a
modified copy under the same terms, and offer corresponding source to people who use a modified copy
over a network (section 13). Under a commercial agreement, the source offer and the share-alike
condition do not apply to the code and model artifacts Sister Software authors.

- Open-source terms: https://github.com/sister-software/mailwoman/blob/main/LICENSE.md
- Commercial terms, as executed at checkout: https://mailwoman.ai/license/terms/commercial-2026-10
- Commercial terms, as a reference template that does not itself execute:
  https://github.com/sister-software/mailwoman/blob/main/COMMERCIAL-LICENSE.md

## What the commercial grant does not cover

Section 2 of the commercial agreement limits the grant to the code and model artifacts Sister
Software authors. It does not extend to third-party components distributed with Mailwoman, which
stay under their own licenses. Any attribution or share-alike obligation attaching to those
components continues to apply and is not waived or relicensed by a commercial agreement.

## Where the sources are recorded

\`${PROVENANCE_FILE}\` in this package records, per artifact, what the repository holds about its
inputs and which questions it cannot answer. Read it as the record it is: a package with no recorded
training attribution is a package whose model card records none, which is not the same as a package
with no attributable inputs. No artifact in this package is recorded as cleared for any particular
use.

\`THIRD_PARTY_NOTICES.md\` in the repository lists the components Mailwoman distributes and the terms
each one carries. Reference data an operator downloads separately carries the terms of whoever
published it, and nothing here states what those are.
`
}
