/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   Root Vitest config for tests across all workspaces.
 *
 *   Workspace aliases point `@mailwoman/*` imports to source `.ts` files. They come from each
 *   workspace's `exports` map, so the aliases stay in sync. The only manual alias is for
 *   `onnxruntime-web`, which is not a workspace.
 */

/// <reference types="vitest/config" />

import { readLocalJSONFile } from "@mailwoman/core/fs/readers"
import { resolveModulePath } from "@mailwoman/core/module/resolvers"
import { readWorkspaceDirectories } from "@mailwoman/core/workspaces"
import { resolvePath } from "path-ts"
import type { Alias } from "vite"
import { defineConfig } from "vite"

const here = import.meta.dirname

const escapeRegExp = (input: string): string => input.replaceAll(/[.*+?^${}()|[\]\\]/g, "\\$&")

/**
 * Read a workspace manifest.
 *
 * Read a manifest without relying on aliases generated by this config.
 * Invalid manifests should stop the test run.
 */
async function readManifest<T>(path: string): Promise<T> {
	// oxlint-disable-next-line no-restricted-properties -- see above.
	return await readLocalJSONFile<T>(path)
}

/**
 * Build source aliases from each workspace's `exports` map.
 *
 * This avoids keeping a separate alias list that can get out of sync with package exports.
 * It also handles file and directory subpaths consistently.
 *
 * Exact subpaths come before wildcards, longest first, because Vite uses the first match.
 */
async function workspaceAliases(): Promise<Alias[]> {
	const aliases: Array<Alias & { specificity: number; wildcard: boolean }> = []

	for (const workspace of await readWorkspaceDirectories(here)) {
		const manifest = await readManifest<{
			name?: string
			exports?: Record<string, string | Record<string, string>>
		}>(resolvePath(here, workspace, "package.json"))

		if (!manifest.name || !manifest.exports) continue

		for (const [subpath, target] of Object.entries(manifest.exports)) {
			// Prefer the `node` source entry.
			// A plain-string export uses its own value.
			const file = typeof target === "string" ? target : (target.node ?? target.default)

			if (!file) continue

			const specifier = manifest.name + (subpath === "." ? "" : subpath.slice(1))
			const wildcard = specifier.includes("*")

			aliases.push({
				find: new RegExp(`^${specifier.split("*").map(escapeRegExp).join("(.+)")}$`),
				replacement: resolvePath(here, workspace, file).replace("*", "$1"),
				specificity: specifier.length,
				wildcard,
			})
		}
	}

	return aliases
		.toSorted((a, b) => Number(a.wildcard) - Number(b.wildcard) || b.specificity - a.specificity)
		.map(({ find, replacement }) => ({ find, replacement }))
}

export default defineConfig({
	resolve: {
		alias: [
			...(await workspaceAliases()),
			// The `/webgpu` bundle uses browser-only loading that fails under Node.
			// Resolve it to the package's Node build for tests.
			// A production import keeps its own target.
			//
			// Resolve the package's root export so upgrades can move or rename its Node build.
			// There is no exported `./dist/*` path, so the root specifier is required.
			{
				find: /^onnxruntime-web\/webgpu$/,
				replacement: resolveModulePath("onnxruntime-web"),
			},
		],
	},
	test: {
		// Share each worker's module graph to avoid reloading the workspace for every test file.
		// The former isolation issue with libpostal no longer reproduces.
		// The tests it affected import core first.
		//
		// Shared modules are cached, so mocks may not apply if a module was loaded earlier.
		// Call `vi.resetModules()` before importing the module under test when mocking shared modules.
		isolate: false,
		testTimeout: 15_000,
		coverage: {
			// Keep the coverage report even when tests fail, so failures don't leave an empty report.
			reportOnFailure: true,
		},
		exclude: [
			"**/node_modules/**",
			"**/dist/**",
			"**/out/**",
			"**/examples/**",
			"**/cypress/**",
			"**/.{idea,git,cache,output,temp}/**",
			"**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*",
			// These Playwright tests use a different runner and must not be collected by Vitest.
			"**/docs/test/browser/**",
			// Exclude Playwright tests in packages too.
			"**/packages/*/test/browser/**",
			"**/packages/*/test/e2e/**",
			"**/docs/test/build/**",
			"**/docs/test/e2e/**",
			// A worktree holds a full repository copy.
			// This run has already collected those tests.
			"**/.claude/worktrees/**",
			// Manual worktrees may run tests against this checkout's source.
			"**/.worktrees/**",
			// Python virtualenvs can contain unrelated JavaScript tests that Vitest may collect.
			"**/.venv/**",
			// A scratchpad holds files copied or generated for a session.
			"**/scratchpad/**",
			// React tests require Vitest browser mode and run separately in CI.
			"**/react/**/*.test.{ts,tsx}",
			// License-worker tests require the Workers pool and run separately in CI.
			"**/license-worker/**/*.test.ts",
		],
	},
})
