# Cloudflare Wrangler Configuration

name = "mailwoman-tiles"
main = "./out/_worker.js"
compatibility_date = "2024-06-03"
minify = false

[[r2_buckets]]
binding = "NEXUS_ASSETS_BUCKET"
bucket_name = "nexus-assets"

[vars]
PMTILES_PATH = "tiles"

routes = [{ pattern = "tiles.sister.software", custom_domain = true }]

[alias]
"@mailwoman/cartographer" = "../cartographer/index.ts"
"@mailwoman/cartographer/tiles/coords" = "../cartographer/tiles/coords.ts"
"@mailwoman/spatial" = "../spatial/index.ts"
"@mailwoman/tiger" = "../tiger/index.ts"
