/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   The address-system registry the trainer reads: one id per distinct component order in codex's layouts,
 *   and the system of every country in each script it has a layout for.
 *
 *   A trained checkpoint's address-system head has one output per id, so an id never changes meaning.
 *   A key that leaves the layouts keeps its id, and a new key takes the next id.
 *   Regenerate with: mailwoman dev generate address-systems
 */

import { addressSystemMembers, type AddressScript } from "@mailwoman/codex/address/layouts"
import { readLocalJSONFile } from "@mailwoman/core/fs/readers"
import { writeLocalJSONFile } from "@mailwoman/core/fs/writers"
import { repoRootPath } from "@mailwoman/core/paths"

/**
 * The committed registry's path, inside the trainer's package data.
 */
export const ADDRESS_SYSTEMS_PATH = repoRootPath("corpus-python", "src", "mailwoman_train", "address_systems.json")

/**
 * One address system: its stable id and the component order that defines it.
 */
export interface AddressSystemEntry {
	id: number
	key: string
}

/**
 * The address-system registry as committed.
 */
export interface AddressSystemRegistry {
	$comment: string
	systems: AddressSystemEntry[]
	members: Array<{ country: string; script: AddressScript; system: number }>
}

const COMMENT =
	"Generated by `mailwoman dev generate address-systems` from @mailwoman/codex layouts. " +
	"Ids are append-only: a checkpoint's address-system head indexes them."

/**
 * Derives the registry from codex's layouts, keeping every id `previous` assigned.
 */
export function deriveAddressSystemRegistry(previous: AddressSystemRegistry | null): AddressSystemRegistry {
	const systems = [...(previous?.systems ?? [])]
	const idByKey = new Map(systems.map((entry) => [entry.key, entry.id]))
	const members = addressSystemMembers()

	for (const member of members) {
		if (idByKey.has(member.key)) continue

		const id = systems.length

		systems.push({ id, key: member.key })
		idByKey.set(member.key, id)
	}

	return {
		$comment: COMMENT,
		systems,
		members: members.map(({ country, script, key }) => ({ country, script, system: idByKey.get(key)! })),
	}
}

/**
 * Reads the committed registry, or null when it has not been generated.
 */
export async function readAddressSystemRegistry(path = ADDRESS_SYSTEMS_PATH): Promise<AddressSystemRegistry | null> {
	return readLocalJSONFile<AddressSystemRegistry>(path).catch((error: NodeJS.ErrnoException) => {
		if (error.code === "ENOENT") return null

		throw error
	})
}

/**
 * Regenerates the committed registry and returns its counts.
 */
export async function generateAddressSystems(
	path = ADDRESS_SYSTEMS_PATH,
	report?: (message: string) => void
): Promise<{ outPath: string; systems: number; members: number }> {
	const registry = deriveAddressSystemRegistry(await readAddressSystemRegistry(path))

	await writeLocalJSONFile(registry, path)
	report?.(`wrote ${path} (${registry.systems.length} systems, ${registry.members.length} members)`)

	return { outPath: path.toString(), systems: registry.systems.length, members: registry.members.length }
}
