/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 * @file The gold-set adjudication packet — the org-name-grain over-merged clusters, with every matcher-visible field,
 *   formatted for human review.
 */

import { writeLocalTextFile } from "@mailwoman/core/fs/writers"
import { isPresent } from "@mailwoman/core/objects"

import type { ResolvedEntity, SourceRecord } from "#index"
import type { MessyRow } from "#tools/nppes/sample"
import type { TruthLabel } from "#tools/nppes/truth-grains"

/**
 * Everything the packet reads.
 */
export interface OvermergePacketInput {
	/**
	 * The clusters to inspect — the SHIPPED config's, since the packet exists to adjudicate what production produces.
	 */
	entities: readonly ResolvedEntity[]
	/**
	 * The source rows, for the fields that ride as attributes rather than on the record face.
	 */
	rows: readonly MessyRow[]
	recordCount: number
	maxNpis: number
	/**
	 * The state the sample was drawn from, so the packet's own header names the run an adjudicator is holding.
	 */
	state: string
	orgNameLabel: TruthLabel
}

/**
 * Write the packet and return the number of over-merged clusters it holds.
 *
 * A cluster qualifies when its members carry more than one org-name label — the matcher fused records the org-name
 * truth says belong to different entities. Per-pair human adjudication is the only instrument that separates model
 * error from yardstick error once the residual is near the measured irreducible ceiling.
 */
export async function writeOvermergePacket(path: string, input: OvermergePacketInput): Promise<number> {
	const { entities, rows, recordCount, maxNpis, state, orgNameLabel } = input
	const rowByID = new Map(rows.map((r) => [r.npi, r]))

	const out: string[] = [
		"# #625 gold-set adjudication packet — org-name-grain over-merged clusters (GBT, shipped config)",
		"",
		`${state} --max-npis ${maxNpis} · ${recordCount} records · generated by \`registry scorer-eval nppes-benchmark --dump-overmerges\``,
		"",
		"For each cluster: the matcher fused records that the org-name truth says belong to DIFFERENT entities.",
		"Adjudicate each: **[same]** one real-world entity (yardstick error — the truth under-collapsed) or",
		"**[distinct]** genuinely different co-located providers (model over-merge). Mark inline and return.",
		"",
	]

	let n = 0

	entities.forEach((e) => {
		const byLabel = new Map<string, SourceRecord[]>()

		for (const rec of e.records) {
			const lbl = orgNameLabel(rec)
			const list = byLabel.get(lbl) ?? []
			list.push(rec)
			byLabel.set(lbl, list)
		}

		if (byLabel.size <= 1) return

		n++
		out.push(`## Cluster ${n} — ${e.records.length} records, ${byLabel.size} org-name entities  → verdict: [ ]`)

		for (const [lbl, members] of byLabel) {
			out.push(`- **entity ${lbl}**`)

			for (const rec of members) {
				const src = rowByID.get(rec.id)

				out.push(
					`  - npi=${rec.id} · name="${[rec.name?.given, rec.name?.family].filter(isPresent).join(" ")}" · org="${rec.organization?.canonical ?? ""}" · addr="${rec.address?.raw ?? ""}" · auth="${src?.auth ?? ""}" · taxonomy="${src?.taxonomy ?? ""}"`
				)
			}
		}

		out.push("")
	})

	await writeLocalTextFile(out.join("\n"), path)

	return n
}
