/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 * @file Writes the over-merged NPPES clusters with every matcher-visible field for human adjudication.
 */

import { writeLocalTextFile } from "@mailwoman/core/fs/writers"
import { formatPersonName } from "@mailwoman/record/name"
import type { PathBuilderLike } from "path-ts"

import type { ResolvedEntity, SourceRecord } from "#index"
import type { MessyRow } from "#tools/nppes/sample"
import type { TruthLabel } from "#tools/nppes/truth-grains"

/**
 * The inputs to {@link writeOvermergePacket}.
 */
export interface OvermergePacketInput {
	/**
	 * The clusters to inspect.
	 * Callers pass the clusters from the shipped matcher config.
	 */
	entities: readonly ResolvedEntity[]
	/**
	 * The source rows.
	 *
	 * The packet reads the authorized official and taxonomy from them.
	 */
	rows: readonly MessyRow[]
	recordCount: number
	maxNpis: number
	/**
	 * The state that the sample was drawn from.
	 * The packet header prints it.
	 */
	state: string
	orgNameLabel: TruthLabel
}

/**
 * Writes the adjudication packet and returns the number of over-merged clusters in it.
 *
 * A cluster is over-merged when its members carry more than one org-name truth label.
 * A reviewer marks each cluster as one real entity or as distinct providers,
 * which separates model error from truth-label error.
 */
export async function writeOvermergePacket(path: PathBuilderLike, input: OvermergePacketInput): Promise<number> {
	const { entities, rows, recordCount, maxNpis, state, orgNameLabel } = input
	const rowByID = new Map(rows.map((r) => [r.npi, r]))

	const out: string[] = [
		"# #625 gold-set adjudication packet — org-name-grain over-merged clusters (GBT, shipped config)",
		"",
		`${state} --max-npis ${maxNpis} · ${recordCount} records · generated by \`registry scorer-eval nppes-benchmark --dump-overmerges\``,
		"",
		"For each cluster: the matcher fused records that the org-name truth says belong to DIFFERENT entities.",
		"Adjudicate each: **[same]** one real-world entity (yardstick error — the truth under-collapsed) or",
		"**[distinct]** genuinely different co-located providers (model over-merge). Mark inline and return.",
		"",
	]

	let n = 0

	entities.forEach((e) => {
		const byLabel = new Map<string, SourceRecord[]>()

		for (const rec of e.records) {
			const lbl = orgNameLabel(rec)
			const list = byLabel.get(lbl) ?? []
			list.push(rec)
			byLabel.set(lbl, list)
		}

		if (byLabel.size <= 1) return

		n++
		out.push(`## Cluster ${n} — ${e.records.length} records, ${byLabel.size} org-name entities  → verdict: [ ]`)

		for (const [lbl, members] of byLabel) {
			out.push(`- **entity ${lbl}**`)

			for (const rec of members) {
				const src = rowByID.get(rec.id)

				out.push(
					`  - npi=${rec.id} · name="${formatPersonName(rec.name, "short")}" · org="${rec.organization?.canonical ?? ""}" · addr="${rec.address?.raw ?? ""}" · auth="${src?.auth ?? ""}" · taxonomy="${src?.taxonomy ?? ""}"`
				)
			}
		}

		out.push("")
	})

	await writeLocalTextFile(out.join("\n"), path)

	return n
}
