/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   Looks up venue head words from `data/venue-heads.json`. A head word marks the phrase around it
 *   as a venue name: `gallery` as the last word of `Manchester Art Gallery`, `musée` as the first
 *   word of `Musée d'Orsay`, the suffix `galerie` inside `Nationalgalerie`, and `館` at the end of
 *   `国立西洋美術館`. The table is generated by
 *   `packages/mailwoman/tools/gazetteer-pipeline/poi/build/venue-heads.ts`.
 *
 *   Each entry holds a bias in natural-log units: the log of the head's rate in venue names over
 *   its higher rate in place names or street names of the same country. A head is positive evidence
 *   only. A word without an entry gives no information about whether the phrase is a venue.
 */

import { readPackagedTable } from "#packaged-data"

/**
 * Where a head sits in a name.
 */
export const VenueHeadPosition = {
	/**
	 * The first word of a name of two or more words.
	 */
	First: "first",
	/**
	 * The last word of a name of two or more words.
	 */
	Last: "last",
	/**
	 * A suffix of the last word, shorter than the word.
	 */
	Suffix: "suffix",
} as const

/**
 * One of {@linkcode VenueHeadPosition}.
 */
export type VenueHeadPosition = (typeof VenueHeadPosition)[keyof typeof VenueHeadPosition]

/**
 * Head biases for one position, keyed by the head in `normalizeFSTToken` form.
 */
export type VenueHeadBiases = Record<string, number>

/**
 * The heads of one country or one language aggregate.
 */
export interface VenueHeadEntries {
	first: VenueHeadBiases
	last: VenueHeadBiases
	suffix: VenueHeadBiases
}

/**
 * The distinct names each population held for one country.
 *
 * A zero `street` count means the corpus held no street spans for the country,
 * so its biases compare venue names with place names only.
 */
export interface VenueHeadPopulation {
	venue: number
	place: number
	street: number
}

/**
 * One country's heads with the populations they were measured on.
 */
export interface VenueHeadCountry extends VenueHeadEntries {
	names: VenueHeadPopulation
}

/**
 * The shape of `data/venue-heads.json`.
 */
export interface VenueHeadTable {
	version: number
	provenance: {
		venueSource: string
		placeSource: string
		/**
		 * The admin database whose every-language names and abbreviations are excluded as heads.
		 */
		adminSource: string
		streetSource: string
		minSupport: number
		minSuffixStems: number
		minBias: number
		minCountryVenueNames: number
	}
	/**
	 * Countries with at least `minCountryVenueNames` venue names, keyed by ISO 3166-1 alpha-2 code.
	 */
	countries: Record<string, VenueHeadCountry>
	/**
	 * Per-language aggregates keyed by ISO 639-3 code.
	 *
	 * Each is the mean of its countries' biases, with every country weighted equally
	 * and a missing entry counted as zero.
	 */
	languages: Record<string, VenueHeadEntries>
	/**
	 * ISO 639-3 official languages per country, for every country the venue source holds.
	 */
	countryLanguages: Record<string, string[]>
}

const TABLE = await readPackagedTable<VenueHeadTable>("venue-heads.json")

/**
 * Returns the table's provenance block.
 */
export function venueHeadProvenance(): VenueHeadTable["provenance"] {
	return TABLE.provenance
}

/**
 * Returns the countries that have their own entries.
 */
export function venueHeadCountries(): string[] {
	return Object.keys(TABLE.countries)
}

function layersFor(country: string): VenueHeadEntries[] {
	const code = country.toUpperCase()
	const layers: VenueHeadEntries[] = []
	const own = TABLE.countries[code]

	if (own) {
		layers.push(own)
	}

	for (const language of TABLE.countryLanguages[code] ?? []) {
		const aggregate = TABLE.languages[language]

		if (aggregate) {
			layers.push(aggregate)
		}
	}

	return layers
}

const SPACELESS_SCRIPT_RE = /^[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Hangul}\p{Script=Thai}]+$/u

const ALL_LANGUAGES: readonly VenueHeadEntries[] = Object.values(TABLE.languages)

function headBias(layers: readonly VenueHeadEntries[], position: VenueHeadPosition, key: string): number | null {
	for (const layer of layers) {
		const bias = layer[position][key]

		if (bias !== undefined) return bias
	}

	// A key written in a script without spaces between words identifies its language
	// family by script, so every language aggregate may answer it.
	// The highest bias wins.
	if (!SPACELESS_SCRIPT_RE.test(key)) return null
	let best: number | null = null

	for (const language of ALL_LANGUAGES) {
		const bias = language[position][key]

		if (bias !== undefined && (best === null || bias > best)) {
			best = bias
		}
	}

	return best
}

/**
 * Returns the head lookups for `country`, the shape `@mailwoman/neural`'s venue-head prior
 * reads: the bias of a word as the first word of a phrase, as its last word, or through the
 * longest suffix of the word that has an entry, each `null` when the table has no entry.
 *
 * A Latin-script or other spaced-script word is answered by the country's own entries
 * and then its language aggregates.
 * A word in a script written without spaces is also answered by every language aggregate,
 * so a session in one locale still reads `館` in a Japanese input.
 */
export function venueHeadLexicon(country: string): {
	first(word: string): number | null
	last(word: string): number | null
	suffix(word: string): number | null
} {
	const layers = layersFor(country)

	return {
		first: (word: string) => headBias(layers, VenueHeadPosition.First, word),
		last: (word: string) => headBias(layers, VenueHeadPosition.Last, word),
		suffix: (word: string) => {
			const characters = [...word]

			for (let start = 1; start < characters.length; start++) {
				const bias = headBias(layers, VenueHeadPosition.Suffix, characters.slice(start).join(""))

				if (bias !== null) return bias
			}

			return null
		},
	}
}
