/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   Looks up single-token venue-class hints from `data/venue-word-hints.json`. A hint says that a
 *   token appears mostly in venue names of one class, such as `teppanyaki` for food. The table is
 *   generated by `scripts/build-venue-word-hints.ts` and should not be edited by hand.
 *
 *   A hint is positive evidence only. A missing token means the table has no information about it,
 *   so consumers must not reject a venue because its tokens are absent.
 */

import { readPackagedTable } from "#packaged-data"

/**
 * One hint row.
 *
 * Rates are per million tokens of the respective name corpus.
 * Shares are fractions of the token's POI occurrences.
 */
export interface VenueWordHint {
	/**
	 * The dominant category class, such as food, retail or civic.
	 */
	topClass: string
	topClassShare: number
	/**
	 * The dominant leaf category.
	 *
	 * Its share is usually much lower than the class share, so a consumer should
	 * apply its own threshold before using it.
	 */
	topCategory: string | null
	topCategoryShare: number
	venueRatio: number
	poiFreq: number
	placeRatePPM: number
}

/**
 * The shape of `data/venue-word-hints.json`.
 */
export interface VenueWordHintTable {
	version: number
	provenance: {
		source: string
		sourceMD5: string
		bars: {
			venueRatioMin: number
			poiFreqMin: number
			topClassShareMin: number
			placeRatePPMMax: number
		}
	}
	hints: Record<string, VenueWordHint>
}

const TABLE = await readPackagedTable<VenueWordHintTable>("venue-word-hints.json")
const HINTS = new Map<string, VenueWordHint>(Object.entries(TABLE.hints))

/**
 * Returns the class hint for one token, or `null` when the table has none.
 *
 * The lookup is case-insensitive.
 * Callers must split longer queries into tokens themselves.
 */
export function venueWordHint(token: string): VenueWordHint | null {
	return HINTS.get(token.toLowerCase()) ?? null
}

/**
 * Returns the table's provenance block.
 */
export function venueWordHintProvenance(): VenueWordHintTable["provenance"] {
	return TABLE.provenance
}

/**
 * Returns the number of tokens that have a hint.
 */
export function venueWordHintCount(): number {
	return HINTS.size
}
