/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   Pure-Node matcher scale eval — the number behind "no Elasticsearch, no server."
 *
 *   The differentiator vs Pelias/Nominatim + a bolt-on ER stack is that the whole resolve (block →
 *   Fellegi-Sunter → cluster) runs in ONE Node process with no external service. This measures how
 *   far that goes: synthetic geo-clustered records (so geo-blocking produces realistic candidate
 *   pairs, not one giant block or all singletons), resolved at increasing N, timing wall-clock +
 *   peak RSS. Geocoding is NOT in scope here (it's the per-record cost measured elsewhere) — this
 *   isolates the matcher's block/score/cluster cost as a function of N.
 *
 *   Run: node --experimental-strip-types scripts/record-matcher/matcher-scale.ts\
 *   [--sizes 10000,50000,100000,250000,500000] [--dup 3] [--em] [--out-md <md>]
 */

import { resolveEntities, type SourceRecord } from "@mailwoman/registry"
import { writeFileSync } from "node:fs"

function arg(name: string, fallback = ""): string {
	const i = process.argv.indexOf(`--${name}`)
	return i >= 0 && process.argv[i + 1] ? process.argv[i + 1]! : fallback
}

const SIZES = arg("sizes", "10000,50000,100000,250000,500000")
	.split(",")
	.map((s) => Number(s.trim()))
	.filter((n) => n > 0)
const DUP = Number(arg("dup", "3")) // avg records per distinct place
const EM = process.argv.includes("--em")
const OUT_MD = arg("out-md", "")

/** Deterministic LCG so the eval is reproducible run to run (no Math.random). */
function lcg(seed: number): () => number {
	let s = seed >>> 0
	return () => {
		s = (Math.imul(s, 1664525) + 1013904223) >>> 0
		return s / 0x100000000
	}
}

/**
 * Generate N synthetic records clustered into ~N/DUP distinct "places". Each place gets a
 * coordinate in the continental-US box, a canonical key, and an org name; its DUP duplicates carry
 * a lightly-varied name and a jittered coordinate, so geo-cell + canonical-key blocking groups them
 * and scoring links them — the realistic shape of a dedup workload.
 */
function generate(n: number, seed = 1): SourceRecord[] {
	const rnd = lcg(seed)
	const places = Math.max(1, Math.round(n / DUP))
	const records: SourceRecord[] = new Array(n)
	for (let i = 0; i < n; i++) {
		const place = i % places
		const latitude = 25 + rnd() * 24 // ~25–49 N
		const longitude = -124 + rnd() * 57 // ~-124 to -67 W
		const variant = i < places ? "" : rnd() < 0.5 ? " llc" : " inc" // duplicates drift the name slightly
		records[i] = {
			id: String(i),
			organization: { canonical: `org ${place}${variant}`, raw: `Org ${place}` },
			address: {
				components: {},
				canonicalKey: `key-${place}`,
				raw: `${place} main st`,
				geocode: {
					coordinate: { latitude: latitude + (place % 7) * 1e-4, longitude: longitude + (place % 5) * 1e-4 },
					tier: "address_point",
					uncertaintyMeters: 5,
				},
			},
		} as SourceRecord
	}
	return records
}

const mb = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(0)} MB`
const sec = (ms: number) => `${(ms / 1000).toFixed(2)} s`

async function main(): Promise<void> {
	interface Measurement {
		n: number
		records: number
		entities: number
		candidatePairs: number
		wallMs: number
		rssBytes: number
	}
	const rows: Measurement[] = []

	for (const n of SIZES) {
		const records = generate(n)
		const t0 = performance.now()
		// learnedScorer:false — this measures the FS-baseline pipeline throughput baseline (the learned scorer
		// is now default-on; its per-pair tree eval is a separate cost, not what this scale number tracks).
		const { entities, candidatePairs } = resolveEntities(records, {
			collapseSpatial: true,
			trainEM: EM,
			learnedScorer: false,
		})
		const wallMs = performance.now() - t0
		const rssBytes = process.memoryUsage().rss
		rows.push({ n, records: records.length, entities: entities.length, candidatePairs, wallMs, rssBytes })
		console.error(
			`    N=${n}: ${sec(wallMs)}, ${candidatePairs} pairs → ${entities.length} entities, RSS ${mb(rssBytes)}`
		)
		// Encourage reclamation between sizes (RSS is a shared-process high-water — see the report note).
		if (global.gc) global.gc()
	}

	const lines: string[] = []
	lines.push(`# Matcher scale — pure-Node block → score → cluster (#K)`)
	lines.push("")
	lines.push(
		`_Generated by \`scripts/record-matcher/matcher-scale.ts\`. Synthetic geo-clustered records (~${DUP} per ` +
			`distinct place), resolved with the geo-first baseline (collapsed spatial${EM ? " + EM" : ""}) in ONE Node ` +
			`process — no Elasticsearch, no server. Geocoding is out of scope (measured separately); this isolates the ` +
			`matcher's block/score/cluster cost vs N._`
	)
	lines.push("")
	lines.push(`| records | candidate pairs | entities | wall-clock | resolve rate | RSS (high-water) |`)
	lines.push(`|---:|---:|---:|---:|---:|---:|`)
	for (const r of rows) {
		const rate = Math.round(r.records / (r.wallMs / 1000))
		lines.push(
			`| ${r.records.toLocaleString()} | ${r.candidatePairs.toLocaleString()} | ${r.entities.toLocaleString()} | ` +
				`${sec(r.wallMs)} | ${rate.toLocaleString()}/s | ${mb(r.rssBytes)} |`
		)
	}
	lines.push("")
	lines.push(`## Reading`)
	lines.push("")
	const last = rows[rows.length - 1]!
	lines.push(
		`The matcher resolves **${last.records.toLocaleString()} records in ${sec(last.wallMs)}** in a single Node ` +
			`process — block → Fellegi-Sunter → union-find clustering, no external service. Geo-cell + canonical-key ` +
			`blocking keeps candidate generation near-linear (it never enumerates the O(n²) pair space), so the wall-clock ` +
			`scales with the number of *blocked* pairs, not the square of N. That is the architectural claim made ` +
			`concrete: a calibrated street-level geocoder feeding the blocking lets entity resolution run in-process at ` +
			`hundreds of thousands of records, where a string-similarity matcher would need a search cluster to make the ` +
			`candidate generation tractable.`
	)
	lines.push("")
	lines.push(
		`RSS is the shared-process high-water mark across the sweep (each size reuses the heap), so it is an upper ` +
			`bound, not a per-N working set. The largest size that fits is bounded by the record objects + the link array; ` +
			`beyond that, shard by geography (each cell is independent) — the same partition the blocking already implies.`
	)
	lines.push("")
	lines.push(
		`One honest caveat on the shape: these are uniform-random US coordinates, so as N rises the geo-cell collision ` +
			`rate climbs and the candidate-pair count grows faster than N (visible in the table). Real address data clusters ` +
			`into a roughly fixed set of places, so its pair/record ratio is flatter — the wall-clock here, which tracks the ` +
			`number of PAIRS, is a conservative upper bound on a realistic workload of the same N.`
	)
	lines.push("")

	const md = lines.join("\n")
	console.log(md)
	if (OUT_MD) {
		writeFileSync(OUT_MD, md)
		console.error(`[written] ${OUT_MD}`)
	}
}

await main()
