/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   The Korean 시군구 (si / gun / gu: the second administrative tier) as the road-name address register writes them,
 *   each under its 시/도 (the first tier). 249 pairs over 226 distinct names; a compound city is
 *   one name (`성남시분당구`), the way the register keys it. 세종특별자치시 has no second tier and is absent.
 *
 *   Why a register: a character model closes a `subregion` span where the training set taught it names end, and a
 *   name it never saw (`해운대구`, held out of the training corpus by the board's design and unseen by the shipped
 *   model for the same reason) closes early, at `해` or `해운대`. The register states every boundary outright, so the
 *   decode-time repair in `@mailwoman/neural` extends a run to the one name the following characters spell.
 *
 *   Source: 행정안전부 (Ministry of the Interior and Safety), 도로명주소 (juso.go.kr), 공공누리 제1유형 (KOGL Type 1):
 *   attribution required; commercial use, derivatives and redistribution permitted.
 */

import { completeFromRegister } from "#register-completion"

/**
 * One second-tier unit under its first-tier region, both as the register writes them.
 */
export interface KoreanSigungu {
	region: string
	city: string
}

/**
 * The register: every (시/도, 시군구) pair the road-name address register carries, in register order.
 */
export const KR_SIGUNGU: readonly KoreanSigungu[] = [
	{ region: "강원도", city: "강릉시" },
	{ region: "강원도", city: "고성군" },
	{ region: "강원도", city: "동해시" },
	{ region: "강원도", city: "삼척시" },
	{ region: "강원도", city: "속초시" },
	{ region: "강원도", city: "양구군" },
	{ region: "강원도", city: "양양군" },
	{ region: "강원도", city: "영월군" },
	{ region: "강원도", city: "원주시" },
	{ region: "강원도", city: "인제군" },
	{ region: "강원도", city: "정선군" },
	{ region: "강원도", city: "철원군" },
	{ region: "강원도", city: "춘천시" },
	{ region: "강원도", city: "태백시" },
	{ region: "강원도", city: "평창군" },
	{ region: "강원도", city: "홍천군" },
	{ region: "강원도", city: "화천군" },
	{ region: "강원도", city: "횡성군" },
	{ region: "경기도", city: "가평군" },
	{ region: "경기도", city: "고양시덕양구" },
	{ region: "경기도", city: "고양시일산동구" },
	{ region: "경기도", city: "고양시일산서구" },
	{ region: "경기도", city: "과천시" },
	{ region: "경기도", city: "광명시" },
	{ region: "경기도", city: "광주시" },
	{ region: "경기도", city: "구리시" },
	{ region: "경기도", city: "군포시" },
	{ region: "경기도", city: "김포시" },
	{ region: "경기도", city: "남양주시" },
	{ region: "경기도", city: "동두천시" },
	{ region: "경기도", city: "부천시" },
	{ region: "경기도", city: "성남시분당구" },
	{ region: "경기도", city: "성남시수정구" },
	{ region: "경기도", city: "성남시중원구" },
	{ region: "경기도", city: "수원시권선구" },
	{ region: "경기도", city: "수원시영통구" },
	{ region: "경기도", city: "수원시장안구" },
	{ region: "경기도", city: "수원시팔달구" },
	{ region: "경기도", city: "시흥시" },
	{ region: "경기도", city: "안산시단원구" },
	{ region: "경기도", city: "안산시상록구" },
	{ region: "경기도", city: "안성시" },
	{ region: "경기도", city: "안양시동안구" },
	{ region: "경기도", city: "안양시만안구" },
	{ region: "경기도", city: "양주시" },
	{ region: "경기도", city: "양평군" },
	{ region: "경기도", city: "여주시" },
	{ region: "경기도", city: "연천군" },
	{ region: "경기도", city: "오산시" },
	{ region: "경기도", city: "용인시기흥구" },
	{ region: "경기도", city: "용인시수지구" },
	{ region: "경기도", city: "용인시처인구" },
	{ region: "경기도", city: "의왕시" },
	{ region: "경기도", city: "의정부시" },
	{ region: "경기도", city: "이천시" },
	{ region: "경기도", city: "파주시" },
	{ region: "경기도", city: "평택시" },
	{ region: "경기도", city: "포천시" },
	{ region: "경기도", city: "하남시" },
	{ region: "경기도", city: "화성시" },
	{ region: "경상남도", city: "거제시" },
	{ region: "경상남도", city: "거창군" },
	{ region: "경상남도", city: "고성군" },
	{ region: "경상남도", city: "김해시" },
	{ region: "경상남도", city: "남해군" },
	{ region: "경상남도", city: "밀양시" },
	{ region: "경상남도", city: "사천시" },
	{ region: "경상남도", city: "산청군" },
	{ region: "경상남도", city: "양산시" },
	{ region: "경상남도", city: "의령군" },
	{ region: "경상남도", city: "진주시" },
	{ region: "경상남도", city: "창녕군" },
	{ region: "경상남도", city: "창원시마산합포구" },
	{ region: "경상남도", city: "창원시마산회원구" },
	{ region: "경상남도", city: "창원시성산구" },
	{ region: "경상남도", city: "창원시의창구" },
	{ region: "경상남도", city: "창원시진해구" },
	{ region: "경상남도", city: "통영시" },
	{ region: "경상남도", city: "하동군" },
	{ region: "경상남도", city: "함안군" },
	{ region: "경상남도", city: "함양군" },
	{ region: "경상남도", city: "합천군" },
	{ region: "경상북도", city: "경산시" },
	{ region: "경상북도", city: "경주시" },
	{ region: "경상북도", city: "고령군" },
	{ region: "경상북도", city: "구미시" },
	{ region: "경상북도", city: "군위군" },
	{ region: "경상북도", city: "김천시" },
	{ region: "경상북도", city: "문경시" },
	{ region: "경상북도", city: "봉화군" },
	{ region: "경상북도", city: "상주시" },
	{ region: "경상북도", city: "성주군" },
	{ region: "경상북도", city: "안동시" },
	{ region: "경상북도", city: "영덕군" },
	{ region: "경상북도", city: "영양군" },
	{ region: "경상북도", city: "영주시" },
	{ region: "경상북도", city: "영천시" },
	{ region: "경상북도", city: "예천군" },
	{ region: "경상북도", city: "울릉군" },
	{ region: "경상북도", city: "울진군" },
	{ region: "경상북도", city: "의성군" },
	{ region: "경상북도", city: "청도군" },
	{ region: "경상북도", city: "청송군" },
	{ region: "경상북도", city: "칠곡군" },
	{ region: "경상북도", city: "포항시남구" },
	{ region: "경상북도", city: "포항시북구" },
	{ region: "광주광역시", city: "광산구" },
	{ region: "광주광역시", city: "남구" },
	{ region: "광주광역시", city: "동구" },
	{ region: "광주광역시", city: "북구" },
	{ region: "광주광역시", city: "서구" },
	{ region: "대구광역시", city: "남구" },
	{ region: "대구광역시", city: "달서구" },
	{ region: "대구광역시", city: "달성군" },
	{ region: "대구광역시", city: "동구" },
	{ region: "대구광역시", city: "북구" },
	{ region: "대구광역시", city: "서구" },
	{ region: "대구광역시", city: "수성구" },
	{ region: "대구광역시", city: "중구" },
	{ region: "대전광역시", city: "대덕구" },
	{ region: "대전광역시", city: "동구" },
	{ region: "대전광역시", city: "서구" },
	{ region: "대전광역시", city: "유성구" },
	{ region: "대전광역시", city: "중구" },
	{ region: "부산광역시", city: "강서구" },
	{ region: "부산광역시", city: "금정구" },
	{ region: "부산광역시", city: "기장군" },
	{ region: "부산광역시", city: "남구" },
	{ region: "부산광역시", city: "동구" },
	{ region: "부산광역시", city: "동래구" },
	{ region: "부산광역시", city: "부산진구" },
	{ region: "부산광역시", city: "북구" },
	{ region: "부산광역시", city: "사상구" },
	{ region: "부산광역시", city: "사하구" },
	{ region: "부산광역시", city: "서구" },
	{ region: "부산광역시", city: "수영구" },
	{ region: "부산광역시", city: "연제구" },
	{ region: "부산광역시", city: "영도구" },
	{ region: "부산광역시", city: "중구" },
	{ region: "부산광역시", city: "해운대구" },
	{ region: "서울특별시", city: "강남구" },
	{ region: "서울특별시", city: "강동구" },
	{ region: "서울특별시", city: "강북구" },
	{ region: "서울특별시", city: "강서구" },
	{ region: "서울특별시", city: "관악구" },
	{ region: "서울특별시", city: "광진구" },
	{ region: "서울특별시", city: "구로구" },
	{ region: "서울특별시", city: "금천구" },
	{ region: "서울특별시", city: "노원구" },
	{ region: "서울특별시", city: "도봉구" },
	{ region: "서울특별시", city: "동대문구" },
	{ region: "서울특별시", city: "동작구" },
	{ region: "서울특별시", city: "마포구" },
	{ region: "서울특별시", city: "서대문구" },
	{ region: "서울특별시", city: "서초구" },
	{ region: "서울특별시", city: "성동구" },
	{ region: "서울특별시", city: "성북구" },
	{ region: "서울특별시", city: "송파구" },
	{ region: "서울특별시", city: "양천구" },
	{ region: "서울특별시", city: "영등포구" },
	{ region: "서울특별시", city: "용산구" },
	{ region: "서울특별시", city: "은평구" },
	{ region: "서울특별시", city: "종로구" },
	{ region: "서울특별시", city: "중구" },
	{ region: "서울특별시", city: "중랑구" },
	{ region: "울산광역시", city: "남구" },
	{ region: "울산광역시", city: "동구" },
	{ region: "울산광역시", city: "북구" },
	{ region: "울산광역시", city: "울주군" },
	{ region: "울산광역시", city: "중구" },
	{ region: "인천광역시", city: "강화군" },
	{ region: "인천광역시", city: "계양구" },
	{ region: "인천광역시", city: "남구" },
	{ region: "인천광역시", city: "남동구" },
	{ region: "인천광역시", city: "동구" },
	{ region: "인천광역시", city: "부평구" },
	{ region: "인천광역시", city: "서구" },
	{ region: "인천광역시", city: "연수구" },
	{ region: "인천광역시", city: "옹진군" },
	{ region: "인천광역시", city: "중구" },
	{ region: "전라남도", city: "강진군" },
	{ region: "전라남도", city: "고흥군" },
	{ region: "전라남도", city: "곡성군" },
	{ region: "전라남도", city: "광양시" },
	{ region: "전라남도", city: "구례군" },
	{ region: "전라남도", city: "나주시" },
	{ region: "전라남도", city: "담양군" },
	{ region: "전라남도", city: "목포시" },
	{ region: "전라남도", city: "무안군" },
	{ region: "전라남도", city: "보성군" },
	{ region: "전라남도", city: "순천시" },
	{ region: "전라남도", city: "신안군" },
	{ region: "전라남도", city: "여수시" },
	{ region: "전라남도", city: "영광군" },
	{ region: "전라남도", city: "영암군" },
	{ region: "전라남도", city: "완도군" },
	{ region: "전라남도", city: "장성군" },
	{ region: "전라남도", city: "장흥군" },
	{ region: "전라남도", city: "진도군" },
	{ region: "전라남도", city: "함평군" },
	{ region: "전라남도", city: "해남군" },
	{ region: "전라남도", city: "화순군" },
	{ region: "전라북도", city: "고창군" },
	{ region: "전라북도", city: "군산시" },
	{ region: "전라북도", city: "김제시" },
	{ region: "전라북도", city: "남원시" },
	{ region: "전라북도", city: "무주군" },
	{ region: "전라북도", city: "부안군" },
	{ region: "전라북도", city: "순창군" },
	{ region: "전라북도", city: "완주군" },
	{ region: "전라북도", city: "익산시" },
	{ region: "전라북도", city: "임실군" },
	{ region: "전라북도", city: "장수군" },
	{ region: "전라북도", city: "전주시덕진구" },
	{ region: "전라북도", city: "전주시완산구" },
	{ region: "전라북도", city: "정읍시" },
	{ region: "전라북도", city: "진안군" },
	{ region: "제주특별자치도", city: "서귀포시" },
	{ region: "제주특별자치도", city: "제주시" },
	{ region: "충청남도", city: "계룡시" },
	{ region: "충청남도", city: "공주시" },
	{ region: "충청남도", city: "금산군" },
	{ region: "충청남도", city: "논산시" },
	{ region: "충청남도", city: "당진시" },
	{ region: "충청남도", city: "보령시" },
	{ region: "충청남도", city: "부여군" },
	{ region: "충청남도", city: "서산시" },
	{ region: "충청남도", city: "서천군" },
	{ region: "충청남도", city: "아산시" },
	{ region: "충청남도", city: "예산군" },
	{ region: "충청남도", city: "천안시동남구" },
	{ region: "충청남도", city: "천안시서북구" },
	{ region: "충청남도", city: "청양군" },
	{ region: "충청남도", city: "태안군" },
	{ region: "충청남도", city: "홍성군" },
	{ region: "충청북도", city: "괴산군" },
	{ region: "충청북도", city: "단양군" },
	{ region: "충청북도", city: "보은군" },
	{ region: "충청북도", city: "영동군" },
	{ region: "충청북도", city: "옥천군" },
	{ region: "충청북도", city: "음성군" },
	{ region: "충청북도", city: "제천시" },
	{ region: "충청북도", city: "증평군" },
	{ region: "충청북도", city: "진천군" },
	{ region: "충청북도", city: "청주시상당구" },
	{ region: "충청북도", city: "청주시서원구" },
	{ region: "충청북도", city: "청주시청원구" },
	{ region: "충청북도", city: "청주시흥덕구" },
	{ region: "충청북도", city: "충주시" },
]

/**
 * Every 시군구 name a `subregion` span may close on.
 */
export const KR_SIGUNGU_NAMES: readonly string[] = [...new Set(KR_SIGUNGU.map((s) => s.city))]

/**
 * The characters a `subregion` surface must absorb from what follows it to become a register name, or null.
 */
export function krSubregionCompletion(surface: string, following: string): string | null {
	return completeFromRegister(KR_SIGUNGU_NAMES, surface, following)
}
