/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 * @file The NPPES dedup benchmark's markdown report. Pure: every figure comes from the input, because eval figures are
 *   never hand-typed into docs.
 */

import type { TermFrequencyTable } from "@mailwoman/match"

import type { ResolveResult } from "#index"
import { ORG_TAU } from "#tools/nppes/org-name"
import type { Score } from "#tools/nppes/scoring"
import { COLOCATION_KM } from "#tools/nppes/truth-grains"

/**
 * F1 gap within which two blocking strategies are treated as equivalent.
 */
const BLOCKING_PARITY_TOLERANCE = 0.015

/**
 * One row of the lever progression, scored at the default threshold.
 */
export interface LeverScore {
	label: string
	score: Score
}

/**
 * One arm of the link-threshold sweep.
 */
export interface SweepArm {
	/**
	 * Link threshold, in bits.
	 */
	t: number
	res: Pick<ResolveResult, "candidatePairs" | "droppedBlocks">
	score: Score
}

/**
 * Everything the report reads.
 */
export interface NPPESReportInput {
	state: string
	/**
	 * Sampled NPIs — the true-entity count at the NPI grain.
	 */
	keptNpis: number
	recordCount: number
	/**
	 * Records whose address placed.
	 */
	geocoded: number
	trainEM: boolean
	/**
	 * The corpus-wide table the progression was fed; only its `total`/`distinct` are reported.
	 */
	addressFrequency: TermFrequencyTable
	/**
	 * The lever progression in order. The first row is the bare baseline, the last the full stack.
	 */
	progression: readonly LeverScore[]
	/**
	 * Zero-config `resolveEntities(records)` — reported apart from the progression because its address-frequency table is
	 * input-scoped, which on a sub-sample is intentionally sparse.
	 */
	defaultOutOfBox: Score
	sweep: readonly SweepArm[]
	/**
	 * The best-F1 arm. Must be an element of {@linkcode sweep} — the table stars it by identity.
	 */
	best: SweepArm
	entityCount: number
	orgCount: number
	orgCoordCount: number
	orgH3Count: number
	fsNPI: Score
	fsEntity: Score
	fsOrg: Score
	fsOrgCoord: Score
	gbtNPI: Score
	gbtEntity: Score
	gbtOrg: Score
	gbtOrgCoord: Score
	gbtOrgH3: Score
	/**
	 * The optional `--candidate` A/B row.
	 */
	candidate: { label: string; npi: Score; entity: Score } | null
	h3Res: number
	/**
	 * Sampled NPIs whose primary practice address placed — the population the coordinate grain can act on.
	 */
	geocodedNpis: number
}

/**
 * Render the run's markdown report.
 */
export function renderNPPESDedupReport(input: NPPESReportInput): string {
	const {
		state: STATE,
		keptNpis,
		recordCount: N,
		geocoded: geo,
		trainEM: TRAIN_EM,
		addressFrequency,
		progression,
		defaultOutOfBox,
		sweep,
		best,
		entityCount,
		orgCount,
		orgCoordCount,
		orgH3Count,
		fsNPI,
		fsEntity,
		fsOrg,
		fsOrgCoord,
		gbtNPI,
		gbtEntity,
		gbtOrg,
		gbtOrgCoord,
		gbtOrgH3,
		candidate: cand,
		h3Res: H3_RES,
		geocodedNpis,
	} = input

	const baseline = progression[0]! // no levers — the prior-prior behaviour
	// The LAST progression row — the whole A1–A5 stack, never compared on F1 against the others. Named for what it
	// is: a row called `best` invites reading a stack-wide delta as one lever's marginal effect, which is how the
	// authorized-official sentence below came to quote a five-lever number.
	const fullStack = progression.at(-1)!
	const base = sweep[0]! // threshold 0, full lever stack

	// NOTE(phase4): local pct keeps the fraction-in/no-%-suffix shape — not core formatPercent's
	// numerator/denominator contract (call sites append their own "%").
	const pct = (x: number) => (100 * x).toFixed(1)
	const signed = (x: number) => `${x >= 0 ? "+" : ""}${x.toFixed(1)}pp`

	const lines: string[] = [
		`# NPPES NPI dedup benchmark (#617)`,
		"",
		`_Generated by \`mailwoman registry scorer-eval nppes-benchmark\`. Sample: ${keptNpis} ${STATE} NPIs with ≥1 ` +
			`alternate name → ${N} records (${(N / keptNpis).toFixed(1)}/NPI) from real registry + other-names + ` +
			`mailing-vs-practice variation. Matcher run BLIND to the NPI${TRAIN_EM ? ", EM-trained (label-free)" : ""}; ` +
			`geocoded ${pct(geo / N)}% of addresses. The NPI is held-out ground truth._`,
		"",
		`**Headline — org-name truth (the honest grain):** the shipped ` +
			`matcher resolves these records at **F1 ${pct(gbtOrg.f1)}%** against org-name entity-truth — not the NPI-level ` +
			`${pct(gbtNPI.f1)}%, which mostly measures NPI over-segmentation (one organization holds many subpart NPIs, so ` +
			`correct co-located merges are scored as errors). Same clusters, three rulers: ` +
			`**NPI ${pct(gbtNPI.f1)}% → site ${pct(gbtEntity.f1)}% → org-name ${pct(gbtOrg.f1)}%** ` +
			`(${keptNpis} NPI → ${entityCount} site → ${orgCount} org-name classes); the climb is the yardstick getting honest, ` +
			`not the model changing — gold-set validated (120/120 hard pairs = same org). Details in "Three truth grains" below.`,
		"",
		`## The comparison-model levers (each toggled on, at the default threshold)`,
		"",
		`| model | precision | recall | F1 | ΔF1 | ARI | over-merged |`,
		`|---|---:|---:|---:|---:|---:|---:|`,
	]

	progression.forEach((p, i) => {
		const delta = i === 0 ? "—" : signed(100 * (p.score.f1 - progression[i - 1]!.score.f1))
		const bold = i === progression.length - 1
		const w = (s: string) => (bold ? `**${s}**` : s)

		lines.push(
			`| ${w(p.label)} | ${w(pct(p.score.precision) + "%")} | ${w(pct(p.score.recall) + "%")} | ${w(pct(p.score.f1) + "%")} | ${delta} | ${w(p.score.ari.toFixed(3))} | ${w(String(p.score.overMergedClusters))} |`
		)
	})

	lines.push("")

	lines.push(
		`Inverse-frequency weighting uses the corpus-wide table (${addressFrequency.distinct.toLocaleString()} distinct addresses ` +
			`over ${addressFrequency.total.toLocaleString()} providers) to down-weight a crowded shared address; collapsing the redundant ` +
			`address-key + distance comparisons into one spatial signal (A1) removes the double-count that let a shared address ` +
			`over-vote a disagreeing name. The address-frequency + A1 baseline is F1 ${pct(progression[2]!.score.f1)}% at the ` +
			`default threshold; the **authorized-official discriminator** is roughly neutral there (${signed(100 * (progression[3]!.score.f1 - progression[2]!.score.f1))}) ` +
			`but enables a higher cutoff — it holds recall where the baseline alone collapses, reaching **${pct(best.score.f1)}%** at ` +
			`threshold ${best.t} (below), the first config past the baseline (#625).`
	)

	lines.push("")

	lines.push(
		`**Out-of-the-box (zero-config \`resolveEntities(records)\`, levers default-on #86):** F1 ` +
			`**${pct(defaultOutOfBox.f1)}%** on this sample — essentially the baseline. The default auto-computes the ` +
			`address-frequency table over the INPUT records, and this benchmark deliberately sub-samples ${N} records, so ` +
			`that table is too sparse to carry the inverse-frequency signal (a corpus statistic you can't synthesize from a ` +
			`slice). It's **not a regression** (≥ baseline, no over-merge added) — it's the honest floor when the input isn't ` +
			`corpus-scale. Fed the corpus-wide table (the \`+ inverse-address-frequency\` row above, what the CLI builds from ` +
			`the full source files) the SAME default reaches the **${pct(progression[2]!.score.f1)}%** baseline. On a full-dataset ` +
			`dedup the input IS the corpus, so zero-config reaches the baseline on its own.`
	)

	lines.push("")
	lines.push(`## With all levers on, across the link threshold (the secondary lever)`)
	lines.push("")
	lines.push(`| link threshold (bits) | precision | recall | F1 | ARI | clusters | over-merged |`)
	lines.push(`|---:|---:|---:|---:|---:|---:|---:|`)

	for (const s of sweep) {
		const star = s === best ? " ⭐" : ""

		lines.push(
			`| ${s.t}${s.t === 0 ? " (default)" : ""} | ${pct(s.score.precision)}% | ${pct(s.score.recall)}% | **${pct(s.score.f1)}%**${star} | ${s.score.ari.toFixed(3)} | ${s.score.clusters} | ${s.score.overMergedClusters} |`
		)
	}

	lines.push("")

	lines.push(
		best.t === 0
			? `Best F1 is at the **default threshold** (${pct(base.score.f1)}%): raising it only trades recall away faster ` +
					`than it buys precision. So the threshold knob alone can't separate co-located distinct providers — the ` +
					`over-merge is structural, in the comparison model, not the cutoff.`
			: `Best F1 **${pct(best.score.f1)}%** (ARI ${best.score.ari.toFixed(3)}) at threshold ${best.t}, vs **${pct(base.score.f1)}%** at the ` +
					`default — the threshold knob moves it ${(100 * (best.score.f1 - base.score.f1)).toFixed(0)}pp. Higher thresholds trade recall for precision.`
	)

	lines.push("")
	lines.push(`## Shape + where the errors are (at the default threshold)`)
	lines.push("")
	lines.push(`- records: ${N} · true entities (NPIs): ${keptNpis} · recovered clusters: ${base.score.clusters}`)

	lines.push(
		`- candidate pairs blocked: ${base.res.candidatePairs}${base.res.droppedBlocks.length ? ` · oversized blocks skipped: ${base.res.droppedBlocks.length}` : ""}`
	)

	lines.push(
		`- **Over-merge (precision):** ${base.score.overMergedClusters} clusters fuse ≥2 distinct NPIs (largest fuses ` +
			`${base.score.maxNpisFused}; ${base.score.recordsInOverMerged} records) — **co-located providers sharing a clinic / ` +
			`billing address**, linked by address agreement despite different names.`
	)

	lines.push(
		`- **Under-merge (recall):** ${base.score.splitNpis}/${keptNpis} NPIs split across >1 cluster — records at distant ` +
			`addresses (mailing vs practice) or with strong name drift the score didn't bridge.`
	)

	lines.push("")
	lines.push(`## Three truth grains — NPI → site → org-name (the over-segmentation correction)`)
	lines.push("")

	lines.push(
		`NPI-as-truth OVER-SEGMENTS: one org holds many NPIs, so the matcher's correct co-located merges are scored as ` +
			`errors. Three yardsticks, same clusters: **NPI** (one entity per registration), **site** (subpart-flagged ` +
			`collapse + split an NPI's distinct addresses), and **org-name** — the gold-set-validated truth: same NPI ⇒ ` +
			`same entity (recall preserved) PLUS collapse co-located NPIs whose primary org names match (Jaccard ≥ ${ORG_TAU}), ` +
			`with NO reliance on the subpart flag (the gold set showed it misses 37%). The same ${N} records carry ` +
			`**${keptNpis} NPI** → **${entityCount} site** → **${orgCount} org-name** classes. The org-name number is the ` +
			`honest one: it stops charging the matcher for the same-org merges the gold set proved are correct.`
	)

	lines.push("")
	lines.push(`| config | truth | precision | recall | F1 | ΔF1 vs NPI | ARI | over-merged |`)
	lines.push(`|---|---|---:|---:|---:|---:|---:|---:|`)

	const dualRow = (label: string, truth: string, s: Score, delta?: number) =>
		lines.push(
			`| ${label} | ${truth} | ${pct(s.precision)}% | ${pct(s.recall)}% | **${pct(s.f1)}%** | ${delta === undefined ? "—" : signed(100 * delta)} | ${s.ari.toFixed(3)} | ${s.overMergedClusters} |`
		)

	dualRow("FS full stack", "NPI", fsNPI)
	dualRow("FS full stack", "site", fsEntity, fsEntity.f1 - fsNPI.f1)
	dualRow("FS full stack", "**org-name**", fsOrg, fsOrg.f1 - fsNPI.f1)
	dualRow("FS full stack", "org-name (coord)", fsOrgCoord, fsOrgCoord.f1 - fsNPI.f1)
	dualRow("GBT (shipped default)", "NPI", gbtNPI)
	dualRow("GBT (shipped default)", "site", gbtEntity, gbtEntity.f1 - gbtNPI.f1)
	dualRow("GBT (shipped default)", "**org-name**", gbtOrg, gbtOrg.f1 - gbtNPI.f1)
	dualRow("GBT (shipped default)", "**org-name (coord)**", gbtOrgCoord, gbtOrgCoord.f1 - gbtNPI.f1)
	dualRow("GBT (shipped default)", `org-name (H3 res ${H3_RES})`, gbtOrgH3, gbtOrgH3.f1 - gbtNPI.f1)

	if (cand) {
		dualRow(cand.label, "NPI", cand.npi)
		dualRow(cand.label, "**entity**", cand.entity, cand.entity.f1 - cand.npi.f1)
	}

	lines.push("")

	lines.push(
		`The F1 **climbs as the yardstick gets honest**: GBT **${pct(gbtNPI.f1)}% (NPI) → ${pct(gbtEntity.f1)}% (site) → ` +
			`${pct(gbtOrg.f1)}% (org-name)**, the over-merge collapsing (${gbtNPI.overMergedClusters} → ${gbtOrg.overMergedClusters}) ` +
			`and precision rising (${pct(gbtNPI.precision)}% → ${pct(gbtOrg.precision)}%). The clusters are IDENTICAL across the three ` +
			`columns — the climb is purely the ruler ceasing to charge the matcher for the correct same-org merges the gold set proved ` +
			`(\`2026-06-16-dedup-gold-set-tx120.md\`: 120/120 same org, 0 genuine over-merges).`
	)

	lines.push("")

	lines.push(
		`**Tier 2D — tightening the org-name ruler with the geocode coordinate.** The org-name truth above blocks by the address ` +
			`STRING (\`addressFrequencyKey\`), so two records at one building whose text differs — \`1504 Taub LOOP\` vs ` +
			`\`1504 Taub LP STE 100\` — key apart and the merge is still charged as an error. Block by the GEOCODED BUILDING instead ` +
			`(union co-located NPIs within ${COLOCATION_KM * 1000} m whose org names agree, same Jaccard gate) and the truth tightens ` +
			`further: GBT **org-name ${pct(gbtOrg.f1)}% → org-name-coord ${pct(gbtOrgCoord.f1)}%** ` +
			`(${signed(100 * (gbtOrgCoord.f1 - gbtOrg.f1))}), ${orgCount} → ${orgCoordCount} classes, over ${geocodedNpis}/${keptNpis} ` +
			`geocoded NPIs. The string org-name F1 is a conservative LOWER bound; the coordinate one is tighter (the Jaccard gate ` +
			`still blocks distinct co-located orgs). Both are honest — the coordinate is the geocode-first key.`
	)

	lines.push("")

	lines.push(
		`**H3-cell robustness check (#109).** Re-keying the same building-grain co-location on an H3 cell ` +
			`(res ${H3_RES}) instead of the 50 m haversine radius — the deterministic, O(n) "geocode-first cell" the issue ` +
			`suggested — gives GBT **org-name-h3 ${pct(gbtOrgH3.f1)}%** (${orgH3Count} classes), vs the haversine ` +
			`${pct(gbtOrgCoord.f1)}% (${orgCoordCount}). ${
				Math.abs(gbtOrgH3.f1 - gbtOrgCoord.f1) < BLOCKING_PARITY_TOLERANCE
					? "Within noise of the haversine grain — the ~" +
						pct(gbtOrgCoord.f1) +
						"% coord-grain F1 is robust to the co-location method, not an artifact of the 50 m threshold."
					: "The two co-location methods differ by " +
						signed(100 * (gbtOrgH3.f1 - gbtOrgCoord.f1)) +
						" — the cell-vs-radius boundary handling shifts the count (a hard H3 boundary can split a same-building pair into adjacent cells)."
			}`
	)

	lines.push("")

	lines.push(
		`**Takeaways:** (1) The dedup model's REAL quality is the **org-name F1 ~${pct(gbtOrg.f1)}%**, not the NPI-level ` +
			`${pct(gbtNPI.f1)}% — the difference was NPI over-segmentation, not model error. (2) The #625 lever was the YARDSTICK, ` +
			`not the scorer: the corroboration-feature experiment (reverted) couldn't move precision because the over-merge was ` +
			`mostly correct. (3) The remaining org-name over-merge (${gbtOrg.overMergedClusters} clusters) is the genuine frontier — ` +
			`small, approaching the ceiling's ~1.6% irreducible (\`2026-06-16-dedup-ceiling.md\`). (4) Trust the large eval: a 50-NPI ` +
			`smoke misled on the site delta (+5–7pp vs this run's ±2pp).`
	)

	lines.push("")

	lines.push(
		`Caveats: the programmatic site-truth is CONSERVATIVE (collapses only NPPES-flagged subparts; unflagged same-org pairs still ` +
			`read as over-merge), so it understates the subpart correction. A hand-adjudicated gold set on the ambiguous co-located + ` +
			`two-site slice is the next refinement (#625).`
	)

	lines.push("")
	lines.push(`## Reading`)
	lines.push("")

	lines.push(
		`The geocode-first **foundation works**: **${pct(geo / N)}%** of addresses placed, blocking + clustering clean — the ` +
			`geocoding (the Pelias/Nominatim-can't-do-this part) is not the bottleneck. The comparison-model levers reach the ` +
			`address-frequency + A1 baseline at F1 **${pct(progression[2]!.score.f1)}%** (${signed(100 * (progression[2]!.score.f1 - baseline.score.f1))} over baseline): ` +
			`inverse-frequency weighting restores full weight to a *rare* shared address (stitching a provider's name-drifted ` +
			`records together — mostly recall) while down-weighting a *crowded* one, and the collapsed spatial signal (A1) drops ` +
			`the address+distance double-count. What remains is **precision / over-merge** — ${fullStack.score.overMergedClusters} ` +
			`clusters still fuse distinct co-located providers, because even one down-weighted spatial agreement can outvote a ` +
			`disagreeing name. The lever search (#625) — two negatives, then the first positive: a name/org/phone ` +
			`**corroboration gate** (A2/A3) — phone is an unreliable secondary identifier on NPPES (shared institutional ` +
			`switchboard lines), so it over-links and falsely corroborates co-phone distinct providers; and **average-linkage ` +
			`clustering** (A4) — the over-merged clusters are joined by STRONG shared-address edges, not weak bridges, so ` +
			`average-linkage can't split them and only trades away name-drift recall. The over-merge is a **scoring** problem ` +
			`this data can't resolve, not a clustering-topology one. The **authorized-official discriminator** is the first lever to beat the baseline — a reliable secondary identifier holds recall so a higher threshold separates the co-located providers; a still-more-distinctive identifier ` +
			`(taxonomy / license) or a learned scorer over the FS feature vector (#603) goes further. Config ` +
			`dominates the model (the pre-registered finding) — tracked as #625 / the selective-model work (#602 / #603).`
	)

	lines.push("")

	lines.push(
		`NPI-as-truth is **conservative**: a cluster fusing two NPIs is a candidate "same entity, two NPIs" surfaced for ` +
			`review, not an adjudicated error; an NPI split across genuinely-distant addresses is geo-first behaving correctly, ` +
			`counted here as a recall miss. We resolve and report; interpretation is the consumer's.`
	)

	lines.push("")

	return lines.join("\n")
}
