/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   The hard-slice board's TOPONYM-REGISTER rows — inputs whose difficulty is the NAME, not the shape.
 *
 *   The four classes here are the ways one surface can mean several places, ordered by what decides:
 *
 *   - `homonym_confound` — a trailing region determines the result (#267/#833/#905).
 *   - `bare_namesake` — nothing determines the result but ranking; the answer has to be dominant enough to pin.
 *   - `wiki_pop_conflict` — population and encyclopedic importance pick DIFFERENT bearers, so the row is
 *       the disagreement itself. Saint-Denis is the canonical member.
 *   - `street_head_control` — the surface is a toponym in street-head position and must NOT be pulled to
 *       locality (#1142). These are the arm comparison's cost side: where a bigger bias is dangerous.
 *
 *   The shape-driven half lives in `hard-slice-rows.ts`; both are concatenated by the builder.
 */

import { ADMIN_TOL, CITY_TOL, type Curated } from "./hard-slice-rows.ts"

/**
 * See the file header — the four toponym-ambiguity classes, grouped by what disambiguates them.
 */
export const TOPONYM_ROWS: Curated[] = [
	//#region homonym_confound
	// The #267/#833/#905 lineage, region-abbreviated form.
	{
		id: "us-hc-portland-maine",
		input: "Portland, ME",
		locale: "en-us",
		country: "US",
		class: "homonym_confound",
		probeSurface: "Portland",
		expectID: 85_948_877,
		toleranceM: CITY_TOL,
		bugRef: "#833",
		note: "#833 — the greedy walk resolved region 'ME' to Messina (IT) and fell back to a Sicilian centroid. The descendant-consistency fix owns this row; the board watches whether a bias change re-opens it.",
	},
	{
		id: "us-hc-portland-oregon",
		input: "Portland, OR",
		locale: "en-us",
		country: "US",
		class: "homonym_confound",
		probeSurface: "Portland",
		expectID: 101_715_829,
		toleranceM: CITY_TOL,
		bugRef: "#833",
		note: "#833 sibling — region 'OR' collided with Ourense (ES). Guards that the fix generalizes across countries, not just one province.",
	},
	{
		id: "us-hc-springfield-illinois",
		input: "Springfield, IL",
		locale: "en-us",
		country: "US",
		class: "homonym_confound",
		probeSurface: "Springfield",
		expectID: 85_940_429,
		toleranceM: CITY_TOL,
		note: "The two scores DISAGREE about which Springfield leads: population ranks MO (171,589) first, encyclopedic importance ranks IL (0.6126) first. IL is the answer here, so the importance arm agrees with the truth for a reason the population arm does not have.",
	},
	{
		id: "us-hc-manchester-new-hampshire",
		input: "Manchester, NH",
		locale: "en-us",
		country: "US",
		class: "homonym_confound",
		probeSurface: "Manchester",
		expectID: 85_975_081,
		toleranceM: CITY_TOL,
		note: "13 US bearers against the English city. NH dominates both scorings, so this is the well-posed half of the Manchester pair (gb-wpc-manchester is the contested half).",
	},
	{
		id: "us-hc-vancouver-washington",
		input: "Vancouver, WA",
		locale: "en-us",
		country: "US",
		class: "homonym_confound",
		probeSurface: "Vancouver",
		expectID: 101_730_071,
		toleranceM: CITY_TOL,
		bugRef: "#905",
		note: "The inverse of #905's 'global-vancouver-bare': the bare form must reach Vancouver BC, but 'Vancouver, WA' must NOT. One surface, two correct answers, selected by context.",
	},
	{
		id: "us-hc-athens-ohio",
		input: "Athens, OH",
		locale: "en-us",
		country: "US",
		class: "homonym_confound",
		probeSurface: "Athens",
		expectID: 101_712_889,
		toleranceM: CITY_TOL,
		note: "The non-dominant US Athens (pop 24,673 vs Georgia's 128,628) — the region token is the only thing standing between this and the population winner.",
	},
	{
		id: "us-hc-lebanon-pennsylvania",
		input: "Lebanon, PA",
		locale: "en-us",
		country: "US",
		class: "homonym_confound",
		probeSurface: "Lebanon",
		expectID: 101_717_093,
		toleranceM: CITY_TOL,
		bugRef: "#1023",
		note: "Not the most populous Lebanon (TN is), but the highest-importance one (0.5412) — the two scorings pick different bearers and the region abbreviation decides.",
	},
	{
		id: "us-hc-portland-oregon-bare-region",
		input: "Portland Oregon",
		locale: "en-us",
		country: "US",
		class: "homonym_confound",
		probeSurface: "Portland",
		expectID: 101_715_829,
		toleranceM: CITY_TOL,
		bugRef: "#833",
		note: "#833's surface with the region SPELLED OUT and the comma removed — the abbreviation-free path, which does not benefit from region-abbrev recognition.",
	},
	//#endregion

	//#region bare_namesake
	// A bare toponym whose referential answer is dominant enough to pin.
	{
		id: "fr-bn-bordeaux",
		input: "Bordeaux",
		locale: "fr-fr",
		country: "FR",
		class: "bare_namesake",
		probeSurface: "Bordeaux",
		expectID: 101_748_979,
		toleranceM: ADMIN_TOL,
		note: "Bare FR toponym that is also a common noun (the wine). Bias 0.57 → 0.73.",
	},
	{
		id: "fr-bn-vichy",
		input: "Vichy",
		locale: "fr-fr",
		country: "FR",
		class: "bare_namesake",
		probeSurface: "Vichy",
		expectID: 101_829_199,
		toleranceM: ADMIN_TOL,
		note: "The clearest FR case of encyclopedic weight exceeding size: pop 27,019, bias 0.34 → 0.61. A brand, a regime, and a spa town share the surface.",
	},
	{
		id: "fr-bn-verdun",
		input: "Verdun",
		locale: "fr-fr",
		country: "FR",
		class: "bare_namesake",
		probeSurface: "Verdun",
		expectID: 101_828_321,
		toleranceM: ADMIN_TOL,
		note: "Largest FR bias delta on the board (0.32 → 0.63) on a town of 21,798 — a battle, not a population, drives the encyclopedic score.",
	},
	{
		id: "fr-bn-sedan",
		input: "Sedan",
		locale: "fr-fr",
		country: "FR",
		class: "bare_namesake",
		probeSurface: "Sedan",
		expectID: 101_840_285,
		toleranceM: ADMIN_TOL,
		note: "The surface is an everyday English common noun (a car body style) AND a French town of 20,620. Bias 0.32 → 0.60.",
	},
	{
		id: "fr-bn-reims",
		input: "Reims",
		locale: "fr-fr",
		country: "FR",
		class: "bare_namesake",
		probeSurface: "Reims",
		expectID: 101_751_377,
		toleranceM: ADMIN_TOL,
		note: "Dominant-bearer control for the FR bare class (pop 196,565, no serious namesake).",
	},
	{
		id: "gb-bn-whitby",
		input: "Whitby",
		locale: "en-gb",
		country: "GB",
		class: "bare_namesake",
		probeSurface: "Whitby",
		expectID: 101_874_191,
		toleranceM: ADMIN_TOL,
		note: "GB town of 13,130 with an outsized literary/abbey footprint. Bias 0.27 → 0.55.",
	},
	{
		id: "gb-bn-epping",
		input: "Epping",
		locale: "en-gb",
		country: "GB",
		class: "bare_namesake",
		probeSurface: "Epping",
		expectID: 101_854_747,
		toleranceM: ADMIN_TOL,
		note: "GB town of 12,547. Bias 0.27 → 0.48.",
	},
	{
		id: "gb-bn-windsor",
		input: "Windsor",
		locale: "en-gb",
		country: "GB",
		class: "bare_namesake",
		probeSurface: "Windsor",
		expectID: 101_854_695,
		toleranceM: ADMIN_TOL,
		note: "A dynasty, a knot, and a Berkshire town of 26,885. Bias 0.34 → 0.56.",
	},
	{
		id: "gb-bn-warwick",
		input: "Warwick",
		locale: "en-gb",
		country: "GB",
		class: "bare_namesake",
		probeSurface: "Warwick",
		expectID: 1_125_994_457,
		toleranceM: ADMIN_TOL,
		note: "GB town of 32,719 with a US namesake in Rhode Island. Bias 0.36 → 0.53.",
	},
	{
		id: "gb-bn-lincoln",
		input: "Lincoln",
		locale: "en-gb",
		country: "GB",
		class: "bare_namesake",
		probeSurface: "Lincoln",
		expectID: 101_750_523,
		toleranceM: ADMIN_TOL,
		note: "A surname, a US president, a US state capital, and a GB cathedral city of 97,541 — the highest-collision GB surface on the board.",
	},
	{
		id: "de-bn-trier",
		input: "Trier",
		locale: "de-de",
		country: "DE",
		class: "bare_namesake",
		probeSurface: "Trier",
		expectID: 101_748_559,
		toleranceM: ADMIN_TOL,
		note: "DE city of 111,528 whose Roman history outweighs its size. Bias 0.49 → 0.66.",
	},
	{
		id: "de-bn-speyer",
		input: "Speyer",
		locale: "de-de",
		country: "DE",
		class: "bare_namesake",
		probeSurface: "Speyer",
		expectID: 101_748_531,
		toleranceM: ADMIN_TOL,
		note: "DE city of 50,561. Bias 0.41 → 0.61 — the cathedral, not the population.",
	},
	{
		id: "de-bn-passau",
		input: "Passau",
		locale: "de-de",
		country: "DE",
		class: "bare_namesake",
		probeSurface: "Passau",
		expectID: 101_748_495,
		toleranceM: ADMIN_TOL,
		note: "DE city of 52,803. Bias 0.41 → 0.62.",
	},
	{
		id: "de-bn-worms",
		input: "Worms",
		locale: "de-de",
		country: "DE",
		class: "bare_namesake",
		probeSurface: "Worms",
		expectID: 101_906_801,
		toleranceM: ADMIN_TOL,
		note: "The surface is an English plural noun AND a DE city of 83,542 — the register trap the lowercase leg exists for. Bias 0.46 → 0.62.",
	},
	{
		id: "de-bn-jena",
		input: "Jena",
		locale: "de-de",
		country: "DE",
		class: "bare_namesake",
		probeSurface: "Jena",
		expectID: 101_748_613,
		toleranceM: ADMIN_TOL,
		note: "DE city of 111,343, also a common given name. Bias 0.49 → 0.65.",
	},
	{
		id: "de-bn-fulda",
		input: "Fulda",
		locale: "de-de",
		country: "DE",
		class: "bare_namesake",
		probeSurface: "Fulda",
		expectID: 101_748_593,
		toleranceM: ADMIN_TOL,
		note: "DE city of 68,635 that shares its name with the river it sits on. Bias 0.44 → 0.59.",
	},
	//#endregion

	//#region wiki_pop_conflict
	// The two scorings disagree, and the disagreement is the row.
	{
		id: "fr-wpc-saint-denis-suburb",
		input: "Saint-Denis",
		locale: "fr-fr",
		country: "FR",
		class: "wiki_pop_conflict",
		probeSurface: "Saint-Denis",
		expectID: 101_751_155,
		toleranceM: ADMIN_TOL,
		note: "THE canonical §2 test. The Seine-Saint-Denis suburb (pop 96,128) carries importance 0.1173; the Aude hamlet (pop 418) carries 0.5683. Encyclopedic importance ranks the hamlet 4.8x ABOVE the suburb — ranking on it would invert this row, which is precisely why the ratified policy ranks referentially.",
	},
	{
		id: "gb-wpc-bristol",
		input: "Bristol",
		locale: "en-gb",
		country: "GB",
		class: "wiki_pop_conflict",
		probeSurface: "Bristol",
		expectID: 1_175_612_699,
		toleranceM: ADMIN_TOL,
		note: "The ONLY downward delta on the board: Bristol (pop 472,465) scores 0.6348 by population and 0.3561 by importance — the importance arm cuts its bias nearly in half on one of GB's largest cities. Whatever the Wikipedia join did here, it moved the wrong way.",
	},
	{
		id: "gb-wpc-manchester",
		input: "Manchester",
		locale: "en-gb",
		country: "GB",
		class: "wiki_pop_conflict",
		probeSurface: "Manchester",
		expectID: 101_750_525,
		toleranceM: ADMIN_TOL,
		note: "A tag INVERSION rather than a magnitude change: population puts region (0.6539) fractionally above locality (0.6500); importance lifts locality to 0.7397 and leaves region at 0.6539. The arms disagree about which LABEL the surface prefers.",
	},
	{
		id: "us-wpc-new-york",
		input: "New York",
		locale: "en-us",
		country: "US",
		class: "wiki_pop_conflict",
		probeSurface: "New York",
		expectID: 85_977_539,
		toleranceM: ADMIN_TOL,
		bugRef: "#832",
		note: "The #832 surface, and the second tag inversion: population ranks region 1.0000 over locality 0.9364; importance ranks locality 0.8818 over region 0.8156. A two-token match, so the length scaling that discounts single-token hits does not apply.",
	},
	{
		id: "us-wpc-santiago-chile",
		input: "Santiago Chile",
		locale: "en-us",
		country: "CL",
		class: "wiki_pop_conflict",
		probeSurface: "Santiago",
		expectID: 8_075_437_716_681,
		toleranceM: ADMIN_TOL,
		note: "HIJACK PROBE. The en-us FST scores 'Santiago' 0.0052 by population — it has only obscure US bearers, the largest being a Washington hamlet of 52 — but 0.3436 by importance. The importance arm hands a 66x locality bias to a place nobody means, on a query whose answer is in Chile. If a real-importance swap costs anything, this row is where it shows.",
	},
	{
		id: "us-wpc-nassau-bahamas",
		input: "Nassau Bahamas",
		locale: "en-us",
		country: "BS",
		class: "wiki_pop_conflict",
		probeSurface: "Nassau",
		expectID: 9_000_000_120_280,
		toleranceM: ADMIN_TOL,
		note: "Second hijack probe, and the sweep's bs-cs-nassau (which resolved to NOTHING). US 'Nassau' bias 0.0755 → 0.4234 while the answer is a Bahamian capital carried on a SYNTHETIC place id (>= 9e12) — the id class the sweep's measured root cause implicates.",
	},
	{
		id: "us-wpc-springfield-bare",
		input: "Springfield",
		locale: "en-us",
		country: "US",
		class: "wiki_pop_conflict",
		probeSurface: "Springfield",
		expectID: 85_971_363,
		toleranceM: ADMIN_TOL,
		note: "The bare form of the disagreement: 149 US bearers, population leader Springfield MO (171,589), importance leader Springfield IL (0.6126 vs MO 0.5962). Pinned to the REFERENTIAL answer per the ratified §2 policy — a row the importance arm should NOT be able to move without violating it.",
	},
	//#endregion

	//#region street_head_control
	// A toponym in street-head position. The bias must NOT pull it to locality.
	// #1142's measured failure mode: real gazetteer importance dragged the leading token of a comma-free
	// street into `locality` ("Sweeney Ranch Road" → loc "Sweeney"), costing US golden 22 points. These rows
	// are where a bigger bias is DANGEROUS, so they are the arm comparison's cost side.
	{
		id: "us-shc-sweeney-ranch-road",
		input: "1000 Sweeney Ranch Road Half Moon Bay CA",
		locale: "en-us",
		country: "US",
		class: "street_head_control",
		probeSurface: "Sweeney",
		expectID: 85_922_515,
		toleranceM: ADMIN_TOL,
		bugRef: "#1142",
		note: "TRUE NEGATIVE CONTROL — 'Sweeney' scores 0.0000 in BOTH arms (two bearers, neither with population or importance), so any movement on this row is not the FST bias and must be explained some other way. The #1142 docstring's own example.",
	},
	{
		id: "us-shc-madison-avenue",
		input: "500 Madison Avenue New York NY",
		locale: "en-us",
		country: "US",
		class: "street_head_control",
		probeSurface: "Madison",
		expectID: 85_977_539,
		toleranceM: ADMIN_TOL,
		bugRef: "#1142",
		note: "The #1142 collision named in fst-prior.ts: Washington/Madison/Jackson are simultaneously the highest-importance US place names AND the commonest US street heads. 'Madison' bias 0.58 → 0.65, comma-free, in street-head position.",
	},
	{
		id: "us-shc-jackson-street",
		input: "1200 Jackson Street San Francisco CA",
		locale: "en-us",
		country: "US",
		class: "street_head_control",
		probeSurface: "Jackson",
		expectID: 85_922_583,
		toleranceM: ADMIN_TOL,
		bugRef: "#1142",
		note: "384 US bearers named Jackson — the highest fan-out street head on the board. Bias 0.52 → 0.62.",
	},
	{
		id: "us-shc-washington-boulevard",
		input: "3400 Washington Boulevard Los Angeles CA",
		locale: "en-us",
		country: "US",
		class: "street_head_control",
		probeSurface: "Washington",
		expectID: 85_923_517,
		toleranceM: ADMIN_TOL,
		bugRef: "#1142",
		note: "The third #1142 name, and a tag inversion besides: population scores region 0.9237 / locality 0.6721 (region clearly ahead); importance flattens both to 0.8148. The arm swap simultaneously raises the locality pull and removes the region's lead — in street-head position, the worst combination.",
	},
	{
		id: "us-shc-berlin-turnpike",
		input: "1800 Berlin Turnpike Hartford CT",
		locale: "en-us",
		country: "US",
		class: "street_head_control",
		probeSurface: "Berlin",
		expectID: 85_930_819,
		toleranceM: ADMIN_TOL,
		bugRef: "#1142",
		note: "A foreign-capital namesake as a street head, in a state that HAS a Berlin. Bias 0.24 → 0.49 — the largest proportional increase among the street-head controls.",
	},
	{
		id: "us-shc-lebanon-road",
		input: "700 Lebanon Road Nashville TN",
		locale: "en-us",
		country: "US",
		class: "street_head_control",
		probeSurface: "Lebanon",
		expectID: 101_723_183,
		toleranceM: ADMIN_TOL,
		bugRef: "#1142",
		note: "A country name as a street head, comma-free, with the real locality trailing. Pairs with us-cf-lebanon-tennessee: same surface, opposite correct label.",
	},
	{
		id: "fr-shc-rue-de-rome",
		input: "12 rue de Rome Paris",
		locale: "fr-fr",
		country: "FR",
		class: "street_head_control",
		probeSurface: "Rome",
		expectID: 101_751_119,
		toleranceM: ADMIN_TOL,
		bugRef: "#1103",
		note: "The operator's 2026-07-15 Paris list. 'Rome' MISSES the fr-fr FST entirely (it is country-scoped to FR), so this row is a declared ZERO-BIAS control in every arm — Paris→Rome is ~1,100 km, so any movement fails loud.",
	},
	{
		id: "gb-shc-manchester-road",
		input: "45 Manchester Road Sheffield",
		locale: "en-gb",
		country: "GB",
		class: "street_head_control",
		probeSurface: "Manchester",
		expectID: 101_750_529,
		toleranceM: ADMIN_TOL,
		bugRef: "#1142",
		note: "GB street-head control on the surface whose LABEL inverts between arms (see gb-wpc-manchester) — the inversion arrives here as a locality pull on a street head.",
	},
	//#endregion
]
