/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 * @file The one markdown-table renderer, for reports a command generates and a human commits.
 *
 *   Cells are padded to the widest in their column because `oxfmt` pads them the same way. An unpadded table
 *   fails `oxfmt --check`, which would leave the tree failing lint whenever a report is regenerated by its
 *   own documented command.
 */

/**
 * Cell width in code points, so a multi-byte name pads to what a reader sees
 * rather than to its UTF-16 length.
 */
function cellWidth(cell: string): number {
	return [...cell].length
}

/**
 * Render a GitHub-flavoured markdown table, padded the way `oxfmt` would pad it.
 *
 * A column is at least three characters wide, which is the narrowest separator GitHub accepts.
 * A row shorter than the header is padded with empty cells rather than raising:
 * a report that drops a column should print a gap rather than fail.
 */
export function renderMarkdownTable(header: readonly string[], rows: ReadonlyArray<readonly string[]>): string[] {
	const widths = header.map((cell, column) =>
		Math.max(3, cellWidth(cell), ...rows.map((row) => cellWidth(row[column] ?? "")))
	)

	const renderRow = (cells: readonly string[]): string => {
		const padded = widths.map((columnWidth, column) => {
			const cell = cells[column] ?? ""

			return cell + " ".repeat(Math.max(0, columnWidth - cellWidth(cell)))
		})

		return `| ${padded.join(" | ")} |`
	}

	return [
		renderRow(header),
		`| ${widths.map((columnWidth) => "-".repeat(columnWidth)).join(" | ")} |`,
		...rows.map((row) => renderRow(row)),
	]
}
