/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 * @file The one markdown-table renderer, for reports a command generates and a human commits.
 *
 *   IT PADS BECAUSE THE FORMATTER DOES. `oxfmt` pads a markdown table's cells to the widest cell in the
 *   column; an unpadded table fails `oxfmt --check`, so a scorecard regenerated by its own documented
 *   command leaves the tree failing lint until someone reformats it by hand. Emitting the padded form is
 *   what makes "regenerate and commit" a complete instruction.
 *
 *   Extracted from `@mailwoman/filer`'s linkage report, which had the only correct copy: three other
 *   report writers build their rows by hand and none of them pads.
 */

/**
 * Cell width in code points, so a multi-byte name pads to what a reader sees rather than to its UTF-16 length.
 */
function cellWidth(cell: string): number {
	return [...cell].length
}

/**
 * Render a GitHub-flavoured markdown table, padded the way `oxfmt` would pad it.
 *
 * A column is at least three characters wide, which is the narrowest separator GitHub accepts. A row shorter than the
 * header is padded with empty cells rather than raising: a report that drops a column should print a gap, not fail.
 */
export function renderMarkdownTable(header: readonly string[], rows: ReadonlyArray<readonly string[]>): string[] {
	const widths = header.map((cell, column) =>
		Math.max(3, cellWidth(cell), ...rows.map((row) => cellWidth(row[column] ?? "")))
	)

	const renderRow = (cells: readonly string[]): string => {
		const padded = widths.map((columnWidth, column) => {
			const cell = cells[column] ?? ""

			return cell + " ".repeat(Math.max(0, columnWidth - cellWidth(cell)))
		})

		return `| ${padded.join(" | ")} |`
	}

	return [
		renderRow(header),
		`| ${widths.map((columnWidth) => "-".repeat(columnWidth)).join(" | ")} |`,
		...rows.map((row) => renderRow(row)),
	]
}
