/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   Markdown renderer for the gazetteer depth scorecard — the committed artifact under
 *   `docs/articles/evals/coverage/`, following the `fill-rates.md` precedent.
 *
 *   The report declares its own limits inline rather than deferring them to a design doc. These
 *   numbers will outlive the conversation that produced them, and a reader six months out must be
 *   told IN THE FILE that counts are not quality and that the locality rung is self-comparison for
 *   the Overture-backfilled countries.
 *
 *   Pure: rows in, markdown out, `buildDate` injected by the caller so the output is deterministic
 *   under test.
 */

import type { ComponentTag } from "@mailwoman/core/types"

import { LADDER, type CountryGranularity, bottomsOutAt } from "./granularity.ts"

export interface GranularityReportMeta {
	/**
	 * Display path of the measured DB. Use the `$MAILWOMAN_DATA_ROOT`-relative form, never the resolved lab path.
	 */
	sourcePath: string
	sourceMD5: string
	/**
	 * ISO timestamp, injected rather than read from the clock so the renderer stays deterministic.
	 */
	buildDate: string
	floor: number
}

function pct(value: number): string {
	return `${(value * 100).toFixed(1)}%`
}

/**
 * One row's cell for a rung: node count, plus the Overture-backfilled share when any of it is backfilled.
 */
function rungCell(country: CountryGranularity, rung: ComponentTag): string {
	const measurement = country.rungs[rung]

	// Absent measurement = never measured. Distinct from a measured zero, which renders as "0".
	if (!measurement) return "—"

	if (!measurement.nodes) return "0"

	if (!measurement.overtureBackfilled) return measurement.nodes.toLocaleString()

	const share = measurement.overtureBackfilled / measurement.nodes

	return `${measurement.nodes.toLocaleString()} (${pct(share)} ovt)`
}

/**
 * Render the scorecard.
 */
export function renderGranularityReport(rows: CountryGranularity[], meta: GranularityReportMeta): string {
	const header = LADDER.join(" | ")
	const alignment = LADDER.map(() => "--:").join(" | ")

	const body = rows.map((country) => {
		const bottom = bottomsOutAt(country, meta.floor)
		const cells = LADDER.map((rung) => rungCell(country, rung)).join(" | ")

		return `| ${country.country} | ${bottom ?? "(none)"} | ${country.localityParents.toLocaleString()} | ${cells} |`
	})

	const reached = rows.filter((country) => bottomsOutAt(country, meta.floor) === "dependent_locality").length

	return `# Gazetteer depth scorecard

Generated by \`mailwoman gazetteer granularity\`. Per-country measurement of where the admin
gazetteer bottoms out — node counts per containment rung, and for the sub-locality rungs the
parent-coverage share (the fraction of the country's locality-class nodes carrying at least one
child projecting onto that rung).

- **Source:** \`${meta.sourcePath}\` (md5 \`${meta.sourceMD5}\`)
- **Built:** ${meta.buildDate}
- **Parent-coverage floor:** ${pct(meta.floor)} — a sub-locality rung counts as reached only above this.
- **Countries measured:** ${rows.length.toLocaleString()}
- **Countries reaching \`dependent_locality\`:** ${reached.toLocaleString()}

## What this report does not tell you

- **Counts are not quality.** A node count establishes where to look, never that the rows are good.
- **There is no demand-side grounding below the locality line.** Nothing here proves a sub-locality
  surface appears in real addresses. Overture's \`address_levels\` — the obvious instrument — bottoms
  out at municipality in every country measured, so it cannot see this tier.
- **The locality rung and above are partly self-comparison.** For the Overture-backfilled country
  set those rows came from Overture, not WOF; the \`ovt\` share in each cell is how much.
- **An empty rung is coverage, not fact.** \`ADMIN_PLACETYPES\` in \`admin/ingest-wof.ts\` allowlists
  9 of WOF's 34 placetypes, so for 25 of them the build never asked. Per the **meaning-of-zero**
  rule a measured-and-empty rung renders as \`0\` and a never-measured rung as \`—\`; they are not
  the same claim.

## Ladder

| country | bottoms out at | locality parents | ${header} |
| --- | --- | --: | ${alignment} |
${body.join("\n")}
`
}
