/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   The committed node-census baseline for `verifyAdmin` (#1026). Generated 2026-07-07 from the live
 *   `admin-global-priority.db` UNION the 95 countries the 2026-07-07 rebuild flattened (their country
 *   nodes are REQUIRED so the next rebuild must restore them — see #1023/#1026), with `region` added
 *   for GE (the #1023 trigger) and the 11 WOF-priority countries.
 *
 *   UPDATE DELIBERATELY: regenerate with `generateBaseline` (verify.ts) against a verified-good DB,
 *   re-apply the required-restore unions, and review the diff like code. A lagging baseline fails
 *   loudly; a hand-loosened one ships the next #1026.
 */

import type { VerifyBaseline } from "./verify.js"

export const DEFAULT_VERIFY_BASELINE: VerifyBaseline = {
	requiredNodes: {
		AE: ["country", "region"],
		AO: ["country", "region"],
		AR: ["country", "region"],
		AT: ["country", "region"],
		AU: ["country", "region"],
		BD: ["country", "region"],
		BE: ["country", "region"],
		BG: ["country", "region"],
		BH: ["country", "region"],
		BO: ["country", "region"],
		BR: ["country", "region"],
		BY: ["country", "region"],
		CA: ["country", "region"],
		CH: ["country", "region"],
		CI: ["country", "region"],
		CL: ["country", "region"],
		CM: ["country", "region"],
		CN: ["country", "region"],
		CO: ["country", "region"],
		CR: ["country", "region"],
		CU: ["country", "region"],
		CZ: ["country", "region"],
		DE: ["country", "region"],
		DK: ["country", "region"],
		DO: ["country", "region"],
		DZ: ["country", "region"],
		EC: ["country", "region"],
		EE: ["country", "region"],
		EG: ["country", "region"],
		ES: ["country", "region"],
		ET: ["country", "region"],
		FI: ["country", "region"],
		FR: ["country", "region"],
		GB: ["country", "region"],
		GH: ["country", "region"],
		GR: ["country", "region"],
		GT: ["country", "region"],
		HR: ["country", "region"],
		HU: ["country", "region"],
		ID: ["country", "region"],
		IE: ["country", "region"],
		IL: ["country", "region"],
		IN: ["country", "region"],
		IQ: ["country", "region"],
		IR: ["country", "region"],
		IS: ["country", "region"],
		IT: ["country", "region"],
		JO: ["country", "region"],
		JP: ["country", "region"],
		KE: ["country", "region"],
		KH: ["country", "region"],
		KR: ["country", "region"],
		KW: ["country", "region"],
		KZ: ["country", "region"],
		LB: ["country", "region"],
		LK: ["country", "region"],
		LT: ["country", "region"],
		LU: ["country", "region"],
		LV: ["country", "region"],
		MA: ["country", "region"],
		MM: ["country", "region"],
		MX: ["country", "region"],
		MY: ["country", "region"],
		NG: ["country", "region"],
		NL: ["country", "region"],
		NO: ["country", "region"],
		NP: ["country", "region"],
		NZ: ["country", "region"],
		OM: ["country", "region"],
		PA: ["country", "region"],
		PE: ["country", "region"],
		PH: ["country", "region"],
		PK: ["country", "region"],
		PL: ["country", "region"],
		PT: ["country", "region"],
		QA: ["country", "region"],
		RO: ["country", "region"],
		RS: ["country", "region"],
		RU: ["country", "region"],
		SA: ["country", "region"],
		SE: ["country", "region"],
		SG: ["country", "region"],
		SI: ["country", "region"],
		SK: ["country", "region"],
		SN: ["country", "region"],
		TH: ["country", "region"],
		TN: ["country", "region"],
		TR: ["country", "region"],
		TW: ["country", "region"],
		TZ: ["country", "region"],
		UA: ["country", "region"],
		UG: ["country", "region"],
		US: ["country", "region"],
		UY: ["country", "region"],
		VE: ["country", "region"],
		VN: ["country", "region"],
		ZA: ["country", "region"],
		AD: ["country"],
		AF: ["country"],
		AG: ["country"],
		AL: ["country"],
		AM: ["country"],
		AW: ["country"],
		AZ: ["country"],
		BA: ["country"],
		BB: ["country"],
		BF: ["country"],
		BI: ["country"],
		BJ: ["country"],
		BL: ["country"],
		BN: ["country"],
		BS: ["country"],
		BT: ["country"],
		BW: ["country"],
		BZ: ["country"],
		CD: ["country"],
		CF: ["country"],
		CG: ["country"],
		CV: ["country"],
		CW: ["country"],
		CY: ["country"],
		DJ: ["country"],
		DM: ["country"],
		ER: ["country"],
		FJ: ["country"],
		GA: ["country"],
		GD: ["country"],
		GE: ["country", "region"],
		GM: ["country"],
		GN: ["country"],
		GQ: ["country"],
		GW: ["country"],
		GY: ["country"],
		HN: ["country"],
		HT: ["country"],
		JM: ["country"],
		KG: ["country"],
		KI: ["country"],
		KM: ["country"],
		KN: ["country"],
		KP: ["country"],
		LA: ["country"],
		LC: ["country"],
		LI: ["country"],
		LR: ["country"],
		LS: ["country"],
		LY: ["country"],
		MC: ["country"],
		MD: ["country"],
		ME: ["country"],
		MF: ["country"],
		MG: ["country"],
		MK: ["country"],
		ML: ["country"],
		MN: ["country"],
		MR: ["country"],
		MT: ["country"],
		MU: ["country"],
		MV: ["country"],
		MW: ["country"],
		MZ: ["country"],
		NA: ["country"],
		NE: ["country"],
		NI: ["country"],
		NR: ["country"],
		PG: ["country"],
		PY: ["country"],
		RW: ["country"],
		SB: ["country"],
		SC: ["country"],
		SD: ["country"],
		SL: ["country"],
		SM: ["country"],
		SO: ["country"],
		SR: ["country"],
		SS: ["country"],
		ST: ["country"],
		SV: ["country"],
		SX: ["country"],
		SY: ["country"],
		SZ: ["country"],
		TD: ["country"],
		TF: ["country"],
		TG: ["country"],
		TJ: ["country"],
		TL: ["country"],
		TM: ["country"],
		TO: ["country"],
		TT: ["country"],
		TV: ["country"],
		UZ: ["country"],
		VA: ["country"],
		VC: ["country"],
		VU: ["country"],
		WS: ["country"],
		XK: ["country"],
		YE: ["country"],
		ZM: ["country"],
		ZW: ["country"],
	},
	minRows: 3962560,
	minCountries: 244,
}
