/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   Regenerate the language-code types and label maps in `core/resources/languages/types.gen.ts`.
 *   The generator reads the committed `internal/languages.csv` dictionary.
 *
 *   ISO 639-2 has /B (bibliographic) and /T (terminological) three-letter forms that differ for 20 languages.
 *   Who's On First uses /T in its name-property keys.
 *   A /B-only union excluded `deu`, `fra`, and `nld`, which identify three tier-1 locales.
 *   It also admitted spellings absent from the data.
 *   The built gazetteer's `names` table contains 3,591,751 rows with /T spellings and 247 rows with /B spellings.
 *
 *   /B is not dropped: `packages/codex/lib/country/official-languages.ts` lists both forms deliberately
 *   (`DE: ["de","deu","ger"]`) and 247 real rows contain one, so the union accepts either and both map to the same
 *   label and the same alpha-2.
 *
 *   `Alpha3bLanguageCode`, `Alpha3bLabelMap`, `Alpha3bToAlpha2` and the CSV's `alpha3-b` header still say "b"
 *   while holding both standards, because renaming them is a published-API break.
 *
 *   Usage: mailwoman dev generate language-types
 */

import { pascalCase } from "change-case"
import { CSVSpliterator } from "spliterator"

import { open } from "#fs/readers"
import { stringifyJSON } from "#json"
import { resourceDictionaryPath, workspacePath } from "#paths"

/**
 * Options for {@linkcode generateLanguageTypes}.
 */
export interface GenerateLanguageTypesOptions {
	/**
	 * Output path override.
	 *
	 * Default: `core/resources/languages/types.gen.ts` (the committed types).
	 */
	out?: string
}

/**
 * Summary returned by {@linkcode generateLanguageTypes}.
 */
export interface GenerateLanguageTypesSummary {
	languages: number
	outPath: string
}

/**
 * Regenerate the committed language-code types from `internal/languages.csv`.
 */
export async function generateLanguageTypes(
	options: GenerateLanguageTypesOptions = {},
	report?: (line: string) => void
): Promise<GenerateLanguageTypesSummary> {
	const outfile = options.out ?? workspacePath("core", "lib", "resources", "languages", "types.gen.ts")
	const dataSourcePath = resourceDictionaryPath("internal", "languages.csv")

	const alpha2Entries = new Map<string, string[]>()
	const alpha3bEntries = new Map<string, string[]>()
	const entryLines: [alpha2: string, alpha3b: string][] = []
	// The 20 divergent /T spellings, kept apart so they widen the accepting direction only.
	const alpha3tPairs: [alpha2: string, alpha3t: string][] = []

	report?.(`Reading ${dataSourcePath}`)

	// `header` defaults true and skips the `alpha3-b,alpha2,English` line.
	// The columns are read by position, so the mode is explicit rather than derived from them.
	for await (const columns of CSVSpliterator.fromAsync<string[]>(dataSourcePath, { mode: "array" })) {
		const alpha3b = columns[0] as string
		const alpha2 = columns[1] as string
		const labelsConcatenated = columns[2] as string
		// The two 639-2 forms agree for 163 languages.
		// The 20 languages with differing forms receive a distinct code.
		const alpha3t = (columns[3] as string | null) ?? ""

		const labels = labelsConcatenated.split("; ")

		alpha2Entries.set(alpha2, labels)
		alpha3bEntries.set(alpha3b, labels)

		entryLines.push([alpha2, alpha3b])

		// The /T spelling is a first-class member of the same union.
		// It maps to the same label and alpha-2 code.
		// WOF writes this form.
		// It goes to `alpha3tPairs` rather than `entryLines` because both lists build
		// their maps from a `new Map([...])` where the last entry for a key wins,
		// so appending it to `entryLines` would silently flip `Alpha2ToAlpha3b.get("de")`
		// from `ger` to `deu` in a map documented as returning /B.
		if (alpha3t) {
			alpha3bEntries.set(alpha3t, labels)
			alpha3tPairs.push([alpha2, alpha3t])
		}
	}

	await using handle = await open(outfile, "w")
	const writeLine = (line: string) => handle.writeFile(`${line}\n`)

	await writeLine(`
/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 * This file was generated by: mailwoman dev generate language-types
 */
`)

	await writeLine(`
	/**
	 * A two-letter language code.
	 */
	export type Alpha2LanguageCode =
	`)

	for (const alpha2 of alpha2Entries.keys()) {
		await writeLine(`  | "${alpha2}"`)
	}

	await writeLine(`
	/**
	 * An enumeration of ISO 639-1 language codes.
	 */
	export const Alpha2LanguageCode = {
	`)

	for (const [alpha2, labels] of alpha2Entries) {
		for (const label of labels) {
			await writeLine(`  ${pascalCase(label)}: "${alpha2}",`)
		}
	}

	await writeLine(`} as const satisfies Record<string, Alpha2LanguageCode>`)

	await writeLine(`
	/**
	 * A three-letter language code.
	 */
	export type Alpha3bLanguageCode =
	`)

	for (const alpha3b of alpha3bEntries.keys()) {
		await writeLine(`  | "${alpha3b}"`)
	}

	await writeLine(`
/**
 * A valid ISO 639-1 or ISO 639-2 language code.
 */
export type LanguageCode = Alpha2LanguageCode | Alpha3bLanguageCode | "all"
`)

	await writeLine(`
/**
 * A map of two-letter language codes to their labels.
 */
export const Alpha2LabelMap: ReadonlyMap<Alpha2LanguageCode, string[]> = new Map([
`)

	for (const [alpha2, labels] of alpha2Entries) {
		await writeLine(`["${alpha2}", ${stringifyJSON(labels)}],`)
	}

	await writeLine(`])`)

	await writeLine(`
/**
 * A map of three-letter language codes to their labels.
 */
export const Alpha3bLabelMap: ReadonlyMap<Alpha3bLanguageCode, string[]> = new Map([
`)

	for (const [alpha3b, labels] of alpha3bEntries) {
		await writeLine(`["${alpha3b}", ${stringifyJSON(labels)}],`)
	}

	await writeLine(`])`)

	await writeLine(`
/**
 * Convert a two-letter language code to a three-letter language code.
 */
export const Alpha2ToAlpha3b: ReadonlyMap<Alpha2LanguageCode, Alpha3bLanguageCode> = new Map([
`)

	for (const [alpha2, alpha3b] of entryLines) {
		await writeLine(`["${alpha2}", "${alpha3b}"],`)
	}

	await writeLine(`])`)

	await writeLine(`
/**
 * Convert a three-letter language code to a two-letter language code.
 */
export const Alpha3bToAlpha2: ReadonlyMap<Alpha3bLanguageCode, Alpha2LanguageCode> = new Map([
`)

	// This direction accepts a code, so it takes both spellings.
	// The keys are distinct and none is overwritten.
	// `deu` answers `de` exactly as `ger` does.
	for (const [alpha2, alpha3] of [...entryLines, ...alpha3tPairs]) {
		await writeLine(`["${alpha3}", "${alpha2}"],`)
	}

	await writeLine(`])`)

	report?.(`Wrote ${outfile}`)

	return { languages: entryLines.length, outPath: outfile }
}
