/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   GENERATED — do not edit by hand. Official languages per ISO 3166-1 territory, derived from
 *   Unicode CLDR 47.0.0 supplemental territoryInfo (`_officialStatus`). `official` merges
 *   CLDR's `official` + `de_facto_official`; `regional` is `official_regional` (kept separate —
 *   the #936 probe showed it pulls in cross-border quirks like Korean-in-CN, so consumers opt in).
 *   Every language appears under each ISO-639 spelling CLDR aliases to it (fi AND fin) so WOF
 *   639-3 tags, Overture BCP-47 keys, and GeoNames codes all match without mapping.
 *   Regenerate with scripts/build-official-languages.ts.
 */

/** Official-language spellings for one territory. */
export interface OfficialLanguageEntry {
	/** CLDR `official` + `de_facto_official`, in every ISO-639 spelling. */
	official: readonly string[]
	/** CLDR `official_regional` (e.g. Catalan in ES) — opt-in for consumers. */
	regional?: readonly string[]
}

/** ISO 3166-1 alpha-2 → official languages. */
export const OFFICIAL_LANGUAGES: Record<string, OfficialLanguageEntry> = {
	AD: { official: ["ca", "cat"] },
	AE: { official: ["ar", "ara", "arb"] },
	AF: { official: ["fa", "fas", "pbu", "per", "pes", "ps", "pus"], regional: ["tk", "tuk", "uz", "uzb", "uzn"] },
	AG: { official: ["en", "eng"] },
	AI: { official: ["en", "eng"] },
	AL: { official: ["alb", "als", "sq", "sqi"] },
	AM: { official: ["arm", "hy", "hye"] },
	AO: { official: ["por", "pt"] },
	AR: { official: ["es", "spa"] },
	AS: { official: ["en", "eng", "sm", "smo"] },
	AT: { official: ["de", "deu", "ger"], regional: ["hr", "hrv", "hu", "hun", "scr", "sl", "slv"] },
	AU: { official: ["en", "eng"] },
	AW: { official: ["dut", "nl", "nld", "pap"] },
	AX: { official: ["sv", "swe"] },
	AZ: { official: ["az", "aze", "azj"] },
	BA: { official: ["bos", "bs", "hr", "hrv", "scc", "scr", "sr", "srp"] },
	BB: { official: ["en", "eng"] },
	BD: { official: ["ben", "bn"] },
	BE: { official: ["de", "deu", "dut", "fr", "fra", "fre", "ger", "nl", "nld"] },
	BF: { official: ["fr", "fra", "fre"] },
	BG: { official: ["bg", "bul"] },
	BH: { official: ["ar", "ara", "arb"] },
	BI: { official: ["en", "eng", "fr", "fra", "fre", "rn", "run"] },
	BJ: { official: ["fr", "fra", "fre"] },
	BL: { official: ["fr", "fra", "fre"] },
	BM: { official: ["en", "eng"] },
	BN: { official: ["may", "ms", "msa", "zsm"] },
	BO: { official: ["ay", "aym", "ayr", "es", "qu", "que", "quz", "spa"] },
	BQ: { official: ["dut", "nl", "nld"] },
	BR: { official: ["por", "pt"], regional: ["vec"] },
	BS: { official: ["en", "eng"] },
	BT: { official: ["adp", "dz", "dzo"] },
	BW: { official: ["en", "eng", "tn", "tsn"] },
	BY: { official: ["be", "bel", "ru", "rus"] },
	BZ: { official: ["en", "eng"] },
	CA: {
		official: ["en", "eng", "fr", "fra", "fre"],
		regional: ["chp", "crk", "den", "dgr", "gwi", "ike", "iku", "iu", "xsl"],
	},
	CC: { official: ["en", "eng"] },
	CD: { official: ["fr", "fra", "fre"], regional: ["kg", "kng", "kon", "lin", "ln", "lua", "sw", "swa", "swh"] },
	CF: { official: ["fr", "fra", "fre", "sag", "sg"] },
	CG: { official: ["fr", "fra", "fre"] },
	CH: { official: ["de", "deu", "fr", "fra", "fre", "ger", "gsw", "it", "ita"], regional: ["rm", "roh"] },
	CI: { official: ["fr", "fra", "fre"] },
	CK: { official: ["en", "eng"] },
	CL: { official: ["es", "spa"] },
	CM: { official: ["en", "eng", "fr", "fra", "fre"] },
	CN: {
		official: ["chi", "cmn", "zh", "zho"],
		regional: ["bo", "bod", "drh", "khk", "ko", "kor", "mn", "mon", "tib", "ug", "uig", "za", "zha", "zyb"],
	},
	CO: { official: ["es", "spa"] },
	CQ: { official: ["en", "eng"] },
	CR: { official: ["es", "spa"] },
	CU: { official: ["es", "spa"] },
	CV: { official: ["por", "pt"] },
	CW: { official: ["dut", "nl", "nld", "pap"] },
	CX: { official: ["en", "eng"] },
	CY: { official: ["el", "ell", "gre", "tr", "tur"] },
	CZ: { official: ["ces", "cs", "cze"] },
	DE: { official: ["de", "deu", "ger"], regional: ["frr"] },
	DG: { official: ["en", "eng"] },
	DJ: { official: ["ar", "ara", "arb", "fr", "fra", "fre"] },
	DK: { official: ["da", "dan"], regional: ["de", "deu", "ger", "kal", "kl"] },
	DM: { official: ["en", "eng"] },
	DO: { official: ["es", "spa"] },
	DZ: { official: ["ar", "ara", "arb", "fr", "fra", "fre"] },
	EA: { official: ["es", "spa"] },
	EC: { official: ["es", "qu", "que", "quz", "spa"] },
	EE: { official: ["ekk", "est", "et"] },
	EG: { official: ["ar", "ara", "arb"] },
	EH: { official: ["ar", "ara", "arb"] },
	ER: { official: ["ar", "ara", "arb", "en", "eng", "ti", "tir"] },
	ES: { official: ["es", "spa"], regional: ["ast", "baq", "ca", "cat", "eu", "eus", "gl", "glg", "oc", "oci"] },
	ET: { official: ["am", "amh"] },
	FI: { official: ["fi", "fin", "sv", "swe"], regional: ["sms"] },
	FJ: { official: ["en", "eng", "fij", "fj", "hif"] },
	FK: { official: ["en", "eng"] },
	FM: { official: ["en", "eng"] },
	FO: { official: ["fao", "fo"] },
	FR: { official: ["fr", "fra", "fre"] },
	GA: { official: ["fr", "fra", "fre"] },
	GB: { official: ["en", "eng"], regional: ["cy", "cym", "ga", "gd", "gla", "gle", "wel"] },
	GD: { official: ["en", "eng"] },
	GE: { official: ["geo", "ka", "kat"], regional: ["ab", "abk", "os", "oss"] },
	GF: { official: ["fr", "fra", "fre"] },
	GG: { official: ["en", "eng"] },
	GH: { official: ["en", "eng"], regional: ["ak", "aka", "ee", "ewe", "fat", "gaa", "tw", "twi"] },
	GI: { official: ["en", "eng"] },
	GL: { official: ["kal", "kl"] },
	GM: { official: ["en", "eng"] },
	GN: { official: ["fr", "fra", "fre"] },
	GP: { official: ["fr", "fra", "fre"] },
	GQ: { official: ["es", "fr", "fra", "fre", "por", "pt", "spa"] },
	GR: { official: ["el", "ell", "gre"] },
	GS: { official: ["en", "eng"] },
	GT: { official: ["es", "spa"], regional: ["quc"] },
	GU: { official: ["ch", "cha", "en", "eng"] },
	GW: { official: ["por", "pt"] },
	GY: { official: ["en", "eng"] },
	HK: { official: ["chi", "cmn", "en", "eng", "zh", "zho"] },
	HN: { official: ["es", "spa"] },
	HR: { official: ["hr", "hrv", "scr"], regional: ["it", "ita", "vec"] },
	HT: { official: ["fr", "fra", "fre", "hat", "ht"] },
	HU: { official: ["hu", "hun"] },
	IC: { official: ["es", "spa"] },
	ID: { official: ["id", "in", "ind"] },
	IE: { official: ["en", "eng", "ga", "gle"] },
	IL: { official: ["ar", "ara", "arb", "he", "heb", "iw"] },
	IM: { official: ["en", "eng", "glv", "gv"] },
	IN: {
		official: ["en", "eng", "hi", "hin"],
		regional: [
			"as",
			"asm",
			"ben",
			"bn",
			"cls",
			"gom",
			"gu",
			"guj",
			"kan",
			"kas",
			"kha",
			"kn",
			"kok",
			"ks",
			"mai",
			"mal",
			"mar",
			"ml",
			"mr",
			"ne",
			"nep",
			"npi",
			"or",
			"ori",
			"ory",
			"pa",
			"pan",
			"prp",
			"sa",
			"san",
			"sat",
			"sd",
			"snd",
			"ta",
			"tam",
			"te",
			"tel",
			"ur",
			"urd",
		],
	},
	IO: { official: ["en", "eng"] },
	IQ: { official: ["ar", "ara", "arb"], regional: ["az", "aze", "azj", "ckb"] },
	IR: { official: ["fa", "fas", "per", "pes"] },
	IS: { official: ["ice", "is", "isl"] },
	IT: { official: ["it", "ita"], regional: ["fr", "fra", "fre", "vec"] },
	JE: { official: ["en", "eng"] },
	JM: { official: ["en", "eng"] },
	JO: { official: ["ar", "ara", "arb"] },
	JP: { official: ["ja", "jpn"] },
	KE: { official: ["en", "eng", "sw", "swa", "swh"] },
	KG: { official: ["kir", "ky", "ru", "rus"] },
	KH: { official: ["khm", "km"] },
	KI: { official: ["en", "eng", "gil"] },
	KM: { official: ["ar", "ara", "arb", "fr", "fra", "fre", "wni", "zdj"] },
	KN: { official: ["en", "eng"] },
	KP: { official: ["ko", "kor"] },
	KR: { official: ["ko", "kor"] },
	KW: { official: ["ar", "ara", "arb"] },
	KY: { official: ["en", "eng"] },
	KZ: { official: ["kaz", "kk", "ru", "rus"] },
	LA: { official: ["lao", "lo"] },
	LB: { official: ["ar", "ara", "arb"] },
	LC: { official: ["en", "eng"] },
	LI: { official: ["de", "deu", "ger", "gsw"] },
	LK: { official: ["si", "sin", "ta", "tam"] },
	LR: { official: ["en", "eng"] },
	LS: { official: ["en", "eng", "sot", "st"] },
	LT: { official: ["lit", "lt"] },
	LU: { official: ["de", "deu", "fr", "fra", "fre", "ger", "lb", "ltz"] },
	LV: { official: ["lav", "lv", "lvs"] },
	LY: { official: ["ar", "ara", "arb"] },
	MA: { official: ["ar", "ara", "arb", "fr", "fra", "fre", "tzm"] },
	MC: { official: ["fr", "fra", "fre"] },
	MD: { official: ["mo", "mol", "ro", "ron", "rum"] },
	ME: { official: ["scc", "sr", "srp"] },
	MF: { official: ["fr", "fra", "fre"] },
	MG: { official: ["en", "eng", "fr", "fra", "fre", "mg", "mlg", "plt"] },
	MH: { official: ["en", "eng", "mah", "mh"] },
	MK: { official: ["mac", "mk", "mkd"], regional: ["alb", "als", "sq", "sqi"] },
	ML: { official: ["fr", "fra", "fre"] },
	MM: { official: ["bur", "my", "mya"] },
	MN: { official: ["drh", "khk", "mn", "mon"] },
	MO: { official: ["chi", "cmn", "por", "pt", "yue", "zh", "zho"] },
	MP: { official: ["en", "eng"] },
	MQ: { official: ["fr", "fra", "fre"] },
	MR: { official: ["ar", "ara", "arb"] },
	MS: { official: ["en", "eng"] },
	MT: { official: ["en", "eng", "mlt", "mt"] },
	MU: { official: ["en", "eng", "fr", "fra", "fre"] },
	MV: { official: ["div", "dv"] },
	MW: { official: ["en", "eng", "ny", "nya"] },
	MX: { official: ["es", "spa"] },
	MY: { official: ["may", "ms", "msa", "zsm"] },
	MZ: { official: ["por", "pt"] },
	NA: { official: ["en", "eng"] },
	NC: { official: ["fr", "fra", "fre"] },
	NE: { official: ["fr", "fra", "fre"] },
	NF: { official: ["en", "eng"] },
	NG: { official: ["en", "eng", "yo", "yor"] },
	NI: { official: ["es", "spa"] },
	NL: { official: ["dut", "nl", "nld"], regional: ["fry", "fy"] },
	NO: { official: ["nb", "nn", "nno", "no", "nob", "nor"], regional: ["se", "sme"] },
	NP: { official: ["ne", "nep", "npi"] },
	NR: { official: ["en", "eng", "na", "nau"] },
	NU: { official: ["en", "eng", "niu"] },
	NZ: { official: ["en", "eng", "mao", "mi", "mri"] },
	OM: { official: ["ar", "ara", "arb"] },
	PA: { official: ["es", "spa"] },
	PE: { official: ["es", "qu", "que", "quz", "spa"] },
	PF: { official: ["fr", "fra", "fre", "tah", "ty"] },
	PG: { official: ["en", "eng", "hmo", "ho", "tpi"] },
	PH: { official: ["en", "eng", "fil", "tgl", "tl"], regional: ["ceb", "hil", "ilo", "mdh", "pag", "tsg", "war"] },
	PK: { official: ["en", "eng", "ur", "urd"] },
	PL: { official: ["pl", "pol"], regional: ["csb", "de", "deu", "ger", "lit", "lt"] },
	PM: { official: ["fr", "fra", "fre"] },
	PN: { official: ["en", "eng"] },
	PR: { official: ["en", "eng", "es", "spa"] },
	PS: { official: ["ar", "ara", "arb"] },
	PT: { official: ["por", "pt"] },
	PW: { official: ["en", "eng", "pau"] },
	PY: { official: ["es", "gn", "grn", "gug", "spa"] },
	QA: { official: ["ar", "ara", "arb"] },
	RE: { official: ["fr", "fra", "fre"] },
	RO: { official: ["mo", "mol", "ro", "ron", "rum"] },
	RS: {
		official: ["scc", "sr", "srp"],
		regional: ["hr", "hrv", "hu", "hun", "mo", "mol", "ro", "ron", "rum", "scr", "sk", "slk", "slo", "uk", "ukr"],
	},
	RU: {
		official: ["ru", "rus"],
		regional: [
			"ady",
			"av",
			"ava",
			"az",
			"aze",
			"azj",
			"ba",
			"bak",
			"ce",
			"che",
			"inh",
			"kbd",
			"koi",
			"kom",
			"kpv",
			"krc",
			"kum",
			"kv",
			"lbe",
			"lez",
			"mdf",
			"myv",
			"sah",
			"tat",
			"tt",
			"tyv",
			"udm",
		],
	},
	RW: { official: ["en", "eng", "fr", "fra", "fre", "kin", "rw"] },
	SA: { official: ["ar", "ara", "arb"] },
	SB: { official: ["en", "eng"] },
	SC: { official: ["en", "eng", "fr", "fra", "fre"] },
	SD: { official: ["ar", "ara", "arb", "en", "eng"] },
	SE: { official: ["sv", "swe"], regional: ["fi", "fin"] },
	SG: { official: ["chi", "cmn", "en", "eng", "may", "ms", "msa", "ta", "tam", "zh", "zho", "zsm"] },
	SH: { official: ["en", "eng"] },
	SI: { official: ["sl", "slv"], regional: ["vec"] },
	SJ: { official: ["nb", "nob"] },
	SK: { official: ["sk", "slk", "slo"] },
	SL: { official: ["en", "eng"] },
	SM: { official: ["it", "ita"] },
	SN: {
		official: ["fr", "fra", "fre", "wo", "wol"],
		regional: ["bjt", "bsc", "dyo", "ff", "fuc", "ful", "knf", "mey", "mfv", "sav", "snf", "srr", "tnr"],
	},
	SO: { official: ["ar", "ara", "arb", "so", "som"] },
	SR: { official: ["dut", "nl", "nld"] },
	SS: { official: ["en", "eng"] },
	ST: { official: ["por", "pt"] },
	SV: { official: ["es", "spa"] },
	SX: { official: ["dut", "en", "eng", "nl", "nld"] },
	SY: { official: ["ar", "ara", "arb"] },
	SZ: { official: ["en", "eng", "ss", "ssw"] },
	TC: { official: ["en", "eng"] },
	TD: { official: ["ar", "ara", "arb", "fr", "fra", "fre"] },
	TG: { official: ["fr", "fra", "fre"] },
	TH: { official: ["th", "tha"] },
	TJ: { official: ["tg", "tgk"] },
	TK: { official: ["en", "eng", "tkl"] },
	TL: { official: ["por", "pt", "tet"] },
	TM: { official: ["tk", "tuk"] },
	TN: { official: ["ar", "ara", "arb", "fr", "fra", "fre"] },
	TO: { official: ["en", "eng", "to", "ton"] },
	TR: { official: ["tr", "tur"] },
	TT: { official: ["en", "eng"] },
	TV: { official: ["en", "eng", "tvl"] },
	TW: { official: ["chi", "cmn", "hak", "nan", "zh", "zho"] },
	TZ: { official: ["en", "eng", "sw", "swa", "swh"] },
	UA: { official: ["ru", "rus", "uk", "ukr"] },
	UG: { official: ["en", "eng", "sw", "swa", "swh"] },
	UM: { official: ["en", "eng"] },
	US: { official: ["en", "eng"], regional: ["es", "haw", "spa"] },
	UY: { official: ["es", "spa"] },
	UZ: { official: ["uz", "uzb", "uzn"] },
	VA: { official: ["it", "ita"] },
	VC: { official: ["en", "eng"] },
	VE: { official: ["es", "spa"] },
	VG: { official: ["en", "eng"] },
	VI: { official: ["en", "eng"] },
	VN: { official: ["vi", "vie"] },
	VU: { official: ["bi", "bis", "en", "eng", "fr", "fra", "fre"] },
	WF: { official: ["fr", "fra", "fre"] },
	WS: { official: ["en", "eng", "sm", "smo"] },
	XK: { official: ["alb", "als", "scc", "sq", "sqi", "sr", "srp"] },
	YE: { official: ["ar", "ara", "arb"] },
	YT: { official: ["fr", "fra", "fre"] },
	ZA: {
		official: ["en", "eng"],
		regional: [
			"af",
			"afr",
			"nbl",
			"nr",
			"nso",
			"sot",
			"ss",
			"ssw",
			"st",
			"tn",
			"ts",
			"tsn",
			"tso",
			"ve",
			"ven",
			"xh",
			"xho",
			"zu",
			"zul",
		],
	},
	ZM: { official: ["en", "eng"] },
	ZW: { official: ["en", "eng", "nd", "nde", "sn", "sna"] },
}

/**
 * Is `language` (any ISO-639 spelling: "sv", "swe", …) an official language of `country` (ISO 3166-1 alpha-2)?
 * Regional-official languages count only with `includeRegional`.
 */
export function isOfficialLanguage(country: string, language: string, includeRegional = false): boolean {
	const entry = OFFICIAL_LANGUAGES[country.toUpperCase()]

	if (!entry) return false
	const lang = language.toLowerCase()

	return entry.official.includes(lang) || (includeRegional && (entry.regional?.includes(lang) ?? false))
}
