/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 *
 *   GENERATED — do not edit by hand. Country calling codes (E.164) + currencies (ISO 4217), derived
 *   from mledoze/countries (https://github.com/mledoze/countries, ODbL). NANP members map to 1.
 *   Regenerate with: mailwoman dev generate country-reference
 */

/** Static per-country reference: calling code + currency. */
export interface CountryReference {
	callingCode?: number
	currency?: { isoCode: string; name?: string; symbol?: string }
}

/** ISO 3166-1 alpha-2 → reference. */
export const COUNTRY_REFERENCE: Record<string, CountryReference> = {
	AD: { callingCode: 376, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	AE: { callingCode: 971, currency: { isoCode: "AED", name: "United Arab Emirates dirham", symbol: "د.إ" } },
	AF: { callingCode: 93, currency: { isoCode: "AFN", name: "Afghan afghani", symbol: "؋" } },
	AG: { callingCode: 1, currency: { isoCode: "XCD", name: "Eastern Caribbean dollar", symbol: "$" } },
	AI: { callingCode: 1, currency: { isoCode: "XCD", name: "Eastern Caribbean dollar", symbol: "$" } },
	AL: { callingCode: 355, currency: { isoCode: "ALL", name: "Albanian lek", symbol: "L" } },
	AM: { callingCode: 374, currency: { isoCode: "AMD", name: "Armenian dram", symbol: "֏" } },
	AO: { callingCode: 244, currency: { isoCode: "AOA", name: "Angolan kwanza", symbol: "Kz" } },
	AR: { callingCode: 54, currency: { isoCode: "ARS", name: "Argentine peso", symbol: "$" } },
	AS: { callingCode: 1, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	AT: { callingCode: 43, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	AU: { callingCode: 61, currency: { isoCode: "AUD", name: "Australian dollar", symbol: "$" } },
	AW: { callingCode: 297, currency: { isoCode: "AWG", name: "Aruban florin", symbol: "ƒ" } },
	AX: { callingCode: 35818, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	AZ: { callingCode: 994, currency: { isoCode: "AZN", name: "Azerbaijani manat", symbol: "₼" } },
	BA: { callingCode: 387, currency: { isoCode: "BAM", name: "Bosnia and Herzegovina convertible mark", symbol: "KM" } },
	BB: { callingCode: 1, currency: { isoCode: "BBD", name: "Barbadian dollar", symbol: "$" } },
	BD: { callingCode: 880, currency: { isoCode: "BDT", name: "Bangladeshi taka", symbol: "৳" } },
	BE: { callingCode: 32, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	BF: { callingCode: 226, currency: { isoCode: "XOF", name: "West African CFA franc", symbol: "Fr" } },
	BG: { callingCode: 359, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	BH: { callingCode: 973, currency: { isoCode: "BHD", name: "Bahraini dinar", symbol: ".د.ب" } },
	BI: { callingCode: 257, currency: { isoCode: "BIF", name: "Burundian franc", symbol: "Fr" } },
	BJ: { callingCode: 229, currency: { isoCode: "XOF", name: "West African CFA franc", symbol: "Fr" } },
	BL: { callingCode: 590, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	BM: { callingCode: 1, currency: { isoCode: "BMD", name: "Bermudian dollar", symbol: "$" } },
	BN: { callingCode: 673, currency: { isoCode: "BND", name: "Brunei dollar", symbol: "$" } },
	BO: { callingCode: 591, currency: { isoCode: "BOB", name: "Bolivian boliviano", symbol: "Bs." } },
	BQ: { callingCode: 599, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	BR: { callingCode: 55, currency: { isoCode: "BRL", name: "Brazilian real", symbol: "R$" } },
	BS: { callingCode: 1, currency: { isoCode: "BSD", name: "Bahamian dollar", symbol: "$" } },
	BT: { callingCode: 975, currency: { isoCode: "BTN", name: "Bhutanese ngultrum", symbol: "Nu." } },
	BV: { callingCode: 47 },
	BW: { callingCode: 267, currency: { isoCode: "BWP", name: "Botswana pula", symbol: "P" } },
	BY: { callingCode: 375, currency: { isoCode: "BYN", name: "Belarusian ruble", symbol: "Br" } },
	BZ: { callingCode: 501, currency: { isoCode: "BZD", name: "Belize dollar", symbol: "$" } },
	CA: { callingCode: 1, currency: { isoCode: "CAD", name: "Canadian dollar", symbol: "$" } },
	CC: { callingCode: 61, currency: { isoCode: "AUD", name: "Australian dollar", symbol: "$" } },
	CD: { callingCode: 243, currency: { isoCode: "CDF", name: "Congolese franc", symbol: "FC" } },
	CF: { callingCode: 236, currency: { isoCode: "XAF", name: "Central African CFA franc", symbol: "Fr" } },
	CG: { callingCode: 242, currency: { isoCode: "XAF", name: "Central African CFA franc", symbol: "Fr" } },
	CH: { callingCode: 41, currency: { isoCode: "CHF", name: "Swiss franc", symbol: "Fr." } },
	CI: { callingCode: 225, currency: { isoCode: "XOF", name: "West African CFA franc", symbol: "Fr" } },
	CK: { callingCode: 682, currency: { isoCode: "CKD", name: "Cook Islands dollar", symbol: "$" } },
	CL: { callingCode: 56, currency: { isoCode: "CLP", name: "Chilean peso", symbol: "$" } },
	CM: { callingCode: 237, currency: { isoCode: "XAF", name: "Central African CFA franc", symbol: "Fr" } },
	CN: { callingCode: 86, currency: { isoCode: "CNY", name: "Chinese yuan", symbol: "¥" } },
	CO: { callingCode: 57, currency: { isoCode: "COP", name: "Colombian peso", symbol: "$" } },
	CR: { callingCode: 506, currency: { isoCode: "CRC", name: "Costa Rican colón", symbol: "₡" } },
	CU: { callingCode: 53, currency: { isoCode: "CUC", name: "Cuban convertible peso", symbol: "$" } },
	CV: { callingCode: 238, currency: { isoCode: "CVE", name: "Cape Verdean escudo", symbol: "Esc" } },
	CW: { callingCode: 599, currency: { isoCode: "ANG", name: "Netherlands Antillean guilder", symbol: "ƒ" } },
	CX: { callingCode: 61, currency: { isoCode: "AUD", name: "Australian dollar", symbol: "$" } },
	CY: { callingCode: 357, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	CZ: { callingCode: 420, currency: { isoCode: "CZK", name: "Czech koruna", symbol: "Kč" } },
	DE: { callingCode: 49, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	DJ: { callingCode: 253, currency: { isoCode: "DJF", name: "Djiboutian franc", symbol: "Fr" } },
	DK: { callingCode: 45, currency: { isoCode: "DKK", name: "Danish krone", symbol: "kr" } },
	DM: { callingCode: 1, currency: { isoCode: "XCD", name: "Eastern Caribbean dollar", symbol: "$" } },
	DO: { callingCode: 1, currency: { isoCode: "DOP", name: "Dominican peso", symbol: "$" } },
	DZ: { callingCode: 213, currency: { isoCode: "DZD", name: "Algerian dinar", symbol: "د.ج" } },
	EC: { callingCode: 593, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	EE: { callingCode: 372, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	EG: { callingCode: 20, currency: { isoCode: "EGP", name: "Egyptian pound", symbol: "£" } },
	EH: { callingCode: 2, currency: { isoCode: "DZD", name: "Algerian dinar", symbol: "دج" } },
	ER: { callingCode: 291, currency: { isoCode: "ERN", name: "Eritrean nakfa", symbol: "Nfk" } },
	ES: { callingCode: 34, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	ET: { callingCode: 251, currency: { isoCode: "ETB", name: "Ethiopian birr", symbol: "Br" } },
	FI: { callingCode: 358, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	FJ: { callingCode: 679, currency: { isoCode: "FJD", name: "Fijian dollar", symbol: "$" } },
	FK: { callingCode: 500, currency: { isoCode: "FKP", name: "Falkland Islands pound", symbol: "£" } },
	FM: { callingCode: 691 },
	FO: { callingCode: 298, currency: { isoCode: "DKK", name: "Danish krone", symbol: "kr" } },
	FR: { callingCode: 33, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	GA: { callingCode: 241, currency: { isoCode: "XAF", name: "Central African CFA franc", symbol: "Fr" } },
	GB: { callingCode: 44, currency: { isoCode: "GBP", name: "British pound", symbol: "£" } },
	GD: { callingCode: 1, currency: { isoCode: "XCD", name: "Eastern Caribbean dollar", symbol: "$" } },
	GE: { callingCode: 995, currency: { isoCode: "GEL", name: "lari", symbol: "₾" } },
	GF: { callingCode: 594, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	GG: { callingCode: 44, currency: { isoCode: "GBP", name: "British pound", symbol: "£" } },
	GH: { callingCode: 233, currency: { isoCode: "GHS", name: "Ghanaian cedi", symbol: "₵" } },
	GI: { callingCode: 350, currency: { isoCode: "GIP", name: "Gibraltar pound", symbol: "£" } },
	GL: { callingCode: 299, currency: { isoCode: "DKK", name: "krone", symbol: "kr." } },
	GM: { callingCode: 220, currency: { isoCode: "GMD", name: "dalasi", symbol: "D" } },
	GN: { callingCode: 224, currency: { isoCode: "GNF", name: "Guinean franc", symbol: "Fr" } },
	GP: { callingCode: 590, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	GQ: { callingCode: 240, currency: { isoCode: "XAF", name: "Central African CFA franc", symbol: "Fr" } },
	GR: { callingCode: 30, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	GS: { callingCode: 500, currency: { isoCode: "SHP", name: "Saint Helena pound", symbol: "£" } },
	GT: { callingCode: 502, currency: { isoCode: "GTQ", name: "Guatemalan quetzal", symbol: "Q" } },
	GU: { callingCode: 1, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	GW: { callingCode: 245, currency: { isoCode: "XOF", name: "West African CFA franc", symbol: "Fr" } },
	GY: { callingCode: 592, currency: { isoCode: "GYD", name: "Guyanese dollar", symbol: "$" } },
	HK: { callingCode: 852, currency: { isoCode: "HKD", name: "Hong Kong dollar", symbol: "$" } },
	HN: { callingCode: 504, currency: { isoCode: "HNL", name: "Honduran lempira", symbol: "L" } },
	HR: { callingCode: 385, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	HT: { callingCode: 509, currency: { isoCode: "HTG", name: "Haitian gourde", symbol: "G" } },
	HU: { callingCode: 36, currency: { isoCode: "HUF", name: "Hungarian forint", symbol: "Ft" } },
	ID: { callingCode: 62, currency: { isoCode: "IDR", name: "Indonesian rupiah", symbol: "Rp" } },
	IE: { callingCode: 353, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	IL: { callingCode: 972, currency: { isoCode: "ILS", name: "Israeli new shekel", symbol: "₪" } },
	IM: { callingCode: 44, currency: { isoCode: "GBP", name: "British pound", symbol: "£" } },
	IN: { callingCode: 91, currency: { isoCode: "INR", name: "Indian rupee", symbol: "₹" } },
	IO: { callingCode: 246, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	IQ: { callingCode: 964, currency: { isoCode: "IQD", name: "Iraqi dinar", symbol: "ع.د" } },
	IR: { callingCode: 98, currency: { isoCode: "IRR", name: "Iranian rial", symbol: "﷼" } },
	IS: { callingCode: 354, currency: { isoCode: "ISK", name: "Icelandic króna", symbol: "kr" } },
	IT: { callingCode: 39, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	JE: { callingCode: 44, currency: { isoCode: "GBP", name: "British pound", symbol: "£" } },
	JM: { callingCode: 1, currency: { isoCode: "JMD", name: "Jamaican dollar", symbol: "$" } },
	JO: { callingCode: 962, currency: { isoCode: "JOD", name: "Jordanian dinar", symbol: "د.ا" } },
	JP: { callingCode: 81, currency: { isoCode: "JPY", name: "Japanese yen", symbol: "¥" } },
	KE: { callingCode: 254, currency: { isoCode: "KES", name: "Kenyan shilling", symbol: "Sh" } },
	KG: { callingCode: 996, currency: { isoCode: "KGS", name: "Kyrgyzstani som", symbol: "с" } },
	KH: { callingCode: 855, currency: { isoCode: "KHR", name: "Cambodian riel", symbol: "៛" } },
	KI: { callingCode: 686, currency: { isoCode: "AUD", name: "Australian dollar", symbol: "$" } },
	KM: { callingCode: 269, currency: { isoCode: "KMF", name: "Comorian franc", symbol: "Fr" } },
	KN: { callingCode: 1, currency: { isoCode: "XCD", name: "Eastern Caribbean dollar", symbol: "$" } },
	KP: { callingCode: 850, currency: { isoCode: "KPW", name: "North Korean won", symbol: "₩" } },
	KR: { callingCode: 82, currency: { isoCode: "KRW", name: "South Korean won", symbol: "₩" } },
	KW: { callingCode: 965, currency: { isoCode: "KWD", name: "Kuwaiti dinar", symbol: "د.ك" } },
	KY: { callingCode: 1, currency: { isoCode: "KYD", name: "Cayman Islands dollar", symbol: "$" } },
	KZ: { callingCode: 7, currency: { isoCode: "KZT", name: "Kazakhstani tenge", symbol: "₸" } },
	LA: { callingCode: 856, currency: { isoCode: "LAK", name: "Lao kip", symbol: "₭" } },
	LB: { callingCode: 961, currency: { isoCode: "LBP", name: "Lebanese pound", symbol: "ل.ل" } },
	LC: { callingCode: 1, currency: { isoCode: "XCD", name: "Eastern Caribbean dollar", symbol: "$" } },
	LI: { callingCode: 423, currency: { isoCode: "CHF", name: "Swiss franc", symbol: "Fr" } },
	LK: { callingCode: 94, currency: { isoCode: "LKR", name: "Sri Lankan rupee", symbol: "Rs රු" } },
	LR: { callingCode: 231, currency: { isoCode: "LRD", name: "Liberian dollar", symbol: "$" } },
	LS: { callingCode: 266, currency: { isoCode: "LSL", name: "Lesotho loti", symbol: "L" } },
	LT: { callingCode: 370, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	LU: { callingCode: 352, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	LV: { callingCode: 371, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	LY: { callingCode: 218, currency: { isoCode: "LYD", name: "Libyan dinar", symbol: "ل.د" } },
	MA: { callingCode: 212, currency: { isoCode: "MAD", name: "Moroccan dirham", symbol: "د.م." } },
	MC: { callingCode: 377, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	MD: { callingCode: 373, currency: { isoCode: "MDL", name: "Moldovan leu", symbol: "L" } },
	ME: { callingCode: 382, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	MF: { callingCode: 590, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	MG: { callingCode: 261, currency: { isoCode: "MGA", name: "Malagasy ariary", symbol: "Ar" } },
	MH: { callingCode: 692, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	MK: { callingCode: 389, currency: { isoCode: "MKD", name: "denar", symbol: "den" } },
	ML: { callingCode: 223, currency: { isoCode: "XOF", name: "West African CFA franc", symbol: "Fr" } },
	MM: { callingCode: 95, currency: { isoCode: "MMK", name: "Burmese kyat", symbol: "Ks" } },
	MN: { callingCode: 976, currency: { isoCode: "MNT", name: "Mongolian tögrög", symbol: "₮" } },
	MO: { callingCode: 853, currency: { isoCode: "MOP", name: "Macanese pataca", symbol: "P" } },
	MP: { callingCode: 1, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	MQ: { callingCode: 596, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	MR: { callingCode: 222, currency: { isoCode: "MRU", name: "Mauritanian ouguiya", symbol: "UM" } },
	MS: { callingCode: 1, currency: { isoCode: "XCD", name: "Eastern Caribbean dollar", symbol: "$" } },
	MT: { callingCode: 356, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	MU: { callingCode: 230, currency: { isoCode: "MUR", name: "Mauritian rupee", symbol: "₨" } },
	MV: { callingCode: 960, currency: { isoCode: "MVR", name: "Maldivian rufiyaa", symbol: ".ރ" } },
	MW: { callingCode: 265, currency: { isoCode: "MWK", name: "Malawian kwacha", symbol: "MK" } },
	MX: { callingCode: 52, currency: { isoCode: "MXN", name: "Mexican peso", symbol: "$" } },
	MY: { callingCode: 60, currency: { isoCode: "MYR", name: "Malaysian ringgit", symbol: "RM" } },
	MZ: { callingCode: 258, currency: { isoCode: "MZN", name: "Mozambican metical", symbol: "MT" } },
	NA: { callingCode: 264, currency: { isoCode: "NAD", name: "Namibian dollar", symbol: "$" } },
	NC: { callingCode: 687, currency: { isoCode: "XPF", name: "CFP franc", symbol: "₣" } },
	NE: { callingCode: 227, currency: { isoCode: "XOF", name: "West African CFA franc", symbol: "Fr" } },
	NF: { callingCode: 672, currency: { isoCode: "AUD", name: "Australian dollar", symbol: "$" } },
	NG: { callingCode: 234, currency: { isoCode: "NGN", name: "Nigerian naira", symbol: "₦" } },
	NI: { callingCode: 505, currency: { isoCode: "NIO", name: "Nicaraguan córdoba", symbol: "C$" } },
	NL: { callingCode: 31, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	NO: { callingCode: 47, currency: { isoCode: "NOK", name: "Norwegian krone", symbol: "kr" } },
	NP: { callingCode: 977, currency: { isoCode: "NPR", name: "Nepalese rupee", symbol: "₨" } },
	NR: { callingCode: 674, currency: { isoCode: "AUD", name: "Australian dollar", symbol: "$" } },
	NU: { callingCode: 683, currency: { isoCode: "NZD", name: "New Zealand dollar", symbol: "$" } },
	NZ: { callingCode: 64, currency: { isoCode: "NZD", name: "New Zealand dollar", symbol: "$" } },
	OM: { callingCode: 968, currency: { isoCode: "OMR", name: "Omani rial", symbol: "ر.ع." } },
	PA: { callingCode: 507, currency: { isoCode: "PAB", name: "Panamanian balboa", symbol: "B/." } },
	PE: { callingCode: 51, currency: { isoCode: "PEN", name: "Peruvian sol", symbol: "S/." } },
	PF: { callingCode: 689, currency: { isoCode: "XPF", name: "CFP franc", symbol: "₣" } },
	PG: { callingCode: 675, currency: { isoCode: "PGK", name: "Papua New Guinean kina", symbol: "K" } },
	PH: { callingCode: 63, currency: { isoCode: "PHP", name: "Philippine peso", symbol: "₱" } },
	PK: { callingCode: 92, currency: { isoCode: "PKR", name: "Pakistani rupee", symbol: "₨" } },
	PL: { callingCode: 48, currency: { isoCode: "PLN", name: "Polish złoty", symbol: "zł" } },
	PM: { callingCode: 508, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	PN: { callingCode: 64, currency: { isoCode: "NZD", name: "New Zealand dollar", symbol: "$" } },
	PR: { callingCode: 1, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	PS: { callingCode: 970, currency: { isoCode: "EGP", name: "Egyptian pound", symbol: "E£" } },
	PT: { callingCode: 351, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	PW: { callingCode: 680, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	PY: { callingCode: 595, currency: { isoCode: "PYG", name: "Paraguayan guaraní", symbol: "₲" } },
	QA: { callingCode: 974, currency: { isoCode: "QAR", name: "Qatari riyal", symbol: "ر.ق" } },
	RE: { callingCode: 262, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	RO: { callingCode: 40, currency: { isoCode: "RON", name: "Romanian leu", symbol: "lei" } },
	RS: { callingCode: 381, currency: { isoCode: "RSD", name: "Serbian dinar", symbol: "дин." } },
	RU: { callingCode: 7, currency: { isoCode: "RUB", name: "Russian ruble", symbol: "₽" } },
	RW: { callingCode: 250, currency: { isoCode: "RWF", name: "Rwandan franc", symbol: "Fr" } },
	SA: { callingCode: 966, currency: { isoCode: "SAR", name: "Saudi riyal", symbol: "ر.س" } },
	SB: { callingCode: 677, currency: { isoCode: "SBD", name: "Solomon Islands dollar", symbol: "$" } },
	SC: { callingCode: 248, currency: { isoCode: "SCR", name: "Seychellois rupee", symbol: "₨" } },
	SD: { callingCode: 249, currency: { isoCode: "SDG", name: "Sudanese pound", symbol: "PT" } },
	SE: { callingCode: 46, currency: { isoCode: "SEK", name: "Swedish krona", symbol: "kr" } },
	SG: { callingCode: 65, currency: { isoCode: "SGD", name: "Singapore dollar", symbol: "$" } },
	SH: { callingCode: 2, currency: { isoCode: "GBP", name: "Pound sterling", symbol: "£" } },
	SI: { callingCode: 386, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	SJ: { callingCode: 4779, currency: { isoCode: "NOK", name: "krone", symbol: "kr" } },
	SK: { callingCode: 421, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	SL: { callingCode: 232, currency: { isoCode: "SLL", name: "Sierra Leonean leone", symbol: "Le" } },
	SM: { callingCode: 378, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	SN: { callingCode: 221, currency: { isoCode: "XOF", name: "West African CFA franc", symbol: "Fr" } },
	SO: { callingCode: 252, currency: { isoCode: "SOS", name: "Somali shilling", symbol: "Sh" } },
	SR: { callingCode: 597, currency: { isoCode: "SRD", name: "Surinamese dollar", symbol: "$" } },
	SS: { callingCode: 211, currency: { isoCode: "SSP", name: "South Sudanese pound", symbol: "£" } },
	ST: { callingCode: 239, currency: { isoCode: "STN", name: "São Tomé and Príncipe dobra", symbol: "Db" } },
	SV: { callingCode: 503, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	SX: { callingCode: 1, currency: { isoCode: "ANG", name: "Netherlands Antillean guilder", symbol: "ƒ" } },
	SY: { callingCode: 963, currency: { isoCode: "SYP", name: "Syrian pound", symbol: "£" } },
	SZ: { callingCode: 268, currency: { isoCode: "SZL", name: "Swazi lilangeni", symbol: "L" } },
	TC: { callingCode: 1, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	TD: { callingCode: 235, currency: { isoCode: "XAF", name: "Central African CFA franc", symbol: "Fr" } },
	TF: { callingCode: 262, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	TG: { callingCode: 228, currency: { isoCode: "XOF", name: "West African CFA franc", symbol: "Fr" } },
	TH: { callingCode: 66, currency: { isoCode: "THB", name: "Thai baht", symbol: "฿" } },
	TJ: { callingCode: 992, currency: { isoCode: "TJS", name: "Tajikistani somoni", symbol: "ЅМ" } },
	TK: { callingCode: 690, currency: { isoCode: "NZD", name: "New Zealand dollar", symbol: "$" } },
	TL: { callingCode: 670, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	TM: { callingCode: 993, currency: { isoCode: "TMT", name: "Turkmenistan manat", symbol: "m" } },
	TN: { callingCode: 216, currency: { isoCode: "TND", name: "Tunisian dinar", symbol: "د.ت" } },
	TO: { callingCode: 676, currency: { isoCode: "TOP", name: "Tongan paʻanga", symbol: "T$" } },
	TR: { callingCode: 90, currency: { isoCode: "TRY", name: "Turkish lira", symbol: "₺" } },
	TT: { callingCode: 1, currency: { isoCode: "TTD", name: "Trinidad and Tobago dollar", symbol: "$" } },
	TV: { callingCode: 688, currency: { isoCode: "AUD", name: "Australian dollar", symbol: "$" } },
	TW: { callingCode: 886, currency: { isoCode: "TWD", name: "New Taiwan dollar", symbol: "$" } },
	TZ: { callingCode: 255, currency: { isoCode: "TZS", name: "Tanzanian shilling", symbol: "Sh" } },
	UA: { callingCode: 380, currency: { isoCode: "UAH", name: "Ukrainian hryvnia", symbol: "₴" } },
	UG: { callingCode: 256, currency: { isoCode: "UGX", name: "Ugandan shilling", symbol: "Sh" } },
	UM: { callingCode: 268, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	US: { callingCode: 1, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	UY: { callingCode: 598, currency: { isoCode: "UYU", name: "Uruguayan peso", symbol: "$" } },
	UZ: { callingCode: 998, currency: { isoCode: "UZS", name: "Uzbekistani soʻm", symbol: "so'm" } },
	VA: { callingCode: 3, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	VC: { callingCode: 1, currency: { isoCode: "XCD", name: "Eastern Caribbean dollar", symbol: "$" } },
	VE: { callingCode: 58, currency: { isoCode: "VES", name: "Venezuelan bolívar soberano", symbol: "Bs.S." } },
	VG: { callingCode: 1, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	VI: { callingCode: 1, currency: { isoCode: "USD", name: "United States dollar", symbol: "$" } },
	VN: { callingCode: 84, currency: { isoCode: "VND", name: "Vietnamese đồng", symbol: "₫" } },
	VU: { callingCode: 678, currency: { isoCode: "VUV", name: "Vanuatu vatu", symbol: "Vt" } },
	WF: { callingCode: 681, currency: { isoCode: "XPF", name: "CFP franc", symbol: "₣" } },
	WS: { callingCode: 685, currency: { isoCode: "WST", name: "Samoan tālā", symbol: "T" } },
	XK: { callingCode: 383, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	YE: { callingCode: 967, currency: { isoCode: "YER", name: "Yemeni rial", symbol: "﷼" } },
	YT: { callingCode: 262, currency: { isoCode: "EUR", name: "Euro", symbol: "€" } },
	ZA: { callingCode: 27, currency: { isoCode: "ZAR", name: "South African rand", symbol: "R" } },
	ZM: { callingCode: 260, currency: { isoCode: "ZMW", name: "Zambian kwacha", symbol: "ZK" } },
	ZW: { callingCode: 263, currency: { isoCode: "BWP", name: "Botswana pula", symbol: "P" } },
}
