/**
 * @copyright Sister Software
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 */

import { writeLocalTextFile, makeDirectories, writeLocalJSONFile } from "@mailwoman/core/fs/writers"
import { CommandError } from "@mailwoman/core/scripting/command"
import { Box, Text } from "ink"
import { PathBuilder } from "path-ts"

import { type CommandSpec, CommandTaskResult, type CommandComponent, splitCountryCodes, useCommandTask } from "#cli-kit"

// Overture prunes old releases from its bucket, so a stale pin makes the default ingest fail.
// Keep this pin in step with `DEFAULT_RELEASE` in `gazetteer-pipeline/poi/defaults.ts`.
const DEFAULT_RELEASE = "2026-07-22.0"

const S3_GLOB = (release: string) =>
	`s3://overturemaps-us-west-2/release/${release}/theme=addresses/type=address/*.parquet`

/**
 * The address fields whose fill rates the report measures.
 */
const FILL_FIELDS = ["postcode", "street", "number", "unit", "postal_city"] as const

interface CountryProbe {
	country: string
	rows: number
	fill_pct: Record<string, number>
	address_levels_pct: number
	datasets: Record<string, number>
	oa_lineage_pct: number
}

/**
 * Command specification for `gazetteer overture-ingest`, which copies Overture address
 * rows into per-country Parquet files and writes a fill-rate report.
 *
 * Every output lands under `<out>/<release>/`, so rows from two releases never mix in one directory.
 */
export const spec = {
	name: "overture-ingest",
	description: "Ingest and probe Overture addresses",
	options: {
		release: { type: "string", description: `Pinned release. Default ${DEFAULT_RELEASE}` },
		countries: { type: "string", required: true, description: "Comma-separated ISO country codes" },
		limit: { type: "string", description: "Rows per country" },
		out: { type: "string", description: "Output root" },
		"probe-only": { type: "boolean", default: false, description: "Only probe local Parquet" },
		"corpus-jsonl": { type: "boolean", default: false, description: "Emit corpus JSONL" },
		sample: { type: "string", description: "Reservoir-sample the corpus JSONL to this many rows" },
		seed: { type: "string", description: "Seed for --sample. Default 20260922" },
	},
} as const satisfies CommandSpec

function renderMarkdown(release: string, probes: CountryProbe[]): string {
	const lines = [
		`# Overture addresses fill-rate report — release ${release}`,
		"",
		`Generated by \`mailwoman gazetteer overture-ingest\` (#471). Check rule (epic #470): no`,
		`downstream issue proceeds on a country whose relevant field fills <80% without a note.`,
		"",
		"| country | rows | postcode | street | number | unit | postal_city | address_levels | OA-lineage |",
		"| --- | --: | --: | --: | --: | --: | --: | --: | --: |",
	]

	for (const p of probes) {
		lines.push(
			`| ${p.country} | ${p.rows.toLocaleString("en-US")} | ${p.fill_pct.postcode}% | ${p.fill_pct.street}% | ` +
				`${p.fill_pct.number}% | ${p.fill_pct.unit}% | ${p.fill_pct.postal_city}% | ` +
				`${p.address_levels_pct}% | ${p.oa_lineage_pct}% |`
		)
	}

	lines.push("", "## Observed source datasets (per country)", "")

	for (const p of probes) {
		lines.push(`### ${p.country}`, "")

		for (const [ds, n] of Object.entries(p.datasets)) {
			lines.push(`- \`${ds}\` — ${n.toLocaleString("en-US")} rows`)
		}

		lines.push("")
	}

	return lines.join("\n")
}

const GazetteerOvertureIngest: CommandComponent<typeof spec> = ({ options }) => {
	const state = useCommandTask(async () => {
		const { dataRootPath } = await import("@mailwoman/core/data-root")

		if (!options.countries) {
			throw new CommandError("--countries is required (ISO 3166-1 alpha-2, comma-separated, e.g. US,DE,FR)")
		}

		const release = options.release ?? DEFAULT_RELEASE
		const countries = splitCountryCodes(options.countries)
		const limit = options.limit ? Number.parseInt(options.limit, 10) : undefined
		// The default seed is fixed so that repeated samples of one release write the same rows.
		const seed = options.seed ? Number.parseInt(options.seed, 10) : 20_260_922
		const outRoot = PathBuilder.from(options.out ?? dataRootPath("overture"))
		const outDir = outRoot(release)
		await makeDirectories(outDir)

		// `@duckdb/node-api` is an optional peer, so it loads here to keep `--help` working without it.
		const { DuckDBInstance } = await import("@duckdb/node-api")
		const instance = await DuckDBInstance.create()
		const db = await instance.connect()

		// The Overture bucket is public, so DuckDB needs only the region and no credentials.
		await db.run("INSTALL httpfs; LOAD httpfs;")
		await db.run("INSTALL spatial; LOAD spatial;")
		await db.run("SET s3_region='us-west-2';")
		// DuckDB's defaults can exhaust memory on the addresses theme.
		// The COPY streams to disk, so these limits cost little.
		await db.run("SET threads=4;")
		await db.run("SET memory_limit='8GB';")

		const countryParquet = (cc: string) => outDir(`addresses-${cc.toLowerCase()}.parquet`)

		/**
		 * Copies one country's rows into local Parquet.
		 *
		 * The copy keeps the Overture columns unchanged, including the nested `sources` that
		 * evaluation filtering relies on, and adds `lon` and `lat` decoded from the point geometry.
		 */
		const ingestCountry = async (cc: string): Promise<void> => {
			const limitClause = limit ? `LIMIT ${limit}` : ""
			const dest = countryParquet(cc)
			const started = Date.now()

			await db.run(`
				COPY (
					SELECT
						id,
						country,
						postcode,
						street,
						number,
						unit,
						address_levels,
						postal_city,
						sources,
						version,
						ST_X(geometry) AS lon,
						ST_Y(geometry) AS lat
					FROM read_parquet('${S3_GLOB(release)}', hive_partitioning = 1)
					WHERE country = '${cc}'
					${limitClause}
				) TO '${dest}' (FORMAT PARQUET, COMPRESSION SNAPPY)
			`)

			const secs = ((Date.now() - started) / 1000).toFixed(0)

			console.error(`[ingest] ${cc} -> ${dest} (${secs}s)`)
		}

		/**
		 * Writes the flattened JSONL that the `overture` corpus adapter reads,
		 * so `@mailwoman/corpus` does not need DuckDB.
		 *
		 * The `locality` field is `postal_city` when present and otherwise the deepest `address_levels` value.
		 *
		 * Overture stores a country's rows in spatial order, so the first n rows cover one region.
		 * The `--sample` option therefore draws a reservoir sample across the whole file.
		 */
		const emitCorpusJSONL = async (cc: string): Promise<void> => {
			const src = countryParquet(cc)
			const dest = outDir(`overture-${cc.toLowerCase()}.corpus.jsonl`)
			const sampleClause = options.sample ? ` USING SAMPLE ${Number(options.sample)} ROWS (reservoir, ${seed})` : ""

			await db.run(`
				COPY (
					SELECT
						street,
						number,
						unit,
						postcode,
						COALESCE(NULLIF(trim(postal_city), ''), address_levels[len(address_levels)].value) AS locality
					FROM read_parquet('${src}')
					WHERE street IS NOT NULL AND trim(street) <> ''
						AND (
							(postcode IS NOT NULL AND trim(postcode) <> '')
							OR len(address_levels) > 0
							OR (postal_city IS NOT NULL AND trim(postal_city) <> '')
						)
					${sampleClause}
				) TO '${dest}' (FORMAT JSON)
			`)

			console.error(`[corpus-jsonl] ${cc} -> ${dest}${options.sample ? ` (sample ${options.sample})` : ""}`)
		}

		/**
		 * Measures one country's local Parquet for the fill-rate report, returning `null` when it has no rows.
		 */
		const probeCountry = async (cc: string): Promise<CountryProbe | null> => {
			const src = countryParquet(cc)

			const fillExprs = FILL_FIELDS.map(
				(f) => `round(100.0 * count(nullif(trim(${f}), '')) / count(*), 1) AS ${f}_pct`
			).join(",\n\t\t\t")

			const totals = await db.runAndReadAll(`
				SELECT
					count(*)::BIGINT AS rows,
					${fillExprs},
					round(100.0 * count(*) FILTER (len(address_levels) > 0) / count(*), 1) AS address_levels_pct,
					round(100.0 * count(*) FILTER (
						len(list_filter(sources, s -> s.dataset ILIKE '%openaddress%')) > 0
					) / count(*), 1) AS oa_lineage_pct
				FROM read_parquet('${src}')
			`)

			const row = totals.getRowObjects()[0] as Record<string, unknown>

			if (!row || Number(row.rows) === 0) return null

			const datasetRows = await db.runAndReadAll(`
				SELECT u.dataset AS dataset, count(*)::BIGINT AS n
				FROM (SELECT unnest(sources) AS u FROM read_parquet('${src}'))
				GROUP BY 1 ORDER BY n DESC
			`)

			const datasets: Record<string, number> = {}

			for (const d of datasetRows.getRowObjects() as { dataset: string; n: bigint }[]) {
				datasets[d.dataset ?? "(null)"] = Number(d.n)
			}

			const fill_pct: Record<string, number> = {}

			for (const f of FILL_FIELDS) {
				fill_pct[f] = Number(row[`${f}_pct`])
			}

			return {
				country: cc,
				rows: Number(row.rows),
				fill_pct,
				address_levels_pct: Number(row.address_levels_pct),
				datasets,
				oa_lineage_pct: Number(row.oa_lineage_pct),
			}
		}

		const probes: CountryProbe[] = []

		for (const cc of countries) {
			if (!options.probeOnly) {
				await ingestCountry(cc)
			}

			if (options.corpusJSONL) {
				await emitCorpusJSONL(cc)
			}

			const probe = await probeCountry(cc)

			if (probe) {
				probes.push(probe)

				console.error(
					`[probe] ${cc}: ${probe.rows} rows · postcode ${probe.fill_pct.postcode}% · ` +
						`postal_city ${probe.fill_pct.postal_city}% · OA-lineage ${probe.oa_lineage_pct}%`
				)
			} else {
				console.error(`[probe] ${cc}: no rows found — check the country code or release`)
			}
		}

		await writeLocalJSONFile({ release, probes }, outDir, "fill-rates.json")
		await writeLocalTextFile(renderMarkdown(release, probes), outDir, "fill-rates.md")

		console.error(`[done] report -> ${outDir("fill-rates.{json,md}")}`)

		db.closeSync()

		return [
			`overture ingest: ${outDir}`,
			`release ${release} · ${countries.join(",")} · ${probes.length} probed`,
			`report: fill-rates.json + fill-rates.md`,
			...probes.map(
				(p) =>
					`${p.country}: ${p.rows.toLocaleString("en-US")} rows · postcode ${p.fill_pct.postcode}% · OA ${p.oa_lineage_pct}%`
			),
		]
	})

	if (state.status !== "done") return <CommandTaskResult state={state} />

	if (state.status === "done") {
		return (
			<Box flexDirection="column">
				{state.result.map((line, i) => (
					<Text key={i} color={i === 0 ? "green" : undefined}>
						{i === 0 ? "✓ " : "  "}
						{line}
					</Text>
				))}
			</Box>
		)
	}

	return null
}

export default GazetteerOvertureIngest
