import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// One sidebar per top-level section. The docs sub-header (src/components/DocsSubHeader)
// is the section switcher, so the sidebar no longer wraps each section in a collapsible
// category — every section's docs sit at the top level of their own sidebar, one
// hierarchy level shallower. The sidebar ids here are the single source of truth for
// the switcher (see src/components/DocsSubHeader/sections.ts, which must list the same
// ids in display order). Each doc belongs to exactly one sidebar, so Docusaurus shows
// the right one automatically.
//
// Section intent (docs-architecture cleanup, Phase 1 — navigation curation):
// - startHere / use / understand are guidance: onboarding, task recipes, and the why/how
//   narrative. understand also folds in the old top-level `concepts` sidebar as its last
//   category, so "Concept deep dives" no longer needs its own switcher tab.
// - reference is the authoritative contract layer (SCOPE + the plan/reference/ pages that
//   the Phase 0 inventory marked keep/rewrite/merge), plus a category for the two still-open
//   dated design docs.
// - contribute is maintainer/contributor runbooks — how to work on the project, not lookup
//   contracts.
// - archive is the historical record: phase plans, dated plan-root specs, and the six
//   superseded plan/reference/ pages the inventory marked archive. Nothing moves here from
//   concepts/ or understanding/ in Phase 1 — that's per-page pruning, deferred to Phase 2.
// - evals / retrospectives are untouched, owned by a separate workstream.
// - legal (licensing/) is newly added to the switcher — it already had a sidebar but was
//   missing from sections.ts, reachable only via a separate top-navbar link.
const sidebars: SidebarsConfig = {
	// Explicit (not autogenerated): these live at the articles/ root alongside orphans
	// like sotm-2026-talk-proposal that should stay out of the nav. getting-started is first
	// so the navbar's "Docs" docSidebar link (docusaurus.config.ts) resolves to it instead of
	// the old front door, status.
	startHere: ["getting-started", "api", "status", "releases", "contributing", "documentation-map"],
	use: [
		{
			type: "autogenerated",
			dirName: "recipes",
		},
	],
	understand: [
		// understanding/README.mdx pinned first — autogenerated placement wouldn't reliably
		// surface it ahead of the categories below.
		"understanding/README",
		{
			type: "category",
			label: "The Problem",
			items: [
				{
					type: "autogenerated",
					dirName: "understanding/the-problem",
				},
			],
		},
		{
			type: "category",
			label: "Why It's Hard",
			items: [
				{
					type: "autogenerated",
					dirName: "understanding/why-its-hard",
				},
			],
		},
		{
			type: "category",
			label: "Alternatives",
			items: [
				{
					type: "autogenerated",
					dirName: "understanding/alternatives",
				},
			],
		},
		{
			type: "category",
			label: "Our Approach",
			items: [
				{
					type: "autogenerated",
					dirName: "understanding/our-approach",
				},
			],
		},
		{
			type: "category",
			label: "Exotic POI",
			items: [
				{
					type: "autogenerated",
					dirName: "understanding/exotic-poi",
				},
			],
		},
		{
			type: "category",
			label: "Concepts",
			items: [
				{
					type: "autogenerated",
					dirName: "concepts",
				},
			],
		},
		// A narrow, dated debugging gotcha that doesn't fit any of the categories above.
		// Kept in-nav per "do not drop pages" — parked at the end as an appendix.
		"understanding/onnxruntime-web-webgpu-gotcha",
	],
	reference: [
		"plan/SCOPE",
		{
			type: "category",
			label: "Active design decisions",
			items: ["plan/2026-06-29-joint-consistency-resolution", "plan/2026-07-03-exonym-prominence"],
		},
		"plan/reference/ARCHITECTURE",
		"plan/reference/SCHEMA",
		"plan/reference/INTERFACES",
		"plan/reference/STAGES",
		"plan/reference/QUERY_SHAPE",
		"plan/reference/closed-vocab-fields-model-first",
		"plan/reference/FST_GAZETTEER_LM",
		"plan/reference/TRAINING_RECIPE_LEVERS",
		"plan/reference/runtime-flags",
		"plan/reference/address-data-sources",
		"plan/reference/record-matcher-sources",
		"plan/reference/sentencepiece-uds-whitespace",
	],
	contribute: [
		"plan/CONTRIBUTING_MODEL_WORK",
		"plan/reference/OPERATIONS",
		"plan/reference/coverage-overlay",
		"plan/reference/VERDICT_SMOKES",
		"plan/reference/WIKIPEDIA_IMPORTANCE",
	],
	archive: [
		{
			type: "category",
			label: "Phase plans",
			items: [
				{
					type: "autogenerated",
					dirName: "plan/phases",
				},
			],
		},
		{
			type: "category",
			label: "Dated plans & specs",
			items: [
				"plan/README",
				"plan/2026-05-30-pretraining-experiment-spec",
				"plan/2026-05-30-resolver-routing-plan",
				"plan/2026-06-03-anchor-based-parsing",
				"plan/2026-06-04-coordinate-first-resolver",
				"plan/2026-06-04-pr3-self-conditioned-retrain",
				"plan/2026-06-05-geographic-rule-engine",
				"plan/2026-06-09-parity-endgame",
				"plan/v0-5-0-shipped",
				"plan/2026-06-11-char-offset-labels-design",
				"plan/2026-06-11-geocoder-table-stakes-scoping",
				"plan/2026-06-11-interpolation-design",
				"plan/2026-06-11-resolution-ladder",
				"plan/2026-06-11-subpremise-proposer-direction",
				"plan/2026-06-11-transition-masks-design",
				"plan/2026-06-11-v0.5.0-rebuild-plan",
				"plan/2026-06-14-arbitration-layer-spec",
				"plan/2026-06-14-client-side-geocoder-demo-spec",
				"plan/2026-06-14-coarse-placer-m2-verdict",
				"plan/2026-06-14-coarse-placer-soft-signal-spec",
				"plan/2026-06-19-coordinate-leverage-sprint",
				"plan/migrate-readline-to-spliterator",
			],
		},
		{
			type: "category",
			label: "Reference (superseded)",
			items: [
				"plan/reference/CONTEXT",
				"plan/reference/CORPUS_V0_4_0_GENERATION",
				"plan/reference/DEMO_PRESET_DIAGNOSIS",
				"plan/reference/tokenizer-a0-baseline",
				"plan/reference/tokenizer-a1-results",
				"plan/reference/TRAINING_ENV",
			],
		},
	],
	evals: [
		{
			type: "autogenerated",
			dirName: "evals",
		},
	],
	retrospectives: [
		{
			type: "autogenerated",
			dirName: "retrospectives",
		},
	],
	legal: [
		{
			type: "autogenerated",
			dirName: "licensing",
		},
	],
}

export default sidebars
