import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
	tutorialSidebar: [
		{
			type: "category",
			label: "Start here",
			collapsed: false,
			items: [
				"status",
				"getting-started",
				"api",
			],
		},
		{
			type: "category",
			label: "Understanding Mailwoman",
			link: { type: "doc", id: "understanding/README" },
			collapsed: true,
			items: [{ type: "autogenerated", dirName: "understanding" }],
		},
		{
			type: "category",
			label: "Concept deep dives",
			link: { type: "doc", id: "concepts/README" },
			collapsed: true,
			items: [{ type: "autogenerated", dirName: "concepts" }],
		},
		{
			type: "category",
			label: "Implementation plan 🧪",
			link: { type: "doc", id: "plan/README" },
			collapsed: true,
			items: [{ type: "autogenerated", dirName: "plan" }],
		},
		{
			type: "category",
			label: "Eval reports",
			collapsed: true,
			items: [{ type: "autogenerated", dirName: "evals" }],
		},
		{
			type: "category",
			label: "Retrospectives",
			link: { type: "doc", id: "retrospectives/README" },
			collapsed: true,
			items: [{ type: "autogenerated", dirName: "retrospectives" }],
		},
	],
}

export default sidebars
